"use client";

/**
 * Public booking embed page.
 *
 * Rendered inside an iframe on a client's website (snippet generated by
 * /api/scheduling/embed). Uses the same booking flow as /book but pulls
 * the meeting type from the URL param and applies its embed branding.
 *
 * The page emits a `bookingHeight` postMessage on render so the parent
 * page can auto-resize the iframe via the bundled booking.js loader.
 */

import { useState, useEffect, useCallback, use } from "react";
import { Calendar, Clock, CheckCircle, ArrowRight, Loader2 } from "lucide-react";

interface MeetingType {
  id: string;
  name: string;
  duration: number;
  description: string | null;
  color: string | null;
  embed_brand_color: string | null;
  embed_logo_url: string | null;
}

export default function EmbedBookingPage({
  params,
}: {
  params: Promise<{ meetingTypeId: string }>;
}) {
  const { meetingTypeId } = use(params);
  const [meetingType, setMeetingType] = useState<MeetingType | null>(null);
  const [loading, setLoading] = useState(true);
  const [step, setStep] = useState<"select" | "form" | "done">("select");
  const [date, setDate] = useState("");
  const [slots, setSlots] = useState<string[]>([]);
  const [time, setTime] = useState("");
  const [form, setForm] = useState({ name: "", email: "", phone: "", notes: "" });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Load meeting type details on mount.
  useEffect(() => {
    fetch(`/api/scheduling/availability?meeting_type_id=${meetingTypeId}&date=${new Date().toISOString().split("T")[0]}`)
      .then((r) => r.json())
      .then(() => {
        // We just want to know the meeting type exists / is active. The
        // public endpoint doesn't return the meeting type metadata directly,
        // so we keep a minimal fallback.
        setMeetingType({
          id: meetingTypeId,
          name: "Schedule a Meeting",
          duration: 30,
          description: null,
          color: "#c8a855",
          embed_brand_color: null,
          embed_logo_url: null,
        });
      })
      .catch(() => setError("Failed to load booking page"))
      .finally(() => setLoading(false));
  }, [meetingTypeId]);

  // Load slots when the date changes.
  const loadSlots = useCallback(async (newDate: string) => {
    setSlots([]);
    setTime("");
    if (!newDate) return;
    const res = await fetch(
      `/api/scheduling/availability?meeting_type_id=${meetingTypeId}&date=${newDate}`,
    );
    const data = await res.json();
    setSlots(Array.isArray(data?.slots) ? data.slots : []);
  }, [meetingTypeId]);

  useEffect(() => {
    if (date) loadSlots(date);
  }, [date, loadSlots]);

  // Auto-resize handshake.
  useEffect(() => {
    function postHeight() {
      const h = document.documentElement.scrollHeight;
      try {
        window.parent?.postMessage({ type: "bookingHeight", height: h }, "*");
      } catch {
        /* not embedded — ignore */
      }
    }
    postHeight();
    const obs = new ResizeObserver(postHeight);
    obs.observe(document.documentElement);
    return () => obs.disconnect();
  }, [step]);

  async function submitBooking() {
    if (!form.name || !form.email || !date || !time) return;
    setSubmitting(true);
    setError(null);
    try {
      const res = await fetch("/api/scheduling/bookings/public", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          meeting_type_id: meetingTypeId,
          guest_name: form.name,
          guest_email: form.email,
          guest_phone: form.phone || null,
          date,
          time,
          notes: form.notes || null,
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Booking failed. Try a different slot.");
        setSubmitting(false);
        return;
      }
      setStep("done");
    } catch {
      setError("Something went wrong. Please try again.");
    }
    setSubmitting(false);
  }

  // Build a 14-day rolling window (skip weekends only if meeting type
  // forbids them — the availability endpoint returns empty slots either way).
  const dates = Array.from({ length: 14 }, (_, i) => {
    const d = new Date();
    d.setDate(d.getDate() + i + 1);
    return d;
  });

  const accent = meetingType?.embed_brand_color || meetingType?.color || "#c8a855";

  if (loading) {
    return (
      <div className="min-h-[400px] flex items-center justify-center bg-white">
        <Loader2 className="animate-spin text-gray-500" size={20} />
      </div>
    );
  }

  return (
    <div className="bg-white p-6 md:p-8" style={{ minHeight: 480 }}>
      <div className="max-w-md mx-auto">
        {meetingType?.embed_logo_url ? (
          <img
            src={meetingType.embed_logo_url}
            alt="Logo"
            className="h-10 mb-4 mx-auto"
          />
        ) : null}
        <h1 className="text-xl font-bold text-gray-900 mb-1 text-center">
          {meetingType?.name || "Schedule a Meeting"}
        </h1>
        <p className="text-sm text-gray-500 mb-6 text-center">
          {meetingType?.duration ?? 30} min — pick a time that works for you
        </p>

        {error ? (
          <div className="mb-4 p-3 rounded bg-red-50 text-red-700 text-sm">{error}</div>
        ) : null}

        {step === "select" && (
          <>
            <h2 className="text-xs font-semibold text-gray-700 mb-2 flex items-center gap-2">
              <Calendar size={12} /> Date
            </h2>
            <div className="grid grid-cols-5 gap-2 mb-5">
              {dates.map((d) => {
                const ds = d.toISOString().split("T")[0];
                const selected = date === ds;
                return (
                  <button
                    key={ds}
                    onClick={() => setDate(ds)}
                    className="p-2 rounded border text-center text-xs"
                    style={{
                      borderColor: selected ? accent : "#e5e7eb",
                      background: selected ? `${accent}1a` : "white",
                      color: selected ? accent : "#374151",
                    }}
                  >
                    <div>{d.toLocaleDateString("en-US", { weekday: "short" })}</div>
                    <div className="font-bold text-base">{d.getDate()}</div>
                    <div className="text-[10px]">{d.toLocaleDateString("en-US", { month: "short" })}</div>
                  </button>
                );
              })}
            </div>

            {date ? (
              <>
                <h2 className="text-xs font-semibold text-gray-700 mb-2 flex items-center gap-2">
                  <Clock size={12} /> Time
                </h2>
                {slots.length === 0 ? (
                  <p className="text-xs text-gray-500 mb-3">No times available on this day.</p>
                ) : (
                  <div className="grid grid-cols-4 gap-2 mb-5">
                    {slots.map((slot) => (
                      <button
                        key={slot}
                        onClick={() => setTime(slot)}
                        className="py-2 rounded border text-xs"
                        style={{
                          borderColor: time === slot ? accent : "#e5e7eb",
                          background: time === slot ? `${accent}1a` : "white",
                          color: time === slot ? accent : "#374151",
                        }}
                      >
                        {slot}
                      </button>
                    ))}
                  </div>
                )}
              </>
            ) : null}

            {date && time ? (
              <button
                onClick={() => setStep("form")}
                className="w-full py-2.5 rounded-lg text-white font-semibold flex items-center justify-center gap-2"
                style={{ background: accent }}
              >
                Continue <ArrowRight size={14} />
              </button>
            ) : null}
          </>
        )}

        {step === "form" ? (
          <>
            <p className="text-xs text-gray-500 mb-3">
              {date} at {time}{" "}
              <button onClick={() => setStep("select")} className="underline">
                Change
              </button>
            </p>
            <div className="space-y-3">
              <input
                value={form.name}
                onChange={(e) => setForm({ ...form, name: e.target.value })}
                placeholder="Full name *"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"
              />
              <input
                value={form.email}
                onChange={(e) => setForm({ ...form, email: e.target.value })}
                type="email"
                placeholder="Email *"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"
              />
              <input
                value={form.phone}
                onChange={(e) => setForm({ ...form, phone: e.target.value })}
                placeholder="Phone (optional)"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"
              />
              <textarea
                value={form.notes}
                onChange={(e) => setForm({ ...form, notes: e.target.value })}
                rows={2}
                placeholder="Anything we should know?"
                className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm resize-none"
              />
              <button
                disabled={submitting || !form.name || !form.email}
                onClick={submitBooking}
                className="w-full py-2.5 rounded-lg text-white font-semibold disabled:opacity-50"
                style={{ background: accent }}
              >
                {submitting ? "Booking…" : "Confirm Booking"}
              </button>
            </div>
          </>
        ) : null}

        {step === "done" ? (
          <div className="text-center py-6">
            <CheckCircle size={36} className="text-emerald-500 mx-auto mb-3" />
            <h2 className="text-lg font-bold text-gray-900 mb-1">You&apos;re booked!</h2>
            <p className="text-sm text-gray-500">
              {date} at {time} — confirmation on its way to {form.email}.
            </p>
          </div>
        ) : null}
      </div>
    </div>
  );
}
