/**
 * Design Studio — seed templates + clone helper.
 *
 * These 10 seed templates are minimal (bg color + text + optional shape) so
 * they render without external assets. Real previews get generated on first
 * export. Templates are inserted as global rows via the API seed route.
 */

import { v4 as uuidv4 } from "uuid";
import type { DesignDoc, Page, TextLayer, ShapeLayer, ImageLayer } from "./types";

function makeId() {
  return uuidv4();
}

function makePage(
  bg: string,
  layers: Array<TextLayer | ShapeLayer | ImageLayer>,
): Page {
  const layerMap: Record<string, TextLayer | ShapeLayer | ImageLayer> = {};
  const layerIds: string[] = [];
  layers.forEach((l, i) => {
    layerMap[l.id] = { ...l, zIndex: i };
    layerIds.push(l.id);
  });
  return {
    id: makeId(),
    name: "Page 1",
    backgroundColor: bg,
    layerIds,
    layers: layerMap,
  };
}

function text(overrides: Partial<TextLayer>): TextLayer {
  return {
    id: makeId(),
    kind: "text",
    name: overrides.name ?? "Text",
    x: 80,
    y: 200,
    width: 920,
    height: 120,
    rotation: 0,
    opacity: 1,
    locked: false,
    hidden: false,
    zIndex: 1,
    content: "Your Headline",
    fontFamily: "Inter",
    fontSize: 72,
    fontWeight: "800",
    fontStyle: "normal",
    textAlign: "center",
    color: "#ffffff",
    lineHeight: 1.1,
    letterSpacing: -1,
    textDecoration: "none",
    backgroundColor: null,
    padding: 0,
    borderRadius: 0,
    ...overrides,
  };
}

function shape(overrides: Partial<ShapeLayer>): ShapeLayer {
  return {
    id: makeId(),
    kind: "shape",
    name: "Background Shape",
    x: 0,
    y: 0,
    width: 1080,
    height: 1080,
    rotation: 0,
    opacity: 1,
    locked: true,
    hidden: false,
    zIndex: 0,
    shapeType: "rectangle",
    fill: "#1a1a2e",
    stroke: "transparent",
    strokeWidth: 0,
    borderRadius: 0,
    ...overrides,
  };
}

// ── 10 seed templates ─────────────────────────────────────────────────────────

export interface SeedTemplate {
  category: string;
  name: string;
  width: number;
  height: number;
  doc: DesignDoc;
}

export const SEED_TEMPLATES: SeedTemplate[] = [
  // 1. Instagram Quote
  {
    category: "Instagram",
    name: "Instagram Quote",
    width: 1080,
    height: 1080,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#16213e", [
          shape({ fill: "#16213e", width: 1080, height: 1080 }),
          shape({
            id: makeId(),
            name: "Accent Bar",
            x: 440,
            y: 420,
            width: 200,
            height: 6,
            fill: "#C9A84C",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 3,
          }),
          text({
            name: "Quote",
            x: 80,
            y: 300,
            width: 920,
            height: 180,
            content: '"Your inspiring quote goes here"',
            fontSize: 56,
            fontWeight: "700",
            fontStyle: "italic",
            color: "#ffffff",
            textAlign: "center",
            zIndex: 2,
          }),
          text({
            name: "Author",
            x: 80,
            y: 480,
            width: 920,
            height: 60,
            content: "— Author Name",
            fontSize: 28,
            fontWeight: "400",
            color: "#C9A84C",
            textAlign: "center",
            zIndex: 3,
          }),
        ]),
      ],
    },
  },

  // 2. Instagram Promo
  {
    category: "Instagram",
    name: "Instagram Promo",
    width: 1080,
    height: 1080,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#0f0f23", [
          shape({ fill: "#0f0f23", width: 1080, height: 1080 }),
          shape({
            id: makeId(),
            name: "Gradient Rect",
            x: 0,
            y: 600,
            width: 1080,
            height: 480,
            fill: "#8B6FCF",
            rotation: 0,
            opacity: 0.4,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
          text({
            name: "Label",
            x: 80,
            y: 580,
            width: 400,
            height: 50,
            content: "LIMITED OFFER",
            fontSize: 22,
            fontWeight: "700",
            color: "#C9A84C",
            textAlign: "left",
            letterSpacing: 4,
            zIndex: 2,
          }),
          text({
            name: "Headline",
            x: 80,
            y: 640,
            width: 920,
            height: 160,
            content: "50% OFF\nEverything",
            fontSize: 96,
            fontWeight: "800",
            color: "#ffffff",
            textAlign: "left",
            zIndex: 3,
          }),
          text({
            name: "CTA",
            x: 80,
            y: 860,
            width: 300,
            height: 60,
            content: "Shop Now →",
            fontSize: 28,
            fontWeight: "600",
            color: "#C9A84C",
            textAlign: "left",
            zIndex: 4,
          }),
        ]),
      ],
    },
  },

  // 3. Story Product
  {
    category: "Instagram",
    name: "Story Product",
    width: 1080,
    height: 1920,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#1a0533", [
          shape({ fill: "#1a0533", width: 1080, height: 1920 }),
          shape({
            id: makeId(),
            name: "Image Placeholder",
            x: 90,
            y: 300,
            width: 900,
            height: 900,
            fill: "#2d1052",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "#8B6FCF",
            strokeWidth: 2,
            borderRadius: 24,
          }),
          text({
            name: "Product Name",
            x: 80,
            y: 1280,
            width: 920,
            height: 100,
            content: "Product Name",
            fontSize: 64,
            fontWeight: "800",
            color: "#ffffff",
            textAlign: "center",
            zIndex: 2,
          }),
          text({
            name: "Price",
            x: 80,
            y: 1390,
            width: 920,
            height: 80,
            content: "$99 — Shop Now",
            fontSize: 40,
            fontWeight: "600",
            color: "#C9A84C",
            textAlign: "center",
            zIndex: 3,
          }),
        ]),
      ],
    },
  },

  // 4. YouTube Thumbnail Bold
  {
    category: "YouTube",
    name: "YouTube Thumbnail Bold",
    width: 1280,
    height: 720,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#0d0d0d", [
          shape({ fill: "#0d0d0d", width: 1280, height: 720 }),
          shape({
            id: makeId(),
            name: "Left Accent",
            x: 0,
            y: 0,
            width: 8,
            height: 720,
            fill: "#FF0000",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
          text({
            name: "Number",
            x: 40,
            y: 80,
            width: 400,
            height: 300,
            content: "#1",
            fontSize: 240,
            fontWeight: "900",
            color: "#FF0000",
            textAlign: "left",
            zIndex: 2,
          }),
          text({
            name: "Headline",
            x: 40,
            y: 400,
            width: 760,
            height: 180,
            content: "THE TRUTH\nABOUT THIS",
            fontSize: 88,
            fontWeight: "800",
            color: "#ffffff",
            textAlign: "left",
            lineHeight: 1.0,
            zIndex: 3,
          }),
        ]),
      ],
    },
  },

  // 5. Facebook Event
  {
    category: "Facebook",
    name: "Facebook Event",
    width: 1200,
    height: 630,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#0a1628", [
          shape({ fill: "#0a1628", width: 1200, height: 630 }),
          shape({
            id: makeId(),
            name: "Diagonal Accent",
            x: 700,
            y: 0,
            width: 500,
            height: 630,
            fill: "#1e3a5f",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
          text({
            name: "Event Label",
            x: 60,
            y: 80,
            width: 600,
            height: 50,
            content: "YOU'RE INVITED",
            fontSize: 22,
            fontWeight: "700",
            color: "#C9A84C",
            letterSpacing: 5,
            textAlign: "left",
            zIndex: 2,
          }),
          text({
            name: "Event Name",
            x: 60,
            y: 140,
            width: 620,
            height: 240,
            content: "Annual\nGala Night",
            fontSize: 100,
            fontWeight: "800",
            color: "#ffffff",
            textAlign: "left",
            lineHeight: 1.0,
            zIndex: 3,
          }),
          text({
            name: "Date",
            x: 60,
            y: 430,
            width: 600,
            height: 60,
            content: "Saturday, June 14 • 7:00 PM",
            fontSize: 28,
            fontWeight: "400",
            color: "#93C5FD",
            textAlign: "left",
            zIndex: 4,
          }),
        ]),
      ],
    },
  },

  // 6. LinkedIn Headline
  {
    category: "LinkedIn",
    name: "LinkedIn Headline",
    width: 1584,
    height: 396,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#0a66c2", [
          shape({ fill: "#0a66c2", width: 1584, height: 396 }),
          shape({
            id: makeId(),
            name: "Dark Overlay",
            x: 0,
            y: 0,
            width: 1584,
            height: 396,
            fill: "#051b2c",
            rotation: 0,
            opacity: 0.6,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
          text({
            name: "Name",
            x: 80,
            y: 60,
            width: 1400,
            height: 100,
            content: "Your Name | Your Title",
            fontSize: 56,
            fontWeight: "700",
            color: "#ffffff",
            textAlign: "left",
            zIndex: 2,
          }),
          text({
            name: "Tagline",
            x: 80,
            y: 180,
            width: 1400,
            height: 80,
            content: "Helping businesses grow with AI-powered systems",
            fontSize: 32,
            fontWeight: "400",
            color: "#93C5FD",
            textAlign: "left",
            zIndex: 3,
          }),
          shape({
            id: makeId(),
            name: "Bottom Line",
            x: 80,
            y: 310,
            width: 200,
            height: 4,
            fill: "#C9A84C",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 4,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 2,
          }),
        ]),
      ],
    },
  },

  // 7. LinkedIn Post
  {
    category: "LinkedIn",
    name: "LinkedIn Post",
    width: 1200,
    height: 627,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#f8f9fa", [
          shape({ fill: "#f8f9fa", width: 1200, height: 627 }),
          shape({
            id: makeId(),
            name: "Left Bar",
            x: 0,
            y: 0,
            width: 12,
            height: 627,
            fill: "#0a66c2",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
          text({
            name: "Statistic",
            x: 80,
            y: 80,
            width: 1100,
            height: 200,
            content: "73%",
            fontSize: 180,
            fontWeight: "900",
            color: "#0a66c2",
            textAlign: "left",
            zIndex: 2,
          }),
          text({
            name: "Insight",
            x: 80,
            y: 300,
            width: 1100,
            height: 100,
            content: "of businesses see ROI within 90 days",
            fontSize: 44,
            fontWeight: "600",
            color: "#1a1a2e",
            textAlign: "left",
            zIndex: 3,
          }),
          text({
            name: "Source",
            x: 80,
            y: 440,
            width: 1100,
            height: 50,
            content: "Source: Industry Report 2025",
            fontSize: 22,
            fontWeight: "400",
            color: "#666666",
            textAlign: "left",
            zIndex: 4,
          }),
        ]),
      ],
    },
  },

  // 8. Twitter/X Post
  {
    category: "Twitter/X",
    name: "Twitter/X Bold Post",
    width: 1600,
    height: 900,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#000000", [
          shape({ fill: "#000000", width: 1600, height: 900 }),
          shape({
            id: makeId(),
            name: "Circle Accent",
            x: 1100,
            y: -100,
            width: 700,
            height: 700,
            fill: "#C9A84C",
            rotation: 0,
            opacity: 0.15,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "ellipse",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
          text({
            name: "Headline",
            x: 80,
            y: 180,
            width: 1440,
            height: 400,
            content: "Hot take:\neverything you know\nis wrong.",
            fontSize: 100,
            fontWeight: "800",
            color: "#ffffff",
            textAlign: "left",
            lineHeight: 1.05,
            zIndex: 2,
          }),
          text({
            name: "Handle",
            x: 80,
            y: 760,
            width: 600,
            height: 60,
            content: "@yourhandle",
            fontSize: 30,
            fontWeight: "400",
            color: "#888888",
            textAlign: "left",
            zIndex: 3,
          }),
        ]),
      ],
    },
  },

  // 9. Minimal Brand Card
  {
    category: "General",
    name: "Minimal Brand Card",
    width: 1080,
    height: 1080,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#ffffff", [
          shape({ fill: "#ffffff", width: 1080, height: 1080 }),
          shape({
            id: makeId(),
            name: "Top Border",
            x: 0,
            y: 0,
            width: 1080,
            height: 8,
            fill: "#1a1a2e",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
          text({
            name: "Brand Name",
            x: 80,
            y: 100,
            width: 920,
            height: 80,
            content: "BRAND NAME",
            fontSize: 42,
            fontWeight: "800",
            color: "#1a1a2e",
            textAlign: "left",
            letterSpacing: 8,
            zIndex: 2,
          }),
          text({
            name: "Tagline",
            x: 80,
            y: 460,
            width: 920,
            height: 160,
            content: "Your tagline\ngoes here.",
            fontSize: 80,
            fontWeight: "300",
            color: "#1a1a2e",
            textAlign: "left",
            zIndex: 3,
          }),
          shape({
            id: makeId(),
            name: "Accent Dot",
            x: 80,
            y: 660,
            width: 16,
            height: 16,
            fill: "#C9A84C",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 4,
            shapeType: "ellipse",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
        ]),
      ],
    },
  },

  // 10. Facebook Story CTA
  {
    category: "Facebook",
    name: "Facebook Story CTA",
    width: 1080,
    height: 1920,
    doc: {
      version: 1,
      activePageIndex: 0,
      pages: [
        makePage("#2d1052", [
          shape({ fill: "#2d1052", width: 1080, height: 1920 }),
          shape({
            id: makeId(),
            name: "Bottom Card",
            x: 0,
            y: 1200,
            width: 1080,
            height: 720,
            fill: "#ffffff",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 1,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 0,
          }),
          text({
            name: "Top Label",
            x: 80,
            y: 200,
            width: 920,
            height: 60,
            content: "DON'T MISS OUT",
            fontSize: 32,
            fontWeight: "700",
            color: "#C9A84C",
            textAlign: "center",
            letterSpacing: 4,
            zIndex: 2,
          }),
          text({
            name: "Main Headline",
            x: 80,
            y: 300,
            width: 920,
            height: 300,
            content: "Big Sale\nStarts\nToday",
            fontSize: 110,
            fontWeight: "800",
            color: "#ffffff",
            textAlign: "center",
            lineHeight: 1.0,
            zIndex: 3,
          }),
          text({
            name: "CTA Headline",
            x: 80,
            y: 1280,
            width: 920,
            height: 100,
            content: "Get 40% Off",
            fontSize: 64,
            fontWeight: "800",
            color: "#2d1052",
            textAlign: "center",
            zIndex: 4,
          }),
          text({
            name: "CTA Sub",
            x: 80,
            y: 1400,
            width: 920,
            height: 60,
            content: "Use code SAVE40 at checkout",
            fontSize: 32,
            fontWeight: "400",
            color: "#666666",
            textAlign: "center",
            zIndex: 5,
          }),
          shape({
            id: makeId(),
            name: "CTA Button",
            x: 240,
            y: 1520,
            width: 600,
            height: 90,
            fill: "#2d1052",
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            zIndex: 6,
            shapeType: "rectangle",
            stroke: "transparent",
            strokeWidth: 0,
            borderRadius: 45,
          }),
          text({
            name: "Button Text",
            x: 240,
            y: 1533,
            width: 600,
            height: 64,
            content: "Shop Now",
            fontSize: 32,
            fontWeight: "700",
            color: "#ffffff",
            textAlign: "center",
            zIndex: 7,
          }),
        ]),
      ],
    },
  },
];

/**
 * Deep-clone a template doc, replacing all layer ids and the page id
 * with fresh UUIDs so the new design is fully independent.
 */
export function cloneTemplateDoc(doc: DesignDoc): DesignDoc {
  const cloned: DesignDoc = JSON.parse(JSON.stringify(doc)) as DesignDoc;
  cloned.pages = cloned.pages.map((page) => {
    const idMap: Record<string, string> = {};
    const newPage = { ...page, id: uuidv4() };
    newPage.layerIds = page.layerIds.map((oldId) => {
      const newId = uuidv4();
      idMap[oldId] = newId;
      return newId;
    });
    const newLayers: typeof page.layers = {};
    for (const [oldId, layer] of Object.entries(page.layers)) {
      const newId = idMap[oldId] ?? uuidv4();
      newLayers[newId] = { ...layer, id: newId };
    }
    newPage.layers = newLayers;
    return newPage;
  });
  return cloned;
}
