import { NextRequest, NextResponse } from "next/server";
import { createServerSupabase } from "@/lib/supabase/server";
import { checkAiRateLimit } from "@/lib/api-rate-limit";
import { safeJsonParse } from "@/lib/ai/claude-helpers";
import { callLLM } from "@/lib/ai/llm-router";
import { ALL_PLATFORMS, FALLBACK_HASHTAGS } from "@/lib/social-studio/constants";
import type { ContentIdea, SocialPlatform, TrendsResponse } from "@/lib/social-studio/types";

/**
 * GET /api/social/trends?niche=<niche>
 *
 * Returns:
 *  - hashtags_by_platform: top hashtags per platform (Zernio when
 *    available, fallback dictionary otherwise — all keyed by the niche
 *    string).
 *  - ideas: 10 short post ideas for the next ~7 days, generated by
 *    Claude Haiku. Refresh button on the UI hits the same route.
 *
 * v1 doesn't yet hit a Zernio "trending hashtags" endpoint — Zernio
 * doesn't expose that publicly. Once we ship a webhook that mirrors
 * trending tags into a `social_trending_hashtags` table this route
 * will read from there. For now we serve the curated FALLBACK_HASHTAGS
 * augmented with niche-aware tags from Claude.
 */
interface ClaudeTrendsResponse {
  ideas: ContentIdea[];
  niche_hashtags?: Partial<Record<SocialPlatform, string[]>>;
}

const SYSTEM_PROMPT = `You are a social media trends researcher. The user gives you a niche (e.g. "digital marketing agency", "fitness coach", "ecommerce founder") and you return:
1. 10 concrete post ideas for the next ~7 days. Each idea has: title (under 70 chars), hook (under 140 chars), format (one of: reel, carousel, single-image, thread, short-form-video, long-form-video, text-post), platforms (subset of: instagram, tiktok, linkedin, facebook, twitter, youtube, pinterest, threads).
2. Up to 8 niche-specific hashtags per platform that complement generic ones.

Mix evergreen + timely. Avoid generic clickbait. STRICT JSON output, no prose, no markdown fences:
{
  "ideas": [
    { "title": "...", "hook": "...", "format": "...", "platforms": ["..."] }
  ],
  "niche_hashtags": {
    "instagram": ["#tag", ...],
    "linkedin": ["#tag", ...]
  }
}`;

function mergeHashtags(
  fallback: Record<SocialPlatform, string[]>,
  niche: Partial<Record<SocialPlatform, string[]>> | undefined,
): Partial<Record<SocialPlatform, string[]>> {
  const merged: Partial<Record<SocialPlatform, string[]>> = {};
  for (const platform of ALL_PLATFORMS) {
    const generic = fallback[platform];
    const nicheTags = niche?.[platform] ?? [];
    const seen = new Set<string>();
    const combined: string[] = [];
    for (const tag of [...nicheTags, ...generic]) {
      const normalised = tag.startsWith("#") ? tag : `#${tag}`;
      const key = normalised.toLowerCase();
      if (!seen.has(key) && normalised.length > 1) {
        seen.add(key);
        combined.push(normalised);
        if (combined.length >= 15) break;
      }
    }
    merged[platform] = combined;
  }
  return merged;
}

const DEFAULT_IDEAS: ContentIdea[] = [
  { title: "Behind-the-scenes: how we built last week's project",      hook: "Most people don't see what goes into a launch — here's the unfiltered process.", format: "reel",       platforms: ["instagram", "tiktok"] },
  { title: "3 mistakes I made my first year",                          hook: "If I could go back, here are the three things I'd skip.",                       format: "carousel",   platforms: ["instagram", "linkedin"] },
  { title: "The 1-page brief I send every new client",                 hook: "Steal this. It's saved me hours every kickoff.",                                format: "carousel",   platforms: ["linkedin", "instagram"] },
  { title: "Watch me edit this in 60 seconds",                         hook: "Speed-edit timelapse with on-screen commentary.",                               format: "short-form-video", platforms: ["tiktok", "instagram", "youtube"] },
  { title: "Tools I use daily — ranked",                               hook: "Honest stack rank, with what I'd cut.",                                         format: "thread",     platforms: ["twitter", "threads"] },
  { title: "Client win story (anonymised)",                            hook: "From X to Y in N weeks — what actually moved the needle.",                      format: "text-post",  platforms: ["linkedin", "twitter"] },
  { title: "Quick poll: which of these is your biggest blocker?",      hook: "Reply A, B, or C — I'll write a deep-dive on the most-voted answer.",           format: "text-post",  platforms: ["threads", "twitter", "linkedin"] },
  { title: "Comment-bait carousel (controversial take)",               hook: "Most agencies are doing X wrong. Here's what should replace it.",               format: "carousel",   platforms: ["instagram", "linkedin"] },
  { title: "60-second teardown of a competitor",                       hook: "What this brand nailed and where they left money on the table.",                format: "short-form-video", platforms: ["tiktok", "instagram"] },
  { title: "Free template / cheat sheet drop",                         hook: "Comment the keyword and I'll DM the file.",                                     format: "single-image", platforms: ["instagram", "linkedin"] },
];

export async function GET(request: NextRequest) {
  const supabase = createServerSupabase();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // Rate limit AI usage.
  const { data: profile } = await supabase
    .from("profiles")
    .select("plan_tier")
    .eq("id", user.id)
    .single();
  const limited = checkAiRateLimit(user.id, profile?.plan_tier);
  if (limited) return limited;

  const niche = (new URL(request.url).searchParams.get("niche") ?? "digital marketing agency").slice(0, 200);

  let ideas: ContentIdea[] = DEFAULT_IDEAS;
  let nicheHashtags: Partial<Record<SocialPlatform, string[]>> = {};

  try {
    const response = await callLLM({
      taskType: "generation_short",
      systemPrompt: SYSTEM_PROMPT,
      userPrompt: `Niche: ${niche}`,
      maxTokens: 2200,
      userId: user.id,
      context: "/api/social/trends",
    });
    const parsed = safeJsonParse<ClaudeTrendsResponse>(response.text);
    if (parsed) {
      if (Array.isArray(parsed.ideas) && parsed.ideas.length > 0) {
        ideas = parsed.ideas
          .filter((i) => i && typeof i.title === "string")
          .slice(0, 10)
          .map((i) => ({
            title: String(i.title).slice(0, 140),
            hook: String(i.hook ?? "").slice(0, 240),
            format: String(i.format ?? "single-image"),
            platforms: Array.isArray(i.platforms)
              ? (i.platforms.filter((p) => ALL_PLATFORMS.includes(p as SocialPlatform)) as SocialPlatform[])
              : [],
          }));
      }
      if (parsed.niche_hashtags) nicheHashtags = parsed.niche_hashtags;
    }
  } catch (err) {
    console.error("[social-studio/trends] claude error", err);
    // Fall through to defaults.
  }

  const merged = mergeHashtags(FALLBACK_HASHTAGS, nicheHashtags);

  const out: TrendsResponse = {
    hashtags_by_platform: merged,
    ideas,
    niche,
  };

  return NextResponse.json(out);
}
