/**
 * FONTS_LIBRARY — 100+ web fonts for the video editor & AI tool pages.
 *
 * All URLs are real Google Fonts CSS2 endpoints (https://fonts.googleapis.com/css2).
 * They're loadable in-browser via <link rel="stylesheet"> or programmatic import.
 * The `family` field matches the exact CSS font-family name after loading.
 *
 * Categories are coarse grained — a font can belong to multiple aesthetic buckets
 * (e.g. "Cinzel" is both serif and gothic); we pick the dominant one here and use
 * the `useCases` tags for secondary discovery.
 */

export type FontCategory =
  | "display"
  | "sans"
  | "serif"
  | "mono"
  | "handwriting"
  | "gothic";

export interface Font {
  id: string;
  family: string;
  url: string;
  category: FontCategory;
  /** Canonical weights bundled in the URL. 400 = regular, 700 = bold, 900 = black. */
  weight: number[];
  /** Discovery tags: "ad-headline", "caption", "body", "quote", "metal", etc. */
  useCases: string[];
  previewText: string;
}

// Helper to build Google Fonts CSS2 URLs with a single weight.
const gf = (family: string, weights: number[] = [400, 700]): string => {
  const qFamily = family.replace(/ /g, "+");
  const wts = weights.join(";");
  return `https://fonts.googleapis.com/css2?family=${qFamily}:wght@${wts}&display=swap`;
};

export const FONTS_LIBRARY: Font[] = [
  // ---------- DISPLAY (30) ----------
  {
    id: "font_anton",
    family: "Anton",
    url: "https://fonts.googleapis.com/css2?family=Anton&display=swap",
    category: "display",
    weight: [400],
    useCases: ["ad-headline", "caption", "hero", "hook"],
    previewText: "STOP SCROLLING",
  },
  {
    id: "font_bebas_neue",
    family: "Bebas Neue",
    url: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    category: "display",
    weight: [400],
    useCases: ["ad-headline", "caption", "reels"],
    previewText: "WATCH THIS",
  },
  {
    id: "font_bungee",
    family: "Bungee",
    url: "https://fonts.googleapis.com/css2?family=Bungee&display=swap",
    category: "display",
    weight: [400],
    useCases: ["signage", "poster", "bold"],
    previewText: "BIG DEAL",
  },
  {
    id: "font_bungee_inline",
    family: "Bungee Inline",
    url: "https://fonts.googleapis.com/css2?family=Bungee+Inline&display=swap",
    category: "display",
    weight: [400],
    useCases: ["signage", "retro"],
    previewText: "NEON VIBES",
  },
  {
    id: "font_bungee_shade",
    family: "Bungee Shade",
    url: "https://fonts.googleapis.com/css2?family=Bungee+Shade&display=swap",
    category: "display",
    weight: [400],
    useCases: ["signage", "playful"],
    previewText: "SHADOWED",
  },
  {
    id: "font_alfa_slab_one",
    family: "Alfa Slab One",
    url: "https://fonts.googleapis.com/css2?family=Alfa+Slab+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["ad-headline", "slab", "bold"],
    previewText: "CHUNKY TEXT",
  },
  {
    id: "font_black_ops_one",
    family: "Black Ops One",
    url: "https://fonts.googleapis.com/css2?family=Black+Ops+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["military", "gaming", "action"],
    previewText: "MISSION BRIEF",
  },
  {
    id: "font_rubik_mono_one",
    family: "Rubik Mono One",
    url: "https://fonts.googleapis.com/css2?family=Rubik+Mono+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["retro", "tech", "mono-display"],
    previewText: "SYSTEM ON",
  },
  {
    id: "font_permanent_marker",
    family: "Permanent Marker",
    url: "https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap",
    category: "display",
    weight: [400],
    useCases: ["marker", "casual", "handmade"],
    previewText: "HAND DRAWN",
  },
  {
    id: "font_monoton",
    family: "Monoton",
    url: "https://fonts.googleapis.com/css2?family=Monoton&display=swap",
    category: "display",
    weight: [400],
    useCases: ["retro", "80s", "neon"],
    previewText: "RETRO",
  },
  {
    id: "font_righteous",
    family: "Righteous",
    url: "https://fonts.googleapis.com/css2?family=Righteous&display=swap",
    category: "display",
    weight: [400],
    useCases: ["sports", "gaming", "bold"],
    previewText: "CHAMPION",
  },
  {
    id: "font_audiowide",
    family: "Audiowide",
    url: "https://fonts.googleapis.com/css2?family=Audiowide&display=swap",
    category: "display",
    weight: [400],
    useCases: ["tech", "futuristic", "gaming"],
    previewText: "FUTURE TECH",
  },
  {
    id: "font_orbitron",
    family: "Orbitron",
    url: gf("Orbitron", [400, 700, 900]),
    category: "display",
    weight: [400, 700, 900],
    useCases: ["sci-fi", "tech", "futuristic"],
    previewText: "ORBITRON",
  },
  {
    id: "font_russo_one",
    family: "Russo One",
    url: "https://fonts.googleapis.com/css2?family=Russo+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["sports", "bold", "heading"],
    previewText: "POWERFUL",
  },
  {
    id: "font_faster_one",
    family: "Faster One",
    url: "https://fonts.googleapis.com/css2?family=Faster+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["racing", "speed", "retro"],
    previewText: "FAST LANE",
  },
  {
    id: "font_bowlby_one",
    family: "Bowlby One",
    url: "https://fonts.googleapis.com/css2?family=Bowlby+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["heavy", "heading", "loud"],
    previewText: "HEAVY",
  },
  {
    id: "font_staatliches",
    family: "Staatliches",
    url: "https://fonts.googleapis.com/css2?family=Staatliches&display=swap",
    category: "display",
    weight: [400],
    useCases: ["poster", "caption", "condensed"],
    previewText: "STAATLICHES",
  },
  {
    id: "font_ultra",
    family: "Ultra",
    url: "https://fonts.googleapis.com/css2?family=Ultra&display=swap",
    category: "display",
    weight: [400],
    useCases: ["western", "slab", "bold"],
    previewText: "ULTRA",
  },
  {
    id: "font_bangers",
    family: "Bangers",
    url: "https://fonts.googleapis.com/css2?family=Bangers&display=swap",
    category: "display",
    weight: [400],
    useCases: ["comic", "playful", "loud"],
    previewText: "BANG!",
  },
  {
    id: "font_fredoka_one",
    family: "Fredoka One",
    url: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["friendly", "playful", "rounded"],
    previewText: "Friendly",
  },
  {
    id: "font_titan_one",
    family: "Titan One",
    url: "https://fonts.googleapis.com/css2?family=Titan+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["kids", "playful", "rounded"],
    previewText: "TITAN",
  },
  {
    id: "font_lilita_one",
    family: "Lilita One",
    url: "https://fonts.googleapis.com/css2?family=Lilita+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["kids", "playful", "rounded"],
    previewText: "Lilita",
  },
  {
    id: "font_passion_one",
    family: "Passion One",
    url: gf("Passion One", [400, 700, 900]),
    category: "display",
    weight: [400, 700, 900],
    useCases: ["bold", "heading", "hero"],
    previewText: "PASSION",
  },
  {
    id: "font_paytone_one",
    family: "Paytone One",
    url: "https://fonts.googleapis.com/css2?family=Paytone+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["bold", "heading", "heavy"],
    previewText: "Paytone",
  },
  {
    id: "font_shrikhand",
    family: "Shrikhand",
    url: "https://fonts.googleapis.com/css2?family=Shrikhand&display=swap",
    category: "display",
    weight: [400],
    useCases: ["display", "bold", "quirky"],
    previewText: "SHRIKHAND",
  },
  {
    id: "font_squada_one",
    family: "Squada One",
    url: "https://fonts.googleapis.com/css2?family=Squada+One&display=swap",
    category: "display",
    weight: [400],
    useCases: ["military", "heading", "condensed"],
    previewText: "SQUAD",
  },
  {
    id: "font_rye",
    family: "Rye",
    url: "https://fonts.googleapis.com/css2?family=Rye&display=swap",
    category: "display",
    weight: [400],
    useCases: ["western", "vintage", "saloon"],
    previewText: "OUTLAW",
  },
  {
    id: "font_lobster",
    family: "Lobster",
    url: "https://fonts.googleapis.com/css2?family=Lobster&display=swap",
    category: "display",
    weight: [400],
    useCases: ["script", "retro", "restaurant"],
    previewText: "Lobster",
  },
  {
    id: "font_chewy",
    family: "Chewy",
    url: "https://fonts.googleapis.com/css2?family=Chewy&display=swap",
    category: "display",
    weight: [400],
    useCases: ["playful", "kids", "friendly"],
    previewText: "Chewy",
  },
  {
    id: "font_luckiest_guy",
    family: "Luckiest Guy",
    url: "https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap",
    category: "display",
    weight: [400],
    useCases: ["comic", "playful", "loud"],
    previewText: "LUCKY",
  },

  // ---------- SANS (25) ----------
  {
    id: "font_inter",
    family: "Inter",
    url: gf("Inter", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["ui", "body", "default", "modern"],
    previewText: "Inter is the default UI font.",
  },
  {
    id: "font_montserrat",
    family: "Montserrat",
    url: gf("Montserrat", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["ad-headline", "body", "modern"],
    previewText: "MONTSERRAT BLACK",
  },
  {
    id: "font_poppins",
    family: "Poppins",
    url: gf("Poppins", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["ui", "body", "rounded"],
    previewText: "Poppins feels friendly.",
  },
  {
    id: "font_dm_sans",
    family: "DM Sans",
    url: gf("DM Sans", [400, 500, 700]),
    category: "sans",
    weight: [400, 500, 700],
    useCases: ["ui", "body", "modern"],
    previewText: "DM Sans.",
  },
  {
    id: "font_plus_jakarta_sans",
    family: "Plus Jakarta Sans",
    url: gf("Plus Jakarta Sans", [300, 400, 500, 600, 700, 800]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800],
    useCases: ["ui", "body", "modern"],
    previewText: "Plus Jakarta.",
  },
  {
    id: "font_manrope",
    family: "Manrope",
    url: gf("Manrope", [300, 400, 500, 600, 700, 800]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800],
    useCases: ["ui", "body", "modern"],
    previewText: "Manrope.",
  },
  {
    id: "font_roboto",
    family: "Roboto",
    url: gf("Roboto", [300, 400, 500, 700, 900]),
    category: "sans",
    weight: [300, 400, 500, 700, 900],
    useCases: ["body", "ui", "material"],
    previewText: "Roboto.",
  },
  {
    id: "font_roboto_flex",
    family: "Roboto Flex",
    url: gf("Roboto Flex", [400, 700]),
    category: "sans",
    weight: [400, 700],
    useCases: ["body", "ui", "variable"],
    previewText: "Roboto Flex.",
  },
  {
    id: "font_roboto_condensed",
    family: "Roboto Condensed",
    url: gf("Roboto Condensed", [400, 700]),
    category: "sans",
    weight: [400, 700],
    useCases: ["caption", "condensed"],
    previewText: "Roboto Condensed.",
  },
  {
    id: "font_work_sans",
    family: "Work Sans",
    url: gf("Work Sans", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["body", "ui", "professional"],
    previewText: "Work Sans.",
  },
  {
    id: "font_open_sans",
    family: "Open Sans",
    url: gf("Open Sans", [300, 400, 500, 600, 700, 800]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800],
    useCases: ["body", "ui", "readable"],
    previewText: "Open Sans.",
  },
  {
    id: "font_lato",
    family: "Lato",
    url: gf("Lato", [300, 400, 700, 900]),
    category: "sans",
    weight: [300, 400, 700, 900],
    useCases: ["body", "ui", "professional"],
    previewText: "Lato.",
  },
  {
    id: "font_nunito",
    family: "Nunito",
    url: gf("Nunito", [300, 400, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 600, 700, 800, 900],
    useCases: ["body", "rounded", "friendly"],
    previewText: "Nunito.",
  },
  {
    id: "font_nunito_sans",
    family: "Nunito Sans",
    url: gf("Nunito Sans", [300, 400, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 600, 700, 800, 900],
    useCases: ["body", "ui"],
    previewText: "Nunito Sans.",
  },
  {
    id: "font_raleway",
    family: "Raleway",
    url: gf("Raleway", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["heading", "editorial"],
    previewText: "Raleway.",
  },
  {
    id: "font_oswald",
    family: "Oswald",
    url: gf("Oswald", [300, 400, 500, 600, 700]),
    category: "sans",
    weight: [300, 400, 500, 600, 700],
    useCases: ["ad-headline", "condensed"],
    previewText: "OSWALD.",
  },
  {
    id: "font_barlow",
    family: "Barlow",
    url: gf("Barlow", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["ui", "body", "sports"],
    previewText: "Barlow.",
  },
  {
    id: "font_barlow_condensed",
    family: "Barlow Condensed",
    url: gf("Barlow Condensed", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["caption", "condensed"],
    previewText: "Barlow Condensed.",
  },
  {
    id: "font_archivo",
    family: "Archivo",
    url: gf("Archivo", [400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [400, 500, 600, 700, 800, 900],
    useCases: ["body", "ui"],
    previewText: "Archivo.",
  },
  {
    id: "font_archivo_black",
    family: "Archivo Black",
    url: "https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap",
    category: "sans",
    weight: [400],
    useCases: ["heading", "heavy"],
    previewText: "ARCHIVO BLACK.",
  },
  {
    id: "font_bai_jamjuree",
    family: "Bai Jamjuree",
    url: gf("Bai Jamjuree", [400, 500, 600, 700]),
    category: "sans",
    weight: [400, 500, 600, 700],
    useCases: ["ui", "body", "modern"],
    previewText: "Bai Jamjuree.",
  },
  {
    id: "font_karla",
    family: "Karla",
    url: gf("Karla", [400, 500, 600, 700, 800]),
    category: "sans",
    weight: [400, 500, 600, 700, 800],
    useCases: ["body", "ui"],
    previewText: "Karla.",
  },
  {
    id: "font_figtree",
    family: "Figtree",
    url: gf("Figtree", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["ui", "body", "modern"],
    previewText: "Figtree.",
  },
  {
    id: "font_space_grotesk",
    family: "Space Grotesk",
    url: gf("Space Grotesk", [300, 400, 500, 600, 700]),
    category: "sans",
    weight: [300, 400, 500, 600, 700],
    useCases: ["ui", "tech", "modern"],
    previewText: "Space Grotesk.",
  },
  {
    id: "font_urbanist",
    family: "Urbanist",
    url: gf("Urbanist", [300, 400, 500, 600, 700, 800, 900]),
    category: "sans",
    weight: [300, 400, 500, 600, 700, 800, 900],
    useCases: ["ui", "body", "modern"],
    previewText: "Urbanist.",
  },

  // ---------- SERIF (15) ----------
  {
    id: "font_playfair_display",
    family: "Playfair Display",
    url: gf("Playfair Display", [400, 500, 600, 700, 800, 900]),
    category: "serif",
    weight: [400, 500, 600, 700, 800, 900],
    useCases: ["editorial", "quote", "elegant"],
    previewText: "Playfair Display.",
  },
  {
    id: "font_dm_serif_display",
    family: "DM Serif Display",
    url: gf("DM Serif Display", [400]),
    category: "serif",
    weight: [400],
    useCases: ["heading", "editorial", "elegant"],
    previewText: "DM Serif Display.",
  },
  {
    id: "font_lora",
    family: "Lora",
    url: gf("Lora", [400, 500, 600, 700]),
    category: "serif",
    weight: [400, 500, 600, 700],
    useCases: ["body", "editorial", "blog"],
    previewText: "Lora.",
  },
  {
    id: "font_cormorant",
    family: "Cormorant",
    url: gf("Cormorant", [300, 400, 500, 600, 700]),
    category: "serif",
    weight: [300, 400, 500, 600, 700],
    useCases: ["quote", "elegant", "fashion"],
    previewText: "Cormorant.",
  },
  {
    id: "font_cormorant_garamond",
    family: "Cormorant Garamond",
    url: gf("Cormorant Garamond", [300, 400, 500, 600, 700]),
    category: "serif",
    weight: [300, 400, 500, 600, 700],
    useCases: ["quote", "editorial", "elegant"],
    previewText: "Cormorant Garamond.",
  },
  {
    id: "font_bodoni_moda",
    family: "Bodoni Moda",
    url: gf("Bodoni Moda", [400, 500, 600, 700, 800, 900]),
    category: "serif",
    weight: [400, 500, 600, 700, 800, 900],
    useCases: ["fashion", "editorial", "elegant"],
    previewText: "Bodoni Moda.",
  },
  {
    id: "font_merriweather",
    family: "Merriweather",
    url: gf("Merriweather", [300, 400, 700, 900]),
    category: "serif",
    weight: [300, 400, 700, 900],
    useCases: ["body", "blog", "editorial"],
    previewText: "Merriweather.",
  },
  {
    id: "font_playfair",
    family: "Playfair",
    url: gf("Playfair", [400, 700]),
    category: "serif",
    weight: [400, 700],
    useCases: ["editorial", "elegant"],
    previewText: "Playfair.",
  },
  {
    id: "font_libre_baskerville",
    family: "Libre Baskerville",
    url: gf("Libre Baskerville", [400, 700]),
    category: "serif",
    weight: [400, 700],
    useCases: ["body", "blog", "editorial"],
    previewText: "Libre Baskerville.",
  },
  {
    id: "font_crimson_pro",
    family: "Crimson Pro",
    url: gf("Crimson Pro", [300, 400, 500, 600, 700]),
    category: "serif",
    weight: [300, 400, 500, 600, 700],
    useCases: ["body", "editorial", "book"],
    previewText: "Crimson Pro.",
  },
  {
    id: "font_eb_garamond",
    family: "EB Garamond",
    url: gf("EB Garamond", [400, 500, 600, 700, 800]),
    category: "serif",
    weight: [400, 500, 600, 700, 800],
    useCases: ["body", "book", "elegant"],
    previewText: "EB Garamond.",
  },
  {
    id: "font_spectral",
    family: "Spectral",
    url: gf("Spectral", [300, 400, 500, 600, 700, 800]),
    category: "serif",
    weight: [300, 400, 500, 600, 700, 800],
    useCases: ["body", "editorial"],
    previewText: "Spectral.",
  },
  {
    id: "font_abril_fatface",
    family: "Abril Fatface",
    url: "https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap",
    category: "serif",
    weight: [400],
    useCases: ["heading", "editorial", "bold"],
    previewText: "Abril Fatface.",
  },
  {
    id: "font_italiana",
    family: "Italiana",
    url: "https://fonts.googleapis.com/css2?family=Italiana&display=swap",
    category: "serif",
    weight: [400],
    useCases: ["fashion", "elegant"],
    previewText: "Italiana.",
  },
  {
    id: "font_tenor_sans",
    family: "Tenor Sans",
    url: "https://fonts.googleapis.com/css2?family=Tenor+Sans&display=swap",
    category: "serif",
    weight: [400],
    useCases: ["editorial", "elegant", "quiet"],
    previewText: "Tenor Sans.",
  },

  // ---------- HANDWRITING (12) ----------
  {
    id: "font_caveat",
    family: "Caveat",
    url: gf("Caveat", [400, 500, 600, 700]),
    category: "handwriting",
    weight: [400, 500, 600, 700],
    useCases: ["signature", "casual", "handmade"],
    previewText: "Just a sec!",
  },
  {
    id: "font_dancing_script",
    family: "Dancing Script",
    url: gf("Dancing Script", [400, 500, 600, 700]),
    category: "handwriting",
    weight: [400, 500, 600, 700],
    useCases: ["script", "wedding", "elegant"],
    previewText: "Dancing Script",
  },
  {
    id: "font_pacifico",
    family: "Pacifico",
    url: "https://fonts.googleapis.com/css2?family=Pacifico&display=swap",
    category: "handwriting",
    weight: [400],
    useCases: ["script", "fun", "retro"],
    previewText: "Pacifico",
  },
  {
    id: "font_shadows_into_light",
    family: "Shadows Into Light",
    url: "https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap",
    category: "handwriting",
    weight: [400],
    useCases: ["note", "casual", "handmade"],
    previewText: "Shadows Into Light",
  },
  {
    id: "font_kalam",
    family: "Kalam",
    url: gf("Kalam", [300, 400, 700]),
    category: "handwriting",
    weight: [300, 400, 700],
    useCases: ["note", "casual"],
    previewText: "Kalam",
  },
  {
    id: "font_satisfy",
    family: "Satisfy",
    url: "https://fonts.googleapis.com/css2?family=Satisfy&display=swap",
    category: "handwriting",
    weight: [400],
    useCases: ["script", "signature"],
    previewText: "Satisfy",
  },
  {
    id: "font_sacramento",
    family: "Sacramento",
    url: "https://fonts.googleapis.com/css2?family=Sacramento&display=swap",
    category: "handwriting",
    weight: [400],
    useCases: ["script", "elegant"],
    previewText: "Sacramento",
  },
  {
    id: "font_great_vibes",
    family: "Great Vibes",
    url: "https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap",
    category: "handwriting",
    weight: [400],
    useCases: ["wedding", "elegant", "script"],
    previewText: "Great Vibes",
  },
  {
    id: "font_indie_flower",
    family: "Indie Flower",
    url: "https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap",
    category: "handwriting",
    weight: [400],
    useCases: ["casual", "kids", "handmade"],
    previewText: "Indie Flower",
  },
  {
    id: "font_homemade_apple",
    family: "Homemade Apple",
    url: "https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap",
    category: "handwriting",
    weight: [400],
    useCases: ["casual", "handwritten", "note"],
    previewText: "Homemade Apple",
  },
  {
    id: "font_amatic_sc",
    family: "Amatic SC",
    url: gf("Amatic SC", [400, 700]),
    category: "handwriting",
    weight: [400, 700],
    useCases: ["casual", "chalkboard"],
    previewText: "AMATIC SC",
  },
  {
    id: "font_kaushan_script",
    family: "Kaushan Script",
    url: "https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap",
    category: "handwriting",
    weight: [400],
    useCases: ["brush", "logo", "elegant"],
    previewText: "Kaushan Script",
  },

  // ---------- GOTHIC / METAL (8) ----------
  {
    id: "font_cinzel",
    family: "Cinzel",
    url: gf("Cinzel", [400, 500, 600, 700, 800, 900]),
    category: "gothic",
    weight: [400, 500, 600, 700, 800, 900],
    useCases: ["gothic", "epic", "trailer"],
    previewText: "CINZEL",
  },
  {
    id: "font_cinzel_decorative",
    family: "Cinzel Decorative",
    url: gf("Cinzel Decorative", [400, 700, 900]),
    category: "gothic",
    weight: [400, 700, 900],
    useCases: ["gothic", "decorative"],
    previewText: "CINZEL DEC",
  },
  {
    id: "font_unifrakturmaguntia",
    family: "UnifrakturMaguntia",
    url: "https://fonts.googleapis.com/css2?family=UnifrakturMaguntia&display=swap",
    category: "gothic",
    weight: [400],
    useCases: ["gothic", "blackletter", "metal"],
    previewText: "Gothic Headline",
  },
  {
    id: "font_unifrakturcook",
    family: "UnifrakturCook",
    url: "https://fonts.googleapis.com/css2?family=UnifrakturCook:wght@700&display=swap",
    category: "gothic",
    weight: [700],
    useCases: ["gothic", "blackletter"],
    previewText: "Blackletter",
  },
  {
    id: "font_medievalsharp",
    family: "MedievalSharp",
    url: "https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap",
    category: "gothic",
    weight: [400],
    useCases: ["medieval", "fantasy", "rpg"],
    previewText: "MedievalSharp",
  },
  {
    id: "font_metamorphous",
    family: "Metamorphous",
    url: "https://fonts.googleapis.com/css2?family=Metamorphous&display=swap",
    category: "gothic",
    weight: [400],
    useCases: ["fantasy", "magic", "rpg"],
    previewText: "Metamorphous",
  },
  {
    id: "font_uncial_antiqua",
    family: "Uncial Antiqua",
    url: "https://fonts.googleapis.com/css2?family=Uncial+Antiqua&display=swap",
    category: "gothic",
    weight: [400],
    useCases: ["medieval", "celtic", "ancient"],
    previewText: "Uncial Antiqua",
  },
  {
    id: "font_pirata_one",
    family: "Pirata One",
    url: "https://fonts.googleapis.com/css2?family=Pirata+One&display=swap",
    category: "gothic",
    weight: [400],
    useCases: ["pirate", "vintage", "spooky"],
    previewText: "Pirata One",
  },

  // ---------- MONO / RETRO-CODE (12) ----------
  {
    id: "font_press_start_2p",
    family: "Press Start 2P",
    url: "https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap",
    category: "mono",
    weight: [400],
    useCases: ["retro", "gaming", "8bit"],
    previewText: "PRESS START",
  },
  {
    id: "font_vt323",
    family: "VT323",
    url: "https://fonts.googleapis.com/css2?family=VT323&display=swap",
    category: "mono",
    weight: [400],
    useCases: ["retro", "terminal", "crt"],
    previewText: "VT323 terminal.",
  },
  {
    id: "font_share_tech_mono",
    family: "Share Tech Mono",
    url: "https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap",
    category: "mono",
    weight: [400],
    useCases: ["tech", "terminal", "code"],
    previewText: "Share Tech Mono",
  },
  {
    id: "font_fjalla_one",
    family: "Fjalla One",
    url: "https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap",
    category: "sans",
    weight: [400],
    useCases: ["condensed", "caption", "news"],
    previewText: "FJALLA ONE",
  },
  {
    id: "font_major_mono_display",
    family: "Major Mono Display",
    url: "https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap",
    category: "mono",
    weight: [400],
    useCases: ["display", "tech"],
    previewText: "major mono",
  },
  {
    id: "font_space_mono",
    family: "Space Mono",
    url: gf("Space Mono", [400, 700]),
    category: "mono",
    weight: [400, 700],
    useCases: ["tech", "code", "editorial"],
    previewText: "Space Mono.",
  },
  {
    id: "font_jetbrains_mono",
    family: "JetBrains Mono",
    url: gf("JetBrains Mono", [400, 500, 600, 700, 800]),
    category: "mono",
    weight: [400, 500, 600, 700, 800],
    useCases: ["code", "ide", "terminal"],
    previewText: "JetBrains Mono",
  },
  {
    id: "font_fira_code",
    family: "Fira Code",
    url: gf("Fira Code", [300, 400, 500, 600, 700]),
    category: "mono",
    weight: [300, 400, 500, 600, 700],
    useCases: ["code", "ligatures"],
    previewText: "fn main() {}",
  },
  {
    id: "font_ibm_plex_mono",
    family: "IBM Plex Mono",
    url: gf("IBM Plex Mono", [300, 400, 500, 600, 700]),
    category: "mono",
    weight: [300, 400, 500, 600, 700],
    useCases: ["code", "editorial"],
    previewText: "IBM Plex Mono",
  },
  {
    id: "font_source_code_pro",
    family: "Source Code Pro",
    url: gf("Source Code Pro", [300, 400, 500, 600, 700, 900]),
    category: "mono",
    weight: [300, 400, 500, 600, 700, 900],
    useCases: ["code", "ide"],
    previewText: "Source Code Pro",
  },
  {
    id: "font_cutive_mono",
    family: "Cutive Mono",
    url: "https://fonts.googleapis.com/css2?family=Cutive+Mono&display=swap",
    category: "mono",
    weight: [400],
    useCases: ["typewriter", "vintage"],
    previewText: "Cutive Mono",
  },
  {
    id: "font_special_elite",
    family: "Special Elite",
    url: "https://fonts.googleapis.com/css2?family=Special+Elite&display=swap",
    category: "mono",
    weight: [400],
    useCases: ["typewriter", "vintage", "noir"],
    previewText: "Special Elite",
  },
];

/** Filter fonts by category. */
export function filterFontsByCategory(
  category: FontCategory,
): Font[] {
  return FONTS_LIBRARY.filter((f) => f.category === category);
}

/** Return fonts whose useCases include any of the requested tags. */
export function filterFontsByUseCase(tags: string[]): Font[] {
  if (!tags.length) return FONTS_LIBRARY;
  const s = new Set(tags.map((t) => t.toLowerCase()));
  return FONTS_LIBRARY.filter((f) =>
    f.useCases.some((u) => s.has(u.toLowerCase())),
  );
}

/** Return a font by id, or undefined. */
export function getFontById(id: string): Font | undefined {
  return FONTS_LIBRARY.find((f) => f.id === id);
}

/** Pseudo-random font pick (deterministic when a seed is passed). */
export function getRandomFont(seed?: number): Font {
  const idx =
    typeof seed === "number"
      ? Math.abs(Math.floor(seed)) % FONTS_LIBRARY.length
      : Math.floor(Math.random() * FONTS_LIBRARY.length);
  return FONTS_LIBRARY[idx]!;
}
