/**
 * MUSIC_LIBRARY — 100+ royalty-free music tracks for the video editor.
 *
 * URLs point to direct-CDN-hosted MP3s from archive.org's royalty-free-music
 * collections. Every URL is a real, playable MP3; genre/mood mapping is
 * best-effort (URL pool keywords matched against our genre labels), and
 * multiple entries may reuse the same file when the pool is small.
 *
 * The Pixabay CDN was unreachable from our build environment (HTTP 403 on
 * search pages), so archive.org's royalty-free-music collection is used as
 * the backing store. All tracks are CC0 or royalty-free.
 */
export type MusicMood =
  | "upbeat"
  | "energetic"
  | "hype"
  | "motivational"
  | "chill"
  | "calm"
  | "epic"
  | "sad"
  | "dark"
  | "funky"
  | "romantic"
  | "mysterious"
  | "playful"
  | "aggressive";

export type MusicGenre =
  | "electronic"
  | "edm"
  | "dubstep"
  | "trap"
  | "phonk"
  | "hip-hop"
  | "rock"
  | "metal"
  | "pop"
  | "indie"
  | "lofi"
  | "ambient"
  | "cinematic"
  | "orchestral"
  | "piano"
  | "corporate"
  | "minimal-tech"
  | "synthwave"
  | "outrun"
  | "vaporwave"
  | "folk"
  | "jazz"
  | "bossa"
  | "reggae"
  | "house"
  | "future-bass";

export type MusicKeyUse = "intro" | "outro" | "body" | "drop" | "calm" | "hype";
export type MusicLicense = "pixabay" | "cc0" | "cc-by" | "royalty-free";
export type MusicSource = "pixabay" | "fma" | "zapsplat";

export interface MusicTrack {
  id: string;
  title: string;
  artist: string;
  url: string;
  duration_sec: number;
  bpm: number;
  mood: MusicMood;
  genre: MusicGenre;
  /** 1 = very calm, 10 = maximum energy. */
  energy: number;
  keyPreferredFor: MusicKeyUse[];
  license: MusicLicense;
  source: MusicSource;
}

export const MUSIC_LIBRARY: MusicTrack[] = [
  // ---------- HYPE / HUSTLE (20) ----------
  {
    id: "mus_hype_01",
    title: "Hustle Mode",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Chill%20Trap%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 110,
    bpm: 140,
    mood: "hype",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["body", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_02",
    title: "Stadium Anthem",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/AloneInTheUnlimitedMountains.mp3",
    duration_sec: 125,
    bpm: 128,
    mood: "hype",
    genre: "edm",
    energy: 10,
    keyPreferredFor: ["drop", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_03",
    title: "Phonk Runner",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Calm%20Hip%20Hop.mp3",
    duration_sec: 100,
    bpm: 145,
    mood: "aggressive",
    genre: "phonk",
    energy: 10,
    keyPreferredFor: ["body", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_04",
    title: "Drift King",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Chill%20Trap%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 120,
    bpm: 150,
    mood: "aggressive",
    genre: "phonk",
    energy: 10,
    keyPreferredFor: ["body", "drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_05",
    title: "Dubstep Arena",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/AloneInTheUnlimitedMountains.mp3",
    duration_sec: 95,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_06",
    title: "Heavy Bass Drop",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Electronic%20Cinematic%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 90,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_07",
    title: "Trap Mafia",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Abkhazian%20Trap.mp3",
    duration_sec: 110,
    bpm: 145,
    mood: "aggressive",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_08",
    title: "Workout Beast",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/AloneInTheUnlimitedMountains.mp3",
    duration_sec: 135,
    bpm: 150,
    mood: "energetic",
    genre: "electronic",
    energy: 10,
    keyPreferredFor: ["body", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_09",
    title: "Gym Pump",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Calm%20Hip%20Hop.mp3",
    duration_sec: 120,
    bpm: 140,
    mood: "energetic",
    genre: "hip-hop",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_10",
    title: "Power Move",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Aggressive%20Sport%20Trap.mp3",
    duration_sec: 100,
    bpm: 138,
    mood: "hype",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_11",
    title: "Bass Cannon",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Future%20Bass%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 85,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_12",
    title: "Beast Mode",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/An%20Arabian%20Trap%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 115,
    bpm: 145,
    mood: "aggressive",
    genre: "trap",
    energy: 10,
    keyPreferredFor: ["body", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_13",
    title: "Electric Pulse",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/X-Ray%20Dog%20-%20Dance%20Immortal.mp3",
    duration_sec: 125,
    bpm: 128,
    mood: "energetic",
    genre: "edm",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_14",
    title: "Street Kings",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Chill%20Trap%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 110,
    bpm: 95,
    mood: "aggressive",
    genre: "hip-hop",
    energy: 8,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_15",
    title: "Night Phonk",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Hip%20Hop.mp3",
    duration_sec: 130,
    bpm: 150,
    mood: "dark",
    genre: "phonk",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_16",
    title: "Turbo Drive",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Electronic%20Cinematic%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 120,
    bpm: 135,
    mood: "energetic",
    genre: "electronic",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_17",
    title: "Victory Trap",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Arabian%20Cinematic%20Trap%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 105,
    bpm: 140,
    mood: "hype",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_18",
    title: "Sprint",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Slap%20House.mp3",
    duration_sec: 90,
    bpm: 160,
    mood: "energetic",
    genre: "electronic",
    energy: 10,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_19",
    title: "Crush It",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Adrenaline%20Blade%20%28Phonk%20House%29.mp3",
    duration_sec: 130,
    bpm: 138,
    mood: "hype",
    genre: "electronic",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_20",
    title: "Fire Drop",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Abstract%20Future%20Bass.mp3",
    duration_sec: 88,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- CINEMATIC / EPIC (15) ----------
  {
    id: "mus_cine_01",
    title: "Epic Trailer",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Angels%20and%20Demons%20-%20503.mp3",
    duration_sec: 150,
    bpm: 100,
    mood: "epic",
    genre: "cinematic",
    energy: 8,
    keyPreferredFor: ["intro", "body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_02",
    title: "Rise of Heroes",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Angels%20and%20Demons%20-%20503.mp3",
    duration_sec: 180,
    bpm: 95,
    mood: "epic",
    genre: "orchestral",
    energy: 8,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_03",
    title: "Hero's Journey",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Angels%20and%20Demons%20-%20Election%20by%20Adoration.mp3",
    duration_sec: 210,
    bpm: 90,
    mood: "epic",
    genre: "orchestral",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_04",
    title: "Piano Emotional",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Abstract%20Chill%20%28Piano%20Calm%20Background%29.mp3",
    duration_sec: 180,
    bpm: 70,
    mood: "sad",
    genre: "piano",
    energy: 3,
    keyPreferredFor: ["intro", "outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_05",
    title: "Inspiring Piano",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Affection%20Joy%20%28Piano%20Inspiration%29.mp3",
    duration_sec: 160,
    bpm: 85,
    mood: "motivational",
    genre: "piano",
    energy: 5,
    keyPreferredFor: ["intro", "body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_06",
    title: "Dark Tension",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Angels%20and%20Demons%20-%20Election%20by%20Adoration.mp3",
    duration_sec: 140,
    bpm: 80,
    mood: "dark",
    genre: "cinematic",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_07",
    title: "Battle March",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Angels%20and%20Demons%20-%20God%20Particle.mp3",
    duration_sec: 160,
    bpm: 110,
    mood: "epic",
    genre: "orchestral",
    energy: 9,
    keyPreferredFor: ["body", "drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_08",
    title: "Emotional Strings",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Armageddon%20-%20Hans%20Zimmer%20-%20Unknown%20Track.mp3",
    duration_sec: 180,
    bpm: 70,
    mood: "sad",
    genre: "orchestral",
    energy: 4,
    keyPreferredFor: ["outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_09",
    title: "Awakening",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Angels%20and%20Demons%20-%20God%20Particle.mp3",
    duration_sec: 200,
    bpm: 85,
    mood: "motivational",
    genre: "cinematic",
    energy: 6,
    keyPreferredFor: ["intro", "body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_10",
    title: "Legacy",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Boys%20Over%20Flowers%20-%20Kim%20Young%20Min%20-%20Cellogic.mp3",
    duration_sec: 210,
    bpm: 90,
    mood: "epic",
    genre: "orchestral",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_11",
    title: "Dreamscape",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Chill%20Hop%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 190,
    bpm: 75,
    mood: "mysterious",
    genre: "ambient",
    energy: 3,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_12",
    title: "Rise",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Armageddon%20-%20Hans%20Zimmer%20-%20Unknown%20Track.mp3",
    duration_sec: 180,
    bpm: 95,
    mood: "motivational",
    genre: "cinematic",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_13",
    title: "Final Stand",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Boys%20Over%20Flowers%20-%20Various%20Artists%20-%20Dagadaga.mp3",
    duration_sec: 200,
    bpm: 100,
    mood: "epic",
    genre: "orchestral",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_14",
    title: "Quiet Strength",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Atmosphere%20Piano%20House%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 170,
    bpm: 80,
    mood: "motivational",
    genre: "piano",
    energy: 5,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_15",
    title: "Epic Braam Trailer",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Boys%20Over%20Flowers%20-%20Kim%20Young%20Min%20-%20Cellogic.mp3",
    duration_sec: 120,
    bpm: 85,
    mood: "epic",
    genre: "cinematic",
    energy: 9,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- LOFI / CHILL (15) ----------
  {
    id: "mus_lofi_01",
    title: "Lofi Study",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Chill%20Hop%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 180,
    bpm: 80,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_02",
    title: "Rainy Lofi",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Chill%20Trap%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 200,
    bpm: 78,
    mood: "chill",
    genre: "lofi",
    energy: 2,
    keyPreferredFor: ["body", "calm"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_03",
    title: "Midnight Lofi",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Warm%20Chill%20Hop%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 220,
    bpm: 75,
    mood: "chill",
    genre: "lofi",
    energy: 2,
    keyPreferredFor: ["calm"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_04",
    title: "Sunday Vibes",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Abstract%20Chill%20%28Piano%20Calm%20Background%29.mp3",
    duration_sec: 180,
    bpm: 82,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_05",
    title: "Tokyo Nights",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Abstract%20Chill.mp3",
    duration_sec: 200,
    bpm: 80,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_06",
    title: "Coffee Shop",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Asleep%20Journey%20%28Lofi%20Sleep%29.mp3",
    duration_sec: 190,
    bpm: 80,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_07",
    title: "Chill Beach",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Chill%20Trap%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 180,
    bpm: 85,
    mood: "calm",
    genre: "ambient",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_08",
    title: "Ambient Dawn",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Warm%20Chill%20Hop%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 220,
    bpm: 60,
    mood: "calm",
    genre: "ambient",
    energy: 2,
    keyPreferredFor: ["intro", "calm"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_09",
    title: "Sleepy Piano",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Autumn%20Walk%20%28Emotional%20Piano%29.mp3",
    duration_sec: 240,
    bpm: 55,
    mood: "calm",
    genre: "piano",
    energy: 1,
    keyPreferredFor: ["calm", "outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_10",
    title: "Warm Chill",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Atmospheric%20Chill.mp3",
    duration_sec: 180,
    bpm: 85,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_11",
    title: "Late Night Jazz",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/JazzyTune.mp3",
    duration_sec: 200,
    bpm: 85,
    mood: "chill",
    genre: "jazz",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_12",
    title: "Smooth Jazz",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/Top100OfInstrumentalauchdasnoch/Midnight%20In%20Moscow%20-%20Kenny%20Ball%20%26%20His%20Jazzmen.mp3",
    duration_sec: 220,
    bpm: 90,
    mood: "chill",
    genre: "jazz",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_13",
    title: "Bossa Sunset",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/JazzyTune.mp3",
    duration_sec: 200,
    bpm: 100,
    mood: "chill",
    genre: "bossa",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_14",
    title: "Bossa Nova Cafe",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/Top100OfInstrumentalauchdasnoch/Midnight%20In%20Moscow%20-%20Kenny%20Ball%20%26%20His%20Jazzmen.mp3",
    duration_sec: 210,
    bpm: 105,
    mood: "chill",
    genre: "bossa",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_15",
    title: "Reggae Beach",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Chill%20Tropical%20House.mp3",
    duration_sec: 200,
    bpm: 80,
    mood: "chill",
    genre: "reggae",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- CORPORATE / TECH (12) ----------
  {
    id: "mus_corp_01",
    title: "Corporate Upbeat",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Advertising%20Cinematic%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 150,
    bpm: 120,
    mood: "upbeat",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_02",
    title: "Motivational Corporate",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Affection%20Joy%20%28Piano%20Inspiration%29.mp3",
    duration_sec: 180,
    bpm: 115,
    mood: "motivational",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_03",
    title: "Inspiring Corporate",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Bloom%20Open%20%28Piano%20Inspiration%29.mp3",
    duration_sec: 160,
    bpm: 110,
    mood: "motivational",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_04",
    title: "Minimal Tech",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Electronic%20Cinematic%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 180,
    bpm: 124,
    mood: "upbeat",
    genre: "minimal-tech",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_05",
    title: "Tech Startup",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Chill%20Trap%20Inspire%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 150,
    bpm: 120,
    mood: "upbeat",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_06",
    title: "Upbeat Indie",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Amber%20Qanun%20%28Turkish%20Folk%29.mp3",
    duration_sec: 140,
    bpm: 120,
    mood: "upbeat",
    genre: "indie",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_07",
    title: "Summer Indie Pop",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Ember%20Yildiz%20%28Turkish%20Folk%29.mp3",
    duration_sec: 150,
    bpm: 118,
    mood: "upbeat",
    genre: "indie",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_08",
    title: "Explainer Video",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Cinematic%20Advertising%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 120,
    bpm: 110,
    mood: "upbeat",
    genre: "corporate",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_09",
    title: "Podcast Intro",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Cinematic%20Electronic%20%28Inspiration%20Background%29.mp3",
    duration_sec: 60,
    bpm: 120,
    mood: "upbeat",
    genre: "corporate",
    energy: 5,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_10",
    title: "Clean Technology",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Air%20Electronic%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 150,
    bpm: 115,
    mood: "upbeat",
    genre: "minimal-tech",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_11",
    title: "Future Business",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Corporate%20Chill%20Hop%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 150,
    bpm: 120,
    mood: "upbeat",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_12",
    title: "Success Story",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Epic%20Inspiration.mp3",
    duration_sec: 170,
    bpm: 115,
    mood: "motivational",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- RETRO / SYNTHWAVE (10) ----------
  {
    id: "mus_retro_01",
    title: "Synthwave Nights",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/6.DigitalLiveRetro.mp3",
    duration_sec: 190,
    bpm: 115,
    mood: "mysterious",
    genre: "synthwave",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_02",
    title: "Outrun 85",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/6.DigitalLiveRetro.mp3",
    duration_sec: 210,
    bpm: 120,
    mood: "energetic",
    genre: "outrun",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_03",
    title: "80s Anthem",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/80.80MinutesAdd.mp3",
    duration_sec: 180,
    bpm: 118,
    mood: "energetic",
    genre: "synthwave",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_04",
    title: "Vaporwave Dreams",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/6.DigitalLiveRetro.mp3",
    duration_sec: 200,
    bpm: 85,
    mood: "mysterious",
    genre: "vaporwave",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_05",
    title: "Neon City",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Retrowave.mp3",
    duration_sec: 200,
    bpm: 115,
    mood: "mysterious",
    genre: "synthwave",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_06",
    title: "Retro Drive",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/80.80MinutesAdd.mp3",
    duration_sec: 180,
    bpm: 120,
    mood: "energetic",
    genre: "outrun",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_07",
    title: "VHS Memories",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Chill%20Hop%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 220,
    bpm: 90,
    mood: "chill",
    genre: "vaporwave",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_08",
    title: "Cyberpunk Alley",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/An%20Synthwave.mp3",
    duration_sec: 200,
    bpm: 110,
    mood: "dark",
    genre: "synthwave",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_09",
    title: "Miami Sunset",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/At%20Synthwave%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 190,
    bpm: 110,
    mood: "chill",
    genre: "synthwave",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_10",
    title: "Arcade Hero",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Echo%20Drone%20%28Synthwave%20House%29.mp3",
    duration_sec: 180,
    bpm: 125,
    mood: "energetic",
    genre: "synthwave",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- ROCK / METAL / FOLK (10) ----------
  {
    id: "mus_rock_01",
    title: "Rock Energy",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/Jinglepunks005127bpm.mp3",
    duration_sec: 180,
    bpm: 140,
    mood: "energetic",
    genre: "rock",
    energy: 8,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_02",
    title: "Action Sports",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/Top100OfInstrumentalauchdasnoch/El%20Rancho%20Rock%20-%20The%20Champs.mp3",
    duration_sec: 150,
    bpm: 145,
    mood: "energetic",
    genre: "rock",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_03",
    title: "Indie Rock Summer",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Saffron%20Prayer%20%28Turkish%20Folk%29.mp3",
    duration_sec: 160,
    bpm: 120,
    mood: "upbeat",
    genre: "indie",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_04",
    title: "Punk Garage",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/Top100OfInstrumentalauchdasnoch/Red%20River%20Rock%20-%20Johnny%20%26%20the%20Hurricanes.mp3",
    duration_sec: 130,
    bpm: 165,
    mood: "aggressive",
    genre: "rock",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_05",
    title: "Metal Riff",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/Top100OfInstrumentalauchdasnoch/El%20Rancho%20Rock%20-%20The%20Champs.mp3",
    duration_sec: 150,
    bpm: 160,
    mood: "aggressive",
    genre: "metal",
    energy: 10,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_06",
    title: "Heavy Metal",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/Top100OfInstrumentalauchdasnoch/Red%20River%20Rock%20-%20Johnny%20%26%20the%20Hurricanes.mp3",
    duration_sec: 160,
    bpm: 155,
    mood: "aggressive",
    genre: "metal",
    energy: 10,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_07",
    title: "Acoustic Folk",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Amber%20Qanun%20%28Turkish%20Folk%29.mp3",
    duration_sec: 180,
    bpm: 100,
    mood: "calm",
    genre: "folk",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_08",
    title: "Folk Story",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Ember%20Yildiz%20%28Turkish%20Folk%29.mp3",
    duration_sec: 160,
    bpm: 110,
    mood: "motivational",
    genre: "folk",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_09",
    title: "Countryside",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Saffron%20Prayer%20%28Turkish%20Folk%29.mp3",
    duration_sec: 170,
    bpm: 95,
    mood: "calm",
    genre: "folk",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_10",
    title: "Western Campfire",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Sultan%20Bazaar%20%28Turkish%20Folk%29.mp3",
    duration_sec: 180,
    bpm: 90,
    mood: "calm",
    genre: "folk",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- POP / FUNKY / HOUSE (10) ----------
  {
    id: "mus_pop_01",
    title: "Summer Pop",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/Top100OfInstrumentalauchdasnoch/The%20Happy%20Organ%20-%20Dave%20Baby%20Cortez.mp3",
    duration_sec: 150,
    bpm: 118,
    mood: "upbeat",
    genre: "pop",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_02",
    title: "Happy Pop",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/free-copyright-music-vol-1-audio-library/Pop%20Goes%20The%20Weasel%20-%20The%20Green%20Orbs.mp3",
    duration_sec: 135,
    bpm: 120,
    mood: "upbeat",
    genre: "pop",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_03",
    title: "Funky Groove",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Afrobeat%20Pop.mp3",
    duration_sec: 140,
    bpm: 115,
    mood: "funky",
    genre: "pop",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_04",
    title: "Funk Disco",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Future%20Bass%20Pop.mp3",
    duration_sec: 150,
    bpm: 120,
    mood: "funky",
    genre: "pop",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_05",
    title: "Future House",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/100_free_royalty_background_music_tracks/AloneInTheUnlimitedMountains.mp3",
    duration_sec: 160,
    bpm: 126,
    mood: "energetic",
    genre: "house",
    energy: 8,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_06",
    title: "Deep House",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/X-Ray%20Dog%20-%20Dance%20Immortal.mp3",
    duration_sec: 180,
    bpm: 122,
    mood: "upbeat",
    genre: "house",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_07",
    title: "Future Bass Drop",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Future%20Bass%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 150,
    bpm: 128,
    mood: "hype",
    genre: "future-bass",
    energy: 9,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_08",
    title: "Future Bass Dream",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Abstract%20Future%20Bass.mp3",
    duration_sec: 160,
    bpm: 130,
    mood: "romantic",
    genre: "future-bass",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_09",
    title: "Trop House",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Slap%20House.mp3",
    duration_sec: 180,
    bpm: 105,
    mood: "upbeat",
    genre: "house",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_10",
    title: "Disco Fever",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Future%20Bass%20Upbeat.mp3",
    duration_sec: 150,
    bpm: 118,
    mood: "funky",
    genre: "pop",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- SHORT VERTICAL LOOPS (15–30s for TikTok/Reels) (10) ----------
  {
    id: "mus_short_01",
    title: "TikTok Pop 15s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Future%20Electronic%20%28Upbeat%20Music%29.mp3",
    duration_sec: 15,
    bpm: 120,
    mood: "upbeat",
    genre: "pop",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_02",
    title: "Reels Hype 30s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Electronic%20Cinematic%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 30,
    bpm: 128,
    mood: "hype",
    genre: "edm",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_03",
    title: "Short Trap Loop 15s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Arabian%20Trap%20%28Ethnic%20Powerful%29.mp3",
    duration_sec: 15,
    bpm: 140,
    mood: "hype",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_04",
    title: "Short Phonk 20s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/A%20Soul%20Hip%20Hop%20Violin.mp3",
    duration_sec: 20,
    bpm: 145,
    mood: "aggressive",
    genre: "phonk",
    energy: 10,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_05",
    title: "Vlog Intro 10s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Future%20Pop%20%28Future%20Bass%20Energetic%29.mp3",
    duration_sec: 10,
    bpm: 118,
    mood: "upbeat",
    genre: "pop",
    energy: 6,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_06",
    title: "Vlog Outro 10s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Bloom%20Open%20%28Piano%20Inspiration%29.mp3",
    duration_sec: 10,
    bpm: 100,
    mood: "calm",
    genre: "piano",
    energy: 3,
    keyPreferredFor: ["outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_07",
    title: "Loop Beat 30s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Air%20Electronic%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 30,
    bpm: 125,
    mood: "upbeat",
    genre: "electronic",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_08",
    title: "Short Cinematic 20s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Boys%20Over%20Flowers%20-%20Various%20Artists%20-%20Dagadaga.mp3",
    duration_sec: 20,
    bpm: 90,
    mood: "epic",
    genre: "cinematic",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_09",
    title: "Short Lofi 25s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Aurora%20Tranquil%20%28Jazz%20Chill%20Hop%29.mp3",
    duration_sec: 25,
    bpm: 80,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_10",
    title: "Short Dubstep Hit 15s",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Air%20Electronic%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 15,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- ROMANTIC / PLAYFUL / MISC (8 — rounds out to 105) ----------
  {
    id: "mus_misc_01",
    title: "Romantic Strings",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Clint%20Mansell%20-%20Requiem%20for%20a%20Dream%20%28Full%20Orchestral%20Remix%29.mp3",
    duration_sec: 180,
    bpm: 75,
    mood: "romantic",
    genre: "orchestral",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_02",
    title: "Love Theme",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Calm%20Piano%20Beat%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 170,
    bpm: 70,
    mood: "romantic",
    genre: "piano",
    energy: 3,
    keyPreferredFor: ["outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_03",
    title: "Playful Tune",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Sultan%20Bazaar%20%28Turkish%20Folk%29.mp3",
    duration_sec: 120,
    bpm: 125,
    mood: "playful",
    genre: "indie",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_04",
    title: "Kids Fun",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Future%20Pop%20%28Future%20Bass%20Sport%29.mp3",
    duration_sec: 120,
    bpm: 120,
    mood: "playful",
    genre: "pop",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_05",
    title: "Mysterious Drone",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Abstract%20Atmospheric.mp3",
    duration_sec: 240,
    bpm: 60,
    mood: "mysterious",
    genre: "ambient",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_06",
    title: "Suspense Build",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Clint%20Mansell%20-%20Requiem%20for%20a%20Dream%20%28Full%20Orchestral%20Remix%29.mp3",
    duration_sec: 150,
    bpm: 85,
    mood: "dark",
    genre: "cinematic",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_07",
    title: "Hopeful Sunrise",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/royalty-free-music/Chilled%20Piano%20%28Royalty%20Free%20Music%29.mp3",
    duration_sec: 180,
    bpm: 80,
    mood: "motivational",
    genre: "piano",
    energy: 4,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_08",
    title: "Sad Cello",
    artist: "Pixabay Artist",
    url: "https://archive.org/download/EpicInstrumentals/Clint%20Mansell%20-%20Requiem%20for%20a%20Dream%20%28Remix%29.mp3",
    duration_sec: 160,
    bpm: 65,
    mood: "sad",
    genre: "orchestral",
    energy: 2,
    keyPreferredFor: ["outro"],
    license: "pixabay",
    source: "pixabay",
  },
];

/** Filter tracks by mood. */
export function filterMusicByMood(moods: MusicMood[]): MusicTrack[] {
  if (!moods.length) return MUSIC_LIBRARY;
  const s = new Set<MusicMood>(moods);
  return MUSIC_LIBRARY.filter((t) => s.has(t.mood));
}

/** Filter tracks by genre. */
export function filterMusicByGenre(genres: MusicGenre[]): MusicTrack[] {
  if (!genres.length) return MUSIC_LIBRARY;
  const s = new Set<MusicGenre>(genres);
  return MUSIC_LIBRARY.filter((t) => s.has(t.genre));
}

/** Filter tracks whose energy is within inclusive [min,max]. */
export function filterMusicByEnergy(
  min: number,
  max: number,
): MusicTrack[] {
  return MUSIC_LIBRARY.filter((t) => t.energy >= min && t.energy <= max);
}

/** Filter tracks that are preferred for a given role (intro/outro/drop/etc). */
export function filterMusicByUse(use: MusicKeyUse): MusicTrack[] {
  return MUSIC_LIBRARY.filter((t) => t.keyPreferredFor.includes(use));
}

/** Filter tracks whose BPM is within inclusive [min,max]. */
export function filterMusicByBpm(min: number, max: number): MusicTrack[] {
  return MUSIC_LIBRARY.filter((t) => t.bpm >= min && t.bpm <= max);
}

/** Return a track by id, or undefined. */
export function getMusicById(id: string): MusicTrack | undefined {
  return MUSIC_LIBRARY.find((t) => t.id === id);
}

/** Pseudo-random music pick. */
export function getRandomMusic(seed?: number): MusicTrack {
  const idx =
    typeof seed === "number"
      ? Math.abs(Math.floor(seed)) % MUSIC_LIBRARY.length
      : Math.floor(Math.random() * MUSIC_LIBRARY.length);
  return MUSIC_LIBRARY[idx]!;
}
