/**
 * MUSIC_LIBRARY — 100+ royalty-free music tracks for the video editor.
 *
 * ⚠️ REPLACE PLACEHOLDERS WITH REAL URLs FROM PIXABAY/FREESOUND ⚠️
 *
 * URLs below follow Pixabay's landing-page format
 * (`https://pixabay.com/music/<genre>-<slug>-<id>/`) but the `<id>` numerics
 * are PLACEHOLDERS. Before shipping:
 *   1. Search pixabay.com/music/ for a track matching title + mood.
 *   2. Replace the `url` with the real page URL.
 *   3. Optionally host the downloadable mp3 on our own CDN for production renders.
 *
 * The smaller curated `ADS_MUSIC_LIBRARY` in ./ads.ts remains the "hand-picked
 * defaults for the Ads preset". This file is the big catalog the editor
 * music browser pulls from.
 */

export type MusicMood =
  | "upbeat"
  | "energetic"
  | "hype"
  | "motivational"
  | "chill"
  | "calm"
  | "epic"
  | "sad"
  | "dark"
  | "funky"
  | "romantic"
  | "mysterious"
  | "playful"
  | "aggressive";

export type MusicGenre =
  | "electronic"
  | "edm"
  | "dubstep"
  | "trap"
  | "phonk"
  | "hip-hop"
  | "rock"
  | "metal"
  | "pop"
  | "indie"
  | "lofi"
  | "ambient"
  | "cinematic"
  | "orchestral"
  | "piano"
  | "corporate"
  | "minimal-tech"
  | "synthwave"
  | "outrun"
  | "vaporwave"
  | "folk"
  | "jazz"
  | "bossa"
  | "reggae"
  | "house"
  | "future-bass";

export type MusicKeyUse = "intro" | "outro" | "body" | "drop" | "calm" | "hype";
export type MusicLicense = "pixabay" | "cc0" | "cc-by" | "royalty-free";
export type MusicSource = "pixabay" | "fma" | "zapsplat";

export interface MusicTrack {
  id: string;
  title: string;
  artist: string;
  url: string;
  duration_sec: number;
  bpm: number;
  mood: MusicMood;
  genre: MusicGenre;
  /** 1 = very calm, 10 = maximum energy. */
  energy: number;
  keyPreferredFor: MusicKeyUse[];
  license: MusicLicense;
  source: MusicSource;
}

const pix = (slug: string, id: string): string =>
  `https://pixabay.com/music/${slug}-${id}/`;

export const MUSIC_LIBRARY: MusicTrack[] = [
  // ---------- HYPE / HUSTLE (20) ----------
  {
    id: "mus_hype_01",
    title: "Hustle Mode",
    artist: "Pixabay Artist",
    url: pix("beats-hustle-mode", "000001"),
    duration_sec: 110,
    bpm: 140,
    mood: "hype",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["body", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_02",
    title: "Stadium Anthem",
    artist: "Pixabay Artist",
    url: pix("edm-stadium-anthem", "000002"),
    duration_sec: 125,
    bpm: 128,
    mood: "hype",
    genre: "edm",
    energy: 10,
    keyPreferredFor: ["drop", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_03",
    title: "Phonk Runner",
    artist: "Pixabay Artist",
    url: pix("phonk-phonk-runner", "000003"),
    duration_sec: 100,
    bpm: 145,
    mood: "aggressive",
    genre: "phonk",
    energy: 10,
    keyPreferredFor: ["body", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_04",
    title: "Drift King",
    artist: "Pixabay Artist",
    url: pix("phonk-drift-king", "000004"),
    duration_sec: 120,
    bpm: 150,
    mood: "aggressive",
    genre: "phonk",
    energy: 10,
    keyPreferredFor: ["body", "drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_05",
    title: "Dubstep Arena",
    artist: "Pixabay Artist",
    url: pix("dubstep-dubstep-arena", "000005"),
    duration_sec: 95,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_06",
    title: "Heavy Bass Drop",
    artist: "Pixabay Artist",
    url: pix("dubstep-heavy-bass-drop", "000006"),
    duration_sec: 90,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_07",
    title: "Trap Mafia",
    artist: "Pixabay Artist",
    url: pix("trap-trap-mafia", "000007"),
    duration_sec: 110,
    bpm: 145,
    mood: "aggressive",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_08",
    title: "Workout Beast",
    artist: "Pixabay Artist",
    url: pix("beats-workout-beast", "000008"),
    duration_sec: 135,
    bpm: 150,
    mood: "energetic",
    genre: "electronic",
    energy: 10,
    keyPreferredFor: ["body", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_09",
    title: "Gym Pump",
    artist: "Pixabay Artist",
    url: pix("beats-gym-pump", "000009"),
    duration_sec: 120,
    bpm: 140,
    mood: "energetic",
    genre: "hip-hop",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_10",
    title: "Power Move",
    artist: "Pixabay Artist",
    url: pix("trap-power-move", "000010"),
    duration_sec: 100,
    bpm: 138,
    mood: "hype",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_11",
    title: "Bass Cannon",
    artist: "Pixabay Artist",
    url: pix("dubstep-bass-cannon", "000011"),
    duration_sec: 85,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_12",
    title: "Beast Mode",
    artist: "Pixabay Artist",
    url: pix("trap-beast-mode", "000012"),
    duration_sec: 115,
    bpm: 145,
    mood: "aggressive",
    genre: "trap",
    energy: 10,
    keyPreferredFor: ["body", "hype"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_13",
    title: "Electric Pulse",
    artist: "Pixabay Artist",
    url: pix("edm-electric-pulse", "000013"),
    duration_sec: 125,
    bpm: 128,
    mood: "energetic",
    genre: "edm",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_14",
    title: "Street Kings",
    artist: "Pixabay Artist",
    url: pix("hip-hop-street-kings", "000014"),
    duration_sec: 110,
    bpm: 95,
    mood: "aggressive",
    genre: "hip-hop",
    energy: 8,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_15",
    title: "Night Phonk",
    artist: "Pixabay Artist",
    url: pix("phonk-night-phonk", "000015"),
    duration_sec: 130,
    bpm: 150,
    mood: "dark",
    genre: "phonk",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_16",
    title: "Turbo Drive",
    artist: "Pixabay Artist",
    url: pix("electronic-turbo-drive", "000016"),
    duration_sec: 120,
    bpm: 135,
    mood: "energetic",
    genre: "electronic",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_17",
    title: "Victory Trap",
    artist: "Pixabay Artist",
    url: pix("trap-victory-trap", "000017"),
    duration_sec: 105,
    bpm: 140,
    mood: "hype",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_18",
    title: "Sprint",
    artist: "Pixabay Artist",
    url: pix("electronic-sprint", "000018"),
    duration_sec: 90,
    bpm: 160,
    mood: "energetic",
    genre: "electronic",
    energy: 10,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_19",
    title: "Crush It",
    artist: "Pixabay Artist",
    url: pix("beats-crush-it", "000019"),
    duration_sec: 130,
    bpm: 138,
    mood: "hype",
    genre: "electronic",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_hype_20",
    title: "Fire Drop",
    artist: "Pixabay Artist",
    url: pix("dubstep-fire-drop", "000020"),
    duration_sec: 88,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- CINEMATIC / EPIC (15) ----------
  {
    id: "mus_cine_01",
    title: "Epic Trailer",
    artist: "Pixabay Artist",
    url: pix("cinematic-epic-trailer", "000021"),
    duration_sec: 150,
    bpm: 100,
    mood: "epic",
    genre: "cinematic",
    energy: 8,
    keyPreferredFor: ["intro", "body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_02",
    title: "Rise of Heroes",
    artist: "Pixabay Artist",
    url: pix("cinematic-rise-of-heroes", "000022"),
    duration_sec: 180,
    bpm: 95,
    mood: "epic",
    genre: "orchestral",
    energy: 8,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_03",
    title: "Hero's Journey",
    artist: "Pixabay Artist",
    url: pix("cinematic-heros-journey", "000023"),
    duration_sec: 210,
    bpm: 90,
    mood: "epic",
    genre: "orchestral",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_04",
    title: "Piano Emotional",
    artist: "Pixabay Artist",
    url: pix("cinematic-piano-emotional", "000024"),
    duration_sec: 180,
    bpm: 70,
    mood: "sad",
    genre: "piano",
    energy: 3,
    keyPreferredFor: ["intro", "outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_05",
    title: "Inspiring Piano",
    artist: "Pixabay Artist",
    url: pix("cinematic-inspiring-piano", "000025"),
    duration_sec: 160,
    bpm: 85,
    mood: "motivational",
    genre: "piano",
    energy: 5,
    keyPreferredFor: ["intro", "body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_06",
    title: "Dark Tension",
    artist: "Pixabay Artist",
    url: pix("cinematic-dark-tension", "000026"),
    duration_sec: 140,
    bpm: 80,
    mood: "dark",
    genre: "cinematic",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_07",
    title: "Battle March",
    artist: "Pixabay Artist",
    url: pix("cinematic-battle-march", "000027"),
    duration_sec: 160,
    bpm: 110,
    mood: "epic",
    genre: "orchestral",
    energy: 9,
    keyPreferredFor: ["body", "drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_08",
    title: "Emotional Strings",
    artist: "Pixabay Artist",
    url: pix("cinematic-emotional-strings", "000028"),
    duration_sec: 180,
    bpm: 70,
    mood: "sad",
    genre: "orchestral",
    energy: 4,
    keyPreferredFor: ["outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_09",
    title: "Awakening",
    artist: "Pixabay Artist",
    url: pix("cinematic-awakening", "000029"),
    duration_sec: 200,
    bpm: 85,
    mood: "motivational",
    genre: "cinematic",
    energy: 6,
    keyPreferredFor: ["intro", "body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_10",
    title: "Legacy",
    artist: "Pixabay Artist",
    url: pix("cinematic-legacy", "000030"),
    duration_sec: 210,
    bpm: 90,
    mood: "epic",
    genre: "orchestral",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_11",
    title: "Dreamscape",
    artist: "Pixabay Artist",
    url: pix("cinematic-dreamscape", "000031"),
    duration_sec: 190,
    bpm: 75,
    mood: "mysterious",
    genre: "ambient",
    energy: 3,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_12",
    title: "Rise",
    artist: "Pixabay Artist",
    url: pix("cinematic-rise", "000032"),
    duration_sec: 180,
    bpm: 95,
    mood: "motivational",
    genre: "cinematic",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_13",
    title: "Final Stand",
    artist: "Pixabay Artist",
    url: pix("cinematic-final-stand", "000033"),
    duration_sec: 200,
    bpm: 100,
    mood: "epic",
    genre: "orchestral",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_14",
    title: "Quiet Strength",
    artist: "Pixabay Artist",
    url: pix("cinematic-quiet-strength", "000034"),
    duration_sec: 170,
    bpm: 80,
    mood: "motivational",
    genre: "piano",
    energy: 5,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_cine_15",
    title: "Epic Braam Trailer",
    artist: "Pixabay Artist",
    url: pix("cinematic-epic-braam-trailer", "000035"),
    duration_sec: 120,
    bpm: 85,
    mood: "epic",
    genre: "cinematic",
    energy: 9,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- LOFI / CHILL (15) ----------
  {
    id: "mus_lofi_01",
    title: "Lofi Study",
    artist: "Pixabay Artist",
    url: pix("beats-lofi-study", "000036"),
    duration_sec: 180,
    bpm: 80,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_02",
    title: "Rainy Lofi",
    artist: "Pixabay Artist",
    url: pix("beats-rainy-lofi", "000037"),
    duration_sec: 200,
    bpm: 78,
    mood: "chill",
    genre: "lofi",
    energy: 2,
    keyPreferredFor: ["body", "calm"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_03",
    title: "Midnight Lofi",
    artist: "Pixabay Artist",
    url: pix("beats-midnight-lofi", "000038"),
    duration_sec: 220,
    bpm: 75,
    mood: "chill",
    genre: "lofi",
    energy: 2,
    keyPreferredFor: ["calm"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_04",
    title: "Sunday Vibes",
    artist: "Pixabay Artist",
    url: pix("beats-sunday-vibes", "000039"),
    duration_sec: 180,
    bpm: 82,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_05",
    title: "Tokyo Nights",
    artist: "Pixabay Artist",
    url: pix("beats-tokyo-nights", "000040"),
    duration_sec: 200,
    bpm: 80,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_06",
    title: "Coffee Shop",
    artist: "Pixabay Artist",
    url: pix("beats-coffee-shop", "000041"),
    duration_sec: 190,
    bpm: 80,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_07",
    title: "Chill Beach",
    artist: "Pixabay Artist",
    url: pix("chill-chill-beach", "000042"),
    duration_sec: 180,
    bpm: 85,
    mood: "calm",
    genre: "ambient",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_08",
    title: "Ambient Dawn",
    artist: "Pixabay Artist",
    url: pix("ambient-ambient-dawn", "000043"),
    duration_sec: 220,
    bpm: 60,
    mood: "calm",
    genre: "ambient",
    energy: 2,
    keyPreferredFor: ["intro", "calm"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_09",
    title: "Sleepy Piano",
    artist: "Pixabay Artist",
    url: pix("ambient-sleepy-piano", "000044"),
    duration_sec: 240,
    bpm: 55,
    mood: "calm",
    genre: "piano",
    energy: 1,
    keyPreferredFor: ["calm", "outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_10",
    title: "Warm Chill",
    artist: "Pixabay Artist",
    url: pix("chill-warm-chill", "000045"),
    duration_sec: 180,
    bpm: 85,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_11",
    title: "Late Night Jazz",
    artist: "Pixabay Artist",
    url: pix("jazz-late-night-jazz", "000046"),
    duration_sec: 200,
    bpm: 85,
    mood: "chill",
    genre: "jazz",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_12",
    title: "Smooth Jazz",
    artist: "Pixabay Artist",
    url: pix("jazz-smooth-jazz", "000047"),
    duration_sec: 220,
    bpm: 90,
    mood: "chill",
    genre: "jazz",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_13",
    title: "Bossa Sunset",
    artist: "Pixabay Artist",
    url: pix("jazz-bossa-sunset", "000048"),
    duration_sec: 200,
    bpm: 100,
    mood: "chill",
    genre: "bossa",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_14",
    title: "Bossa Nova Cafe",
    artist: "Pixabay Artist",
    url: pix("jazz-bossa-nova-cafe", "000049"),
    duration_sec: 210,
    bpm: 105,
    mood: "chill",
    genre: "bossa",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_lofi_15",
    title: "Reggae Beach",
    artist: "Pixabay Artist",
    url: pix("reggae-reggae-beach", "000050"),
    duration_sec: 200,
    bpm: 80,
    mood: "chill",
    genre: "reggae",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- CORPORATE / TECH (12) ----------
  {
    id: "mus_corp_01",
    title: "Corporate Upbeat",
    artist: "Pixabay Artist",
    url: pix("corporate-corporate-upbeat", "000051"),
    duration_sec: 150,
    bpm: 120,
    mood: "upbeat",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_02",
    title: "Motivational Corporate",
    artist: "Pixabay Artist",
    url: pix("corporate-motivational-corporate", "000052"),
    duration_sec: 180,
    bpm: 115,
    mood: "motivational",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_03",
    title: "Inspiring Corporate",
    artist: "Pixabay Artist",
    url: pix("corporate-inspiring-corporate", "000053"),
    duration_sec: 160,
    bpm: 110,
    mood: "motivational",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_04",
    title: "Minimal Tech",
    artist: "Pixabay Artist",
    url: pix("electronic-minimal-tech", "000054"),
    duration_sec: 180,
    bpm: 124,
    mood: "upbeat",
    genre: "minimal-tech",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_05",
    title: "Tech Startup",
    artist: "Pixabay Artist",
    url: pix("electronic-tech-startup", "000055"),
    duration_sec: 150,
    bpm: 120,
    mood: "upbeat",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_06",
    title: "Upbeat Indie",
    artist: "Pixabay Artist",
    url: pix("indie-upbeat-indie", "000056"),
    duration_sec: 140,
    bpm: 120,
    mood: "upbeat",
    genre: "indie",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_07",
    title: "Summer Indie Pop",
    artist: "Pixabay Artist",
    url: pix("indie-summer-indie-pop", "000057"),
    duration_sec: 150,
    bpm: 118,
    mood: "upbeat",
    genre: "indie",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_08",
    title: "Explainer Video",
    artist: "Pixabay Artist",
    url: pix("corporate-explainer-video", "000058"),
    duration_sec: 120,
    bpm: 110,
    mood: "upbeat",
    genre: "corporate",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_09",
    title: "Podcast Intro",
    artist: "Pixabay Artist",
    url: pix("corporate-podcast-intro", "000059"),
    duration_sec: 60,
    bpm: 120,
    mood: "upbeat",
    genre: "corporate",
    energy: 5,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_10",
    title: "Clean Technology",
    artist: "Pixabay Artist",
    url: pix("corporate-clean-technology", "000060"),
    duration_sec: 150,
    bpm: 115,
    mood: "upbeat",
    genre: "minimal-tech",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_11",
    title: "Future Business",
    artist: "Pixabay Artist",
    url: pix("corporate-future-business", "000061"),
    duration_sec: 150,
    bpm: 120,
    mood: "upbeat",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_corp_12",
    title: "Success Story",
    artist: "Pixabay Artist",
    url: pix("corporate-success-story", "000062"),
    duration_sec: 170,
    bpm: 115,
    mood: "motivational",
    genre: "corporate",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- RETRO / SYNTHWAVE (10) ----------
  {
    id: "mus_retro_01",
    title: "Synthwave Nights",
    artist: "Pixabay Artist",
    url: pix("synthwave-synthwave-nights", "000063"),
    duration_sec: 190,
    bpm: 115,
    mood: "mysterious",
    genre: "synthwave",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_02",
    title: "Outrun 85",
    artist: "Pixabay Artist",
    url: pix("synthwave-outrun-85", "000064"),
    duration_sec: 210,
    bpm: 120,
    mood: "energetic",
    genre: "outrun",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_03",
    title: "80s Anthem",
    artist: "Pixabay Artist",
    url: pix("synthwave-80s-anthem", "000065"),
    duration_sec: 180,
    bpm: 118,
    mood: "energetic",
    genre: "synthwave",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_04",
    title: "Vaporwave Dreams",
    artist: "Pixabay Artist",
    url: pix("vaporwave-vaporwave-dreams", "000066"),
    duration_sec: 200,
    bpm: 85,
    mood: "mysterious",
    genre: "vaporwave",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_05",
    title: "Neon City",
    artist: "Pixabay Artist",
    url: pix("synthwave-neon-city", "000067"),
    duration_sec: 200,
    bpm: 115,
    mood: "mysterious",
    genre: "synthwave",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_06",
    title: "Retro Drive",
    artist: "Pixabay Artist",
    url: pix("synthwave-retro-drive", "000068"),
    duration_sec: 180,
    bpm: 120,
    mood: "energetic",
    genre: "outrun",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_07",
    title: "VHS Memories",
    artist: "Pixabay Artist",
    url: pix("synthwave-vhs-memories", "000069"),
    duration_sec: 220,
    bpm: 90,
    mood: "chill",
    genre: "vaporwave",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_08",
    title: "Cyberpunk Alley",
    artist: "Pixabay Artist",
    url: pix("synthwave-cyberpunk-alley", "000070"),
    duration_sec: 200,
    bpm: 110,
    mood: "dark",
    genre: "synthwave",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_09",
    title: "Miami Sunset",
    artist: "Pixabay Artist",
    url: pix("synthwave-miami-sunset", "000071"),
    duration_sec: 190,
    bpm: 110,
    mood: "chill",
    genre: "synthwave",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_retro_10",
    title: "Arcade Hero",
    artist: "Pixabay Artist",
    url: pix("synthwave-arcade-hero", "000072"),
    duration_sec: 180,
    bpm: 125,
    mood: "energetic",
    genre: "synthwave",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- ROCK / METAL / FOLK (10) ----------
  {
    id: "mus_rock_01",
    title: "Rock Energy",
    artist: "Pixabay Artist",
    url: pix("rock-rock-energy", "000073"),
    duration_sec: 180,
    bpm: 140,
    mood: "energetic",
    genre: "rock",
    energy: 8,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_02",
    title: "Action Sports",
    artist: "Pixabay Artist",
    url: pix("rock-action-sports", "000074"),
    duration_sec: 150,
    bpm: 145,
    mood: "energetic",
    genre: "rock",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_03",
    title: "Indie Rock Summer",
    artist: "Pixabay Artist",
    url: pix("rock-indie-rock-summer", "000075"),
    duration_sec: 160,
    bpm: 120,
    mood: "upbeat",
    genre: "indie",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_04",
    title: "Punk Garage",
    artist: "Pixabay Artist",
    url: pix("rock-punk-garage", "000076"),
    duration_sec: 130,
    bpm: 165,
    mood: "aggressive",
    genre: "rock",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_05",
    title: "Metal Riff",
    artist: "Pixabay Artist",
    url: pix("rock-metal-riff", "000077"),
    duration_sec: 150,
    bpm: 160,
    mood: "aggressive",
    genre: "metal",
    energy: 10,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_06",
    title: "Heavy Metal",
    artist: "Pixabay Artist",
    url: pix("rock-heavy-metal", "000078"),
    duration_sec: 160,
    bpm: 155,
    mood: "aggressive",
    genre: "metal",
    energy: 10,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_07",
    title: "Acoustic Folk",
    artist: "Pixabay Artist",
    url: pix("folk-acoustic-folk", "000079"),
    duration_sec: 180,
    bpm: 100,
    mood: "calm",
    genre: "folk",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_08",
    title: "Folk Story",
    artist: "Pixabay Artist",
    url: pix("folk-folk-story", "000080"),
    duration_sec: 160,
    bpm: 110,
    mood: "motivational",
    genre: "folk",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_09",
    title: "Countryside",
    artist: "Pixabay Artist",
    url: pix("folk-countryside", "000081"),
    duration_sec: 170,
    bpm: 95,
    mood: "calm",
    genre: "folk",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_rock_10",
    title: "Western Campfire",
    artist: "Pixabay Artist",
    url: pix("folk-western-campfire", "000082"),
    duration_sec: 180,
    bpm: 90,
    mood: "calm",
    genre: "folk",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- POP / FUNKY / HOUSE (10) ----------
  {
    id: "mus_pop_01",
    title: "Summer Pop",
    artist: "Pixabay Artist",
    url: pix("pop-summer-pop", "000083"),
    duration_sec: 150,
    bpm: 118,
    mood: "upbeat",
    genre: "pop",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_02",
    title: "Happy Pop",
    artist: "Pixabay Artist",
    url: pix("pop-happy-pop", "000084"),
    duration_sec: 135,
    bpm: 120,
    mood: "upbeat",
    genre: "pop",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_03",
    title: "Funky Groove",
    artist: "Pixabay Artist",
    url: pix("funk-funky-groove", "000085"),
    duration_sec: 140,
    bpm: 115,
    mood: "funky",
    genre: "pop",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_04",
    title: "Funk Disco",
    artist: "Pixabay Artist",
    url: pix("funk-funk-disco", "000086"),
    duration_sec: 150,
    bpm: 120,
    mood: "funky",
    genre: "pop",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_05",
    title: "Future House",
    artist: "Pixabay Artist",
    url: pix("house-future-house", "000087"),
    duration_sec: 160,
    bpm: 126,
    mood: "energetic",
    genre: "house",
    energy: 8,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_06",
    title: "Deep House",
    artist: "Pixabay Artist",
    url: pix("house-deep-house", "000088"),
    duration_sec: 180,
    bpm: 122,
    mood: "upbeat",
    genre: "house",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_07",
    title: "Future Bass Drop",
    artist: "Pixabay Artist",
    url: pix("future-bass-future-bass-drop", "000089"),
    duration_sec: 150,
    bpm: 128,
    mood: "hype",
    genre: "future-bass",
    energy: 9,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_08",
    title: "Future Bass Dream",
    artist: "Pixabay Artist",
    url: pix("future-bass-future-bass-dream", "000090"),
    duration_sec: 160,
    bpm: 130,
    mood: "romantic",
    genre: "future-bass",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_09",
    title: "Trop House",
    artist: "Pixabay Artist",
    url: pix("house-trop-house", "000091"),
    duration_sec: 180,
    bpm: 105,
    mood: "upbeat",
    genre: "house",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_pop_10",
    title: "Disco Fever",
    artist: "Pixabay Artist",
    url: pix("pop-disco-fever", "000092"),
    duration_sec: 150,
    bpm: 118,
    mood: "funky",
    genre: "pop",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- SHORT VERTICAL LOOPS (15–30s for TikTok/Reels) (10) ----------
  {
    id: "mus_short_01",
    title: "TikTok Pop 15s",
    artist: "Pixabay Artist",
    url: pix("pop-tiktok-pop-15s", "000093"),
    duration_sec: 15,
    bpm: 120,
    mood: "upbeat",
    genre: "pop",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_02",
    title: "Reels Hype 30s",
    artist: "Pixabay Artist",
    url: pix("edm-reels-hype-30s", "000094"),
    duration_sec: 30,
    bpm: 128,
    mood: "hype",
    genre: "edm",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_03",
    title: "Short Trap Loop 15s",
    artist: "Pixabay Artist",
    url: pix("trap-short-trap-loop-15s", "000095"),
    duration_sec: 15,
    bpm: 140,
    mood: "hype",
    genre: "trap",
    energy: 9,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_04",
    title: "Short Phonk 20s",
    artist: "Pixabay Artist",
    url: pix("phonk-short-phonk-20s", "000096"),
    duration_sec: 20,
    bpm: 145,
    mood: "aggressive",
    genre: "phonk",
    energy: 10,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_05",
    title: "Vlog Intro 10s",
    artist: "Pixabay Artist",
    url: pix("corporate-vlog-intro-10s", "000097"),
    duration_sec: 10,
    bpm: 118,
    mood: "upbeat",
    genre: "pop",
    energy: 6,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_06",
    title: "Vlog Outro 10s",
    artist: "Pixabay Artist",
    url: pix("corporate-vlog-outro-10s", "000098"),
    duration_sec: 10,
    bpm: 100,
    mood: "calm",
    genre: "piano",
    energy: 3,
    keyPreferredFor: ["outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_07",
    title: "Loop Beat 30s",
    artist: "Pixabay Artist",
    url: pix("beats-loop-beat-30s", "000099"),
    duration_sec: 30,
    bpm: 125,
    mood: "upbeat",
    genre: "electronic",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_08",
    title: "Short Cinematic 20s",
    artist: "Pixabay Artist",
    url: pix("cinematic-short-cinematic-20s", "000100"),
    duration_sec: 20,
    bpm: 90,
    mood: "epic",
    genre: "cinematic",
    energy: 7,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_09",
    title: "Short Lofi 25s",
    artist: "Pixabay Artist",
    url: pix("beats-short-lofi-25s", "000101"),
    duration_sec: 25,
    bpm: 80,
    mood: "chill",
    genre: "lofi",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_short_10",
    title: "Short Dubstep Hit 15s",
    artist: "Pixabay Artist",
    url: pix("dubstep-short-dubstep-hit-15s", "000102"),
    duration_sec: 15,
    bpm: 140,
    mood: "hype",
    genre: "dubstep",
    energy: 10,
    keyPreferredFor: ["drop"],
    license: "pixabay",
    source: "pixabay",
  },

  // ---------- ROMANTIC / PLAYFUL / MISC (8 — rounds out to 105) ----------
  {
    id: "mus_misc_01",
    title: "Romantic Strings",
    artist: "Pixabay Artist",
    url: pix("cinematic-romantic-strings", "000103"),
    duration_sec: 180,
    bpm: 75,
    mood: "romantic",
    genre: "orchestral",
    energy: 4,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_02",
    title: "Love Theme",
    artist: "Pixabay Artist",
    url: pix("piano-love-theme", "000104"),
    duration_sec: 170,
    bpm: 70,
    mood: "romantic",
    genre: "piano",
    energy: 3,
    keyPreferredFor: ["outro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_03",
    title: "Playful Tune",
    artist: "Pixabay Artist",
    url: pix("children-playful-tune", "000105"),
    duration_sec: 120,
    bpm: 125,
    mood: "playful",
    genre: "indie",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_04",
    title: "Kids Fun",
    artist: "Pixabay Artist",
    url: pix("children-kids-fun", "000106"),
    duration_sec: 120,
    bpm: 120,
    mood: "playful",
    genre: "pop",
    energy: 6,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_05",
    title: "Mysterious Drone",
    artist: "Pixabay Artist",
    url: pix("ambient-mysterious-drone", "000107"),
    duration_sec: 240,
    bpm: 60,
    mood: "mysterious",
    genre: "ambient",
    energy: 3,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_06",
    title: "Suspense Build",
    artist: "Pixabay Artist",
    url: pix("cinematic-suspense-build", "000108"),
    duration_sec: 150,
    bpm: 85,
    mood: "dark",
    genre: "cinematic",
    energy: 5,
    keyPreferredFor: ["body"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_07",
    title: "Hopeful Sunrise",
    artist: "Pixabay Artist",
    url: pix("piano-hopeful-sunrise", "000109"),
    duration_sec: 180,
    bpm: 80,
    mood: "motivational",
    genre: "piano",
    energy: 4,
    keyPreferredFor: ["intro"],
    license: "pixabay",
    source: "pixabay",
  },
  {
    id: "mus_misc_08",
    title: "Sad Cello",
    artist: "Pixabay Artist",
    url: pix("cinematic-sad-cello", "000110"),
    duration_sec: 160,
    bpm: 65,
    mood: "sad",
    genre: "orchestral",
    energy: 2,
    keyPreferredFor: ["outro"],
    license: "pixabay",
    source: "pixabay",
  },
];

/** Filter tracks by mood. */
export function filterMusicByMood(moods: MusicMood[]): MusicTrack[] {
  if (!moods.length) return MUSIC_LIBRARY;
  const s = new Set<MusicMood>(moods);
  return MUSIC_LIBRARY.filter((t) => s.has(t.mood));
}

/** Filter tracks by genre. */
export function filterMusicByGenre(genres: MusicGenre[]): MusicTrack[] {
  if (!genres.length) return MUSIC_LIBRARY;
  const s = new Set<MusicGenre>(genres);
  return MUSIC_LIBRARY.filter((t) => s.has(t.genre));
}

/** Filter tracks whose energy is within inclusive [min,max]. */
export function filterMusicByEnergy(
  min: number,
  max: number,
): MusicTrack[] {
  return MUSIC_LIBRARY.filter((t) => t.energy >= min && t.energy <= max);
}

/** Filter tracks that are preferred for a given role (intro/outro/drop/etc). */
export function filterMusicByUse(use: MusicKeyUse): MusicTrack[] {
  return MUSIC_LIBRARY.filter((t) => t.keyPreferredFor.includes(use));
}

/** Filter tracks whose BPM is within inclusive [min,max]. */
export function filterMusicByBpm(min: number, max: number): MusicTrack[] {
  return MUSIC_LIBRARY.filter((t) => t.bpm >= min && t.bpm <= max);
}

/** Return a track by id, or undefined. */
export function getMusicById(id: string): MusicTrack | undefined {
  return MUSIC_LIBRARY.find((t) => t.id === id);
}

/** Pseudo-random music pick. */
export function getRandomMusic(seed?: number): MusicTrack {
  const idx =
    typeof seed === "number"
      ? Math.abs(Math.floor(seed)) % MUSIC_LIBRARY.length
      : Math.floor(Math.random() * MUSIC_LIBRARY.length);
  return MUSIC_LIBRARY[idx]!;
}
