/**
 * SFX_LIBRARY — 100+ sound effects for the video editor.
 *
 * ⚠️ REPLACE PLACEHOLDERS WITH REAL URLs FROM PIXABAY/FREESOUND ⚠️
 *
 * The `url` field on every entry below is a plausibly-formed URL that matches
 * the real Pixabay CDN pattern (`https://cdn.pixabay.com/download/audio/YYYY/MM/dd/audio_<hash>.mp3`)
 * or Freesound download URL pattern but the hashes/slugs are PLACEHOLDERS.
 *
 * Before shipping to production a human must:
 *  1. Open each Pixabay page (e.g. https://pixabay.com/sound-effects/search/<tag>/)
 *     and copy the real CDN URL from the <audio> element's src.
 *  2. Paste it into the corresponding entry below.
 *  3. Verify the license noted here matches Pixabay's current terms.
 *
 * Licensing notes:
 *  - Pixabay content is "royalty-free" under the Pixabay Content License
 *    (free commercial use, no attribution required as of April 2024).
 *    See https://pixabay.com/service/license-summary/ for current terms.
 *  - Freesound entries may be CC0 or CC-BY — check the page per-entry.
 */

export type SfxCategory =
  | "impact"
  | "whoosh"
  | "pop"
  | "swoosh"
  | "hit"
  | "ui"
  | "ambient"
  | "comedy"
  | "cinematic"
  | "meme"
  | "riser";

export type SfxLicense = "CC0" | "free" | "royalty-free";
export type SfxSource = "pixabay" | "freesound" | "zapsplat";

export interface Sfx {
  id: string;
  name: string;
  category: SfxCategory;
  url: string;
  duration_ms: number;
  tags: string[];
  license: SfxLicense;
  source: SfxSource;
}

// Placeholder URL helper — keeps them looking real while flagged for replacement.
// Pattern matches Pixabay's actual CDN URL shape, but `hash` here is a deterministic
// hex that does NOT resolve to a real file until a human swaps in the real hash.
const p = (year: number, month: string, day: string, slug: string, hash: string): string =>
  `https://cdn.pixabay.com/download/audio/${year}/${month}/${day}/audio_${hash}-${slug}.mp3`;

export const SFX_LIBRARY: Sfx[] = [
  // ---------- WHOOSH (15) ----------
  {
    id: "sfx_whoosh_short_01",
    name: "Whoosh Short 1",
    category: "whoosh",
    url: p(2023, "05", "12", "whoosh-short-1", "a1b2c3d4e5"),
    duration_ms: 400,
    tags: ["whoosh", "transition", "short"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_short_02",
    name: "Whoosh Short 2",
    category: "whoosh",
    url: p(2023, "05", "12", "whoosh-short-2", "b2c3d4e5f6"),
    duration_ms: 380,
    tags: ["whoosh", "transition"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_long_01",
    name: "Whoosh Long",
    category: "whoosh",
    url: p(2023, "05", "12", "whoosh-long", "c3d4e5f6a7"),
    duration_ms: 1200,
    tags: ["whoosh", "long"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_swipe_01",
    name: "Whoosh Swipe",
    category: "whoosh",
    url: p(2023, "05", "12", "whoosh-swipe", "d4e5f6a7b8"),
    duration_ms: 300,
    tags: ["whoosh", "swipe"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_swipe_02",
    name: "Fast Swipe",
    category: "whoosh",
    url: p(2023, "05", "13", "fast-swipe", "e5f6a7b8c9"),
    duration_ms: 250,
    tags: ["swipe", "fast"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_whip",
    name: "Whip Whoosh",
    category: "whoosh",
    url: p(2023, "05", "13", "whip-whoosh", "f6a7b8c9d0"),
    duration_ms: 350,
    tags: ["whip", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_cinematic",
    name: "Cinematic Whoosh",
    category: "whoosh",
    url: p(2023, "06", "01", "cinematic-whoosh", "a7b8c9d0e1"),
    duration_ms: 1500,
    tags: ["cinematic", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_deep",
    name: "Deep Whoosh",
    category: "whoosh",
    url: p(2023, "06", "01", "deep-whoosh", "b8c9d0e1f2"),
    duration_ms: 900,
    tags: ["deep", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_wind",
    name: "Wind Whoosh",
    category: "whoosh",
    url: p(2023, "06", "01", "wind-whoosh", "c9d0e1f2a3"),
    duration_ms: 700,
    tags: ["wind", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_stinger",
    name: "Whoosh Stinger",
    category: "whoosh",
    url: p(2023, "06", "02", "whoosh-stinger", "d0e1f2a3b4"),
    duration_ms: 600,
    tags: ["stinger", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_transition_high",
    name: "High Whoosh Transition",
    category: "whoosh",
    url: p(2023, "06", "02", "high-whoosh", "e1f2a3b4c5"),
    duration_ms: 500,
    tags: ["transition", "whoosh", "high"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_transition_low",
    name: "Low Whoosh Transition",
    category: "whoosh",
    url: p(2023, "06", "02", "low-whoosh", "f2a3b4c5d6"),
    duration_ms: 500,
    tags: ["transition", "whoosh", "low"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_tail",
    name: "Whoosh Tail",
    category: "whoosh",
    url: p(2023, "06", "03", "whoosh-tail", "a3b4c5d6e7"),
    duration_ms: 700,
    tags: ["tail", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_sweep",
    name: "Sweep Whoosh",
    category: "whoosh",
    url: p(2023, "06", "03", "sweep-whoosh", "b4c5d6e7f8"),
    duration_ms: 900,
    tags: ["sweep", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_rush",
    name: "Rush Whoosh",
    category: "whoosh",
    url: p(2023, "06", "03", "rush-whoosh", "c5d6e7f8a9"),
    duration_ms: 600,
    tags: ["rush", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- IMPACT / HIT (16) ----------
  {
    id: "sfx_impact_boom",
    name: "Boom",
    category: "impact",
    url: p(2023, "07", "01", "boom", "a0a1a2a3a4"),
    duration_ms: 1500,
    tags: ["boom", "impact", "cinematic"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_thud",
    name: "Thud",
    category: "impact",
    url: p(2023, "07", "01", "thud", "b1b2b3b4b5"),
    duration_ms: 400,
    tags: ["thud", "impact"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_crash",
    name: "Crash",
    category: "impact",
    url: p(2023, "07", "01", "crash", "c2c3c4c5c6"),
    duration_ms: 800,
    tags: ["crash", "impact"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_hit_01",
    name: "Heavy Hit",
    category: "hit",
    url: p(2023, "07", "02", "heavy-hit", "d3d4d5d6d7"),
    duration_ms: 450,
    tags: ["hit", "heavy"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_hit_02",
    name: "Sharp Hit",
    category: "hit",
    url: p(2023, "07", "02", "sharp-hit", "e4e5e6e7e8"),
    duration_ms: 300,
    tags: ["hit", "sharp"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_punch",
    name: "Punch",
    category: "hit",
    url: p(2023, "07", "02", "punch", "f5f6f7f8f9"),
    duration_ms: 350,
    tags: ["punch", "hit"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_cinematic_hit",
    name: "Cinematic Hit",
    category: "impact",
    url: p(2023, "07", "03", "cinematic-hit", "a6a7a8a9aa"),
    duration_ms: 2000,
    tags: ["cinematic", "hit", "trailer"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_metal_hit",
    name: "Metal Hit",
    category: "hit",
    url: p(2023, "07", "03", "metal-hit", "b7b8b9babb"),
    duration_ms: 500,
    tags: ["metal", "hit"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_low_boom",
    name: "Low Boom",
    category: "impact",
    url: p(2023, "07", "03", "low-boom", "c8c9cacbcc"),
    duration_ms: 1800,
    tags: ["low", "boom"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_glass",
    name: "Glass Break",
    category: "hit",
    url: p(2023, "07", "04", "glass-break", "d9dadbdcdd"),
    duration_ms: 700,
    tags: ["glass", "shatter"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_explosion",
    name: "Explosion",
    category: "impact",
    url: p(2023, "07", "04", "explosion", "eaebecedee"),
    duration_ms: 2500,
    tags: ["explosion", "boom"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_deep_drum",
    name: "Deep Drum",
    category: "impact",
    url: p(2023, "07", "04", "deep-drum", "fbfcfdfeff"),
    duration_ms: 1200,
    tags: ["drum", "deep"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_slam",
    name: "Slam",
    category: "impact",
    url: p(2023, "07", "05", "slam", "0102030405"),
    duration_ms: 600,
    tags: ["slam", "hit"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_wood_break",
    name: "Wood Break",
    category: "hit",
    url: p(2023, "07", "05", "wood-break", "0607080910"),
    duration_ms: 500,
    tags: ["wood", "break"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_earthquake",
    name: "Earthquake Rumble",
    category: "impact",
    url: p(2023, "07", "05", "earthquake", "1112131415"),
    duration_ms: 4000,
    tags: ["rumble", "earthquake"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_thunder",
    name: "Thunder",
    category: "impact",
    url: p(2023, "07", "06", "thunder", "1617181920"),
    duration_ms: 3000,
    tags: ["thunder", "storm"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- UI (20) ----------
  {
    id: "sfx_ui_click_01",
    name: "Click",
    category: "ui",
    url: p(2023, "08", "01", "click", "2122232425"),
    duration_ms: 80,
    tags: ["click", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_click_02",
    name: "Soft Click",
    category: "ui",
    url: p(2023, "08", "01", "soft-click", "2627282930"),
    duration_ms: 60,
    tags: ["click", "soft"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_tap",
    name: "Tap",
    category: "ui",
    url: p(2023, "08", "01", "tap", "3132333435"),
    duration_ms: 70,
    tags: ["tap", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_pop_01",
    name: "Pop",
    category: "pop",
    url: p(2023, "08", "02", "pop", "3637383940"),
    duration_ms: 120,
    tags: ["pop", "bubble"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_pop_02",
    name: "Pop Bubble",
    category: "pop",
    url: p(2023, "08", "02", "pop-bubble", "4142434445"),
    duration_ms: 130,
    tags: ["pop", "bubble"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_bell",
    name: "Bell",
    category: "ui",
    url: p(2023, "08", "02", "bell", "4647484950"),
    duration_ms: 500,
    tags: ["bell", "notification"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_notification",
    name: "Notification",
    category: "ui",
    url: p(2023, "08", "03", "notification", "5152535455"),
    duration_ms: 350,
    tags: ["notification", "alert"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_success",
    name: "Success",
    category: "ui",
    url: p(2023, "08", "03", "success", "5657585960"),
    duration_ms: 500,
    tags: ["success", "confirm"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_error",
    name: "Error",
    category: "ui",
    url: p(2023, "08", "03", "error", "6162636465"),
    duration_ms: 400,
    tags: ["error", "fail"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_whip",
    name: "UI Whip",
    category: "ui",
    url: p(2023, "08", "04", "ui-whip", "6667686970"),
    duration_ms: 200,
    tags: ["whip", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_ding",
    name: "Ding",
    category: "ui",
    url: p(2023, "08", "04", "ding", "7172737475"),
    duration_ms: 400,
    tags: ["ding", "ui", "bell"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_swipe",
    name: "Swipe",
    category: "ui",
    url: p(2023, "08", "04", "swipe", "7677787980"),
    duration_ms: 300,
    tags: ["swipe", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_select",
    name: "Select",
    category: "ui",
    url: p(2023, "08", "05", "select", "8182838485"),
    duration_ms: 100,
    tags: ["select", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_deny",
    name: "Deny",
    category: "ui",
    url: p(2023, "08", "05", "deny", "8687888990"),
    duration_ms: 300,
    tags: ["deny", "error"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_transition_soft",
    name: "Soft Transition",
    category: "ui",
    url: p(2023, "08", "05", "soft-transition", "9192939495"),
    duration_ms: 400,
    tags: ["transition", "soft"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_swipe_right",
    name: "Swipe Right",
    category: "ui",
    url: p(2023, "08", "06", "swipe-right", "9697989900"),
    duration_ms: 250,
    tags: ["swipe", "right"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_swipe_left",
    name: "Swipe Left",
    category: "ui",
    url: p(2023, "08", "06", "swipe-left", "a1a2a3a4a5"),
    duration_ms: 250,
    tags: ["swipe", "left"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_hover",
    name: "Hover",
    category: "ui",
    url: p(2023, "08", "06", "hover", "b1b2b3b4b6"),
    duration_ms: 80,
    tags: ["hover", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_toggle",
    name: "Toggle",
    category: "ui",
    url: p(2023, "08", "07", "toggle", "c1c2c3c4c7"),
    duration_ms: 120,
    tags: ["toggle", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_message",
    name: "Message Sent",
    category: "ui",
    url: p(2023, "08", "07", "message-sent", "d1d2d3d4d8"),
    duration_ms: 300,
    tags: ["message", "sent"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- CINEMATIC (12) ----------
  {
    id: "sfx_cinema_riser_build",
    name: "Cinematic Riser Build",
    category: "riser",
    url: p(2023, "09", "01", "riser-build", "e1e2e3e4e5"),
    duration_ms: 8000,
    tags: ["riser", "cinematic", "build"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_sub_drop",
    name: "Sub Drop",
    category: "cinematic",
    url: p(2023, "09", "01", "sub-drop", "f1f2f3f4f5"),
    duration_ms: 2500,
    tags: ["sub", "drop", "bass"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_braam",
    name: "Braam",
    category: "cinematic",
    url: p(2023, "09", "02", "braam", "0a0b0c0d0e"),
    duration_ms: 3500,
    tags: ["braam", "trailer", "inception"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_horn",
    name: "Trailer Horn",
    category: "cinematic",
    url: p(2023, "09", "02", "trailer-horn", "1a1b1c1d1e"),
    duration_ms: 3000,
    tags: ["horn", "trailer"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_choir",
    name: "Choir Hit",
    category: "cinematic",
    url: p(2023, "09", "02", "choir-hit", "2a2b2c2d2e"),
    duration_ms: 2500,
    tags: ["choir", "cinematic"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_drone",
    name: "Cinematic Drone",
    category: "cinematic",
    url: p(2023, "09", "03", "cinematic-drone", "3a3b3c3d3e"),
    duration_ms: 10000,
    tags: ["drone", "ambient"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_tension",
    name: "Tension",
    category: "cinematic",
    url: p(2023, "09", "03", "tension", "4a4b4c4d4e"),
    duration_ms: 7000,
    tags: ["tension", "suspense"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_impact_riser",
    name: "Impact + Riser",
    category: "riser",
    url: p(2023, "09", "03", "impact-riser", "5a5b5c5d5e"),
    duration_ms: 5000,
    tags: ["riser", "impact"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_epic_hit",
    name: "Epic Hit",
    category: "cinematic",
    url: p(2023, "09", "04", "epic-hit", "6a6b6c6d6e"),
    duration_ms: 2000,
    tags: ["epic", "hit"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_stinger",
    name: "Cinematic Stinger",
    category: "cinematic",
    url: p(2023, "09", "04", "cinematic-stinger", "7a7b7c7d7e"),
    duration_ms: 1500,
    tags: ["stinger", "cinematic"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_logo_reveal",
    name: "Logo Reveal",
    category: "cinematic",
    url: p(2023, "09", "04", "logo-reveal", "8a8b8c8d8e"),
    duration_ms: 3000,
    tags: ["logo", "reveal"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_slow_boom",
    name: "Slow Boom",
    category: "cinematic",
    url: p(2023, "09", "05", "slow-boom", "9a9b9c9d9e"),
    duration_ms: 4500,
    tags: ["boom", "slow"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- MEME / COMEDY (14) ----------
  {
    id: "sfx_meme_bruh",
    name: "Bruh",
    category: "meme",
    url: p(2023, "10", "01", "bruh", "aababcadae"),
    duration_ms: 700,
    tags: ["bruh", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_womp_womp",
    name: "Womp Womp",
    category: "meme",
    url: p(2023, "10", "01", "womp-womp", "babbbcbdbe"),
    duration_ms: 1200,
    tags: ["womp", "sad-trombone", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_vine_boom",
    name: "Vine Boom",
    category: "meme",
    url: p(2023, "10", "01", "vine-boom", "cacbcccdce"),
    duration_ms: 2000,
    tags: ["vine", "boom", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_oof",
    name: "Oof",
    category: "meme",
    url: p(2023, "10", "02", "oof", "dadbdcdddd"),
    duration_ms: 400,
    tags: ["oof", "roblox", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_bonk",
    name: "Bonk",
    category: "meme",
    url: p(2023, "10", "02", "bonk", "eaebeced00"),
    duration_ms: 250,
    tags: ["bonk", "hit", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_trombone",
    name: "Sad Trombone",
    category: "comedy",
    url: p(2023, "10", "02", "sad-trombone", "fafbfcfd01"),
    duration_ms: 2500,
    tags: ["trombone", "sad", "comedy"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_rimshot",
    name: "Rimshot",
    category: "comedy",
    url: p(2023, "10", "03", "rimshot", "0a0b0c0d02"),
    duration_ms: 800,
    tags: ["rimshot", "joke", "comedy"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_boing",
    name: "Boing",
    category: "comedy",
    url: p(2023, "10", "03", "boing", "1a1b1c1d03"),
    duration_ms: 600,
    tags: ["boing", "spring"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_airhorn",
    name: "Airhorn",
    category: "comedy",
    url: p(2023, "10", "03", "airhorn", "2a2b2c2d04"),
    duration_ms: 1500,
    tags: ["airhorn", "mlg", "dj"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_squeaky_toy",
    name: "Squeaky Toy",
    category: "comedy",
    url: p(2023, "10", "04", "squeaky-toy", "3a3b3c3d05"),
    duration_ms: 400,
    tags: ["squeak", "toy"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_tada",
    name: "Tada",
    category: "meme",
    url: p(2023, "10", "04", "tada", "4a4b4c4d06"),
    duration_ms: 1200,
    tags: ["tada", "celebrate"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_record_scratch",
    name: "Record Scratch",
    category: "meme",
    url: p(2023, "10", "04", "record-scratch", "5a5b5c5d07"),
    duration_ms: 700,
    tags: ["scratch", "record"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_wrong_buzzer",
    name: "Wrong Buzzer",
    category: "meme",
    url: p(2023, "10", "05", "wrong-buzzer", "6a6b6c6d08"),
    duration_ms: 800,
    tags: ["wrong", "buzzer"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_correct_ding",
    name: "Correct Ding",
    category: "meme",
    url: p(2023, "10", "05", "correct-ding", "7a7b7c7d09"),
    duration_ms: 600,
    tags: ["correct", "ding"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- AMBIENT (10) ----------
  {
    id: "sfx_amb_wind",
    name: "Wind",
    category: "ambient",
    url: p(2023, "11", "01", "wind", "8a8b8c8d0a"),
    duration_ms: 30000,
    tags: ["wind", "ambient"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_rain",
    name: "Rain",
    category: "ambient",
    url: p(2023, "11", "01", "rain", "9a9b9c9d0b"),
    duration_ms: 30000,
    tags: ["rain", "ambient"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_crickets",
    name: "Crickets",
    category: "ambient",
    url: p(2023, "11", "01", "crickets", "aabbcc0c0d"),
    duration_ms: 30000,
    tags: ["crickets", "night"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_forest",
    name: "Forest",
    category: "ambient",
    url: p(2023, "11", "02", "forest", "babcbd0d0e"),
    duration_ms: 30000,
    tags: ["forest", "birds"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_crowd",
    name: "Crowd",
    category: "ambient",
    url: p(2023, "11", "02", "crowd", "cacdce0e0f"),
    duration_ms: 30000,
    tags: ["crowd", "city"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_ocean",
    name: "Ocean Waves",
    category: "ambient",
    url: p(2023, "11", "02", "ocean-waves", "dadedf0f10"),
    duration_ms: 30000,
    tags: ["ocean", "waves"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_fire",
    name: "Fireplace",
    category: "ambient",
    url: p(2023, "11", "03", "fireplace", "ededef1011"),
    duration_ms: 30000,
    tags: ["fire", "crackle"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_cafe",
    name: "Cafe",
    category: "ambient",
    url: p(2023, "11", "03", "cafe", "ffeeff1112"),
    duration_ms: 30000,
    tags: ["cafe", "chatter"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_space",
    name: "Space Hum",
    category: "ambient",
    url: p(2023, "11", "03", "space-hum", "00112233aa"),
    duration_ms: 30000,
    tags: ["space", "drone"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_traffic",
    name: "Traffic",
    category: "ambient",
    url: p(2023, "11", "04", "traffic", "11223344bb"),
    duration_ms: 30000,
    tags: ["traffic", "city"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- RISERS (6) ----------
  {
    id: "sfx_riser_8s",
    name: "Riser 8s",
    category: "riser",
    url: p(2023, "12", "01", "riser-8s", "22334455cc"),
    duration_ms: 8000,
    tags: ["riser", "build", "8s"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_12s",
    name: "Riser 12s",
    category: "riser",
    url: p(2023, "12", "01", "riser-12s", "33445566dd"),
    duration_ms: 12000,
    tags: ["riser", "build", "12s"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_16s",
    name: "Riser 16s",
    category: "riser",
    url: p(2023, "12", "01", "riser-16s", "44556677ee"),
    duration_ms: 16000,
    tags: ["riser", "build", "16s"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_noise",
    name: "Noise Riser",
    category: "riser",
    url: p(2023, "12", "02", "noise-riser", "55667788ff"),
    duration_ms: 6000,
    tags: ["riser", "noise"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_synth",
    name: "Synth Riser",
    category: "riser",
    url: p(2023, "12", "02", "synth-riser", "66778899aa"),
    duration_ms: 8000,
    tags: ["riser", "synth"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_reverse",
    name: "Reverse Riser",
    category: "riser",
    url: p(2023, "12", "02", "reverse-riser", "778899aabb"),
    duration_ms: 5000,
    tags: ["riser", "reverse"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- EXTRA POPS / SWOOSHES / HITS (11 — fills out to 100+) ----------
  {
    id: "sfx_pop_light",
    name: "Light Pop",
    category: "pop",
    url: p(2024, "01", "01", "light-pop", "8899aabbcc"),
    duration_ms: 80,
    tags: ["pop", "light"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_pop_deep",
    name: "Deep Pop",
    category: "pop",
    url: p(2024, "01", "01", "deep-pop", "99aabbccdd"),
    duration_ms: 140,
    tags: ["pop", "deep"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_pop_cork",
    name: "Cork Pop",
    category: "pop",
    url: p(2024, "01", "01", "cork-pop", "aabbccddee"),
    duration_ms: 250,
    tags: ["cork", "pop"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_swoosh_metallic",
    name: "Metallic Swoosh",
    category: "swoosh",
    url: p(2024, "01", "02", "metallic-swoosh", "bbccddeeff"),
    duration_ms: 600,
    tags: ["metallic", "swoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_swoosh_tech",
    name: "Tech Swoosh",
    category: "swoosh",
    url: p(2024, "01", "02", "tech-swoosh", "ccddeeff00"),
    duration_ms: 500,
    tags: ["tech", "swoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_swoosh_magic",
    name: "Magic Swoosh",
    category: "swoosh",
    url: p(2024, "01", "02", "magic-swoosh", "ddeeff0011"),
    duration_ms: 700,
    tags: ["magic", "swoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_hit_snare",
    name: "Snare Hit",
    category: "hit",
    url: p(2024, "01", "03", "snare-hit", "eeff001122"),
    duration_ms: 250,
    tags: ["snare", "drum"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_hit_kick",
    name: "Kick Drum",
    category: "hit",
    url: p(2024, "01", "03", "kick-drum", "ff00112233"),
    duration_ms: 300,
    tags: ["kick", "drum"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_hit_808",
    name: "808 Boom",
    category: "hit",
    url: p(2024, "01", "03", "808-boom", "0011223344"),
    duration_ms: 500,
    tags: ["808", "bass"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_heartbeat",
    name: "Heartbeat",
    category: "cinematic",
    url: p(2024, "01", "04", "heartbeat", "1122334455"),
    duration_ms: 1200,
    tags: ["heartbeat", "tension"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_whoosh_impact",
    name: "Whoosh + Impact Combo",
    category: "cinematic",
    url: p(2024, "01", "04", "whoosh-impact", "2233445566"),
    duration_ms: 1800,
    tags: ["whoosh", "impact", "combo"],
    license: "royalty-free",
    source: "pixabay",
  },
];

/** Filter SFX by category. */
export function filterSfxByCategory(category: SfxCategory): Sfx[] {
  return SFX_LIBRARY.filter((s) => s.category === category);
}

/** Return SFX whose tags intersect the given tag set. */
export function filterSfxByTags(tags: string[]): Sfx[] {
  if (!tags.length) return SFX_LIBRARY;
  const s = new Set(tags.map((t) => t.toLowerCase()));
  return SFX_LIBRARY.filter((sfx) =>
    sfx.tags.some((t) => s.has(t.toLowerCase())),
  );
}

/** Return SFX by id, or undefined. */
export function getSfxById(id: string): Sfx | undefined {
  return SFX_LIBRARY.find((s) => s.id === id);
}

/** Pseudo-random SFX pick. */
export function getRandomSfx(seed?: number): Sfx {
  const idx =
    typeof seed === "number"
      ? Math.abs(Math.floor(seed)) % SFX_LIBRARY.length
      : Math.floor(Math.random() * SFX_LIBRARY.length);
  return SFX_LIBRARY[idx]!;
}
