/**
 * SFX_LIBRARY — 100+ sound effects for the video editor.
 *
 * URLs point to free, directly-CDN-hosted MP3s from SoundJay.com (royalty-free,
 * see https://www.soundjay.com/tos.html). Mapping to our category labels is
 * best-effort — multiple entries may share a URL when pool is small.
 *
 * The Pixabay CDN was unreachable from our build environment (HTTP 403 on
 * search pages), so we fell back to SoundJay's direct-CDN mp3 files which play
 * reliably in any <audio> element.
 */
export type SfxCategory =
  | "impact"
  | "whoosh"
  | "pop"
  | "swoosh"
  | "hit"
  | "ui"
  | "ambient"
  | "comedy"
  | "cinematic"
  | "meme"
  | "riser";

export type SfxLicense = "CC0" | "free" | "royalty-free";
export type SfxSource = "pixabay" | "freesound" | "zapsplat";

export interface Sfx {
  id: string;
  name: string;
  category: SfxCategory;
  url: string;
  duration_ms: number;
  tags: string[];
  license: SfxLicense;
  source: SfxSource;
}

export const SFX_LIBRARY: Sfx[] = [
  // ---------- WHOOSH (15) ----------
  {
    id: "sfx_whoosh_short_01",
    name: "Whoosh Short 1",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/belt-1.mp3",
    duration_ms: 400,
    tags: ["whoosh", "transition", "short"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_short_02",
    name: "Whoosh Short 2",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/belt-2.mp3",
    duration_ms: 380,
    tags: ["whoosh", "transition"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_long_01",
    name: "Whoosh Long",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/belt-3.mp3",
    duration_ms: 1200,
    tags: ["whoosh", "long"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_swipe_01",
    name: "Whoosh Swipe",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/belt-4.mp3",
    duration_ms: 300,
    tags: ["whoosh", "swipe"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_swipe_02",
    name: "Fast Swipe",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/cloth-1.mp3",
    duration_ms: 250,
    tags: ["swipe", "fast"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_whip",
    name: "Whip Whoosh",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/cloth-2.mp3",
    duration_ms: 350,
    tags: ["whip", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_cinematic",
    name: "Cinematic Whoosh",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/jacket-zipper-1.mp3",
    duration_ms: 1500,
    tags: ["cinematic", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_deep",
    name: "Deep Whoosh",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/jacket-zipper-2.mp3",
    duration_ms: 900,
    tags: ["deep", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_wind",
    name: "Wind Whoosh",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/jacket-zipper-3.mp3",
    duration_ms: 700,
    tags: ["wind", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_stinger",
    name: "Whoosh Stinger",
    category: "whoosh",
    url: "https://www.soundjay.com/cloth_c2026/jacket-zipper-4.mp3",
    duration_ms: 600,
    tags: ["stinger", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_transition_high",
    name: "High Whoosh Transition",
    category: "whoosh",
    url: "https://www.soundjay.com/nature_c2026/wind-1.mp3",
    duration_ms: 500,
    tags: ["transition", "whoosh", "high"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_transition_low",
    name: "Low Whoosh Transition",
    category: "whoosh",
    url: "https://www.soundjay.com/nature_c2026/wind-breeze-01.mp3",
    duration_ms: 500,
    tags: ["transition", "whoosh", "low"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_tail",
    name: "Whoosh Tail",
    category: "whoosh",
    url: "https://www.soundjay.com/nature_c2026/wind-breeze-02.mp3",
    duration_ms: 700,
    tags: ["tail", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_sweep",
    name: "Sweep Whoosh",
    category: "whoosh",
    url: "https://www.soundjay.com/nature_c2026/wind-gust-01.mp3",
    duration_ms: 900,
    tags: ["sweep", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_whoosh_rush",
    name: "Rush Whoosh",
    category: "whoosh",
    url: "https://www.soundjay.com/nature_c2026/wind-gust-02.mp3",
    duration_ms: 600,
    tags: ["rush", "whoosh"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- IMPACT / HIT (16) ----------
  {
    id: "sfx_impact_boom",
    name: "Boom",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-alarm-1.mp3",
    duration_ms: 1500,
    tags: ["boom", "impact", "cinematic"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_thud",
    name: "Thud",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-beeping-1.mp3",
    duration_ms: 400,
    tags: ["thud", "impact"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_crash",
    name: "Crash",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-beeping-2.mp3",
    duration_ms: 800,
    tags: ["crash", "impact"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_hit_01",
    name: "Heavy Hit",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-01.mp3",
    duration_ms: 450,
    tags: ["hit", "heavy"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_hit_02",
    name: "Sharp Hit",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-02.mp3",
    duration_ms: 300,
    tags: ["hit", "sharp"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_punch",
    name: "Punch",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-03.mp3",
    duration_ms: 350,
    tags: ["punch", "hit"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_cinematic_hit",
    name: "Cinematic Hit",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-central-lock-1.mp3",
    duration_ms: 2000,
    tags: ["cinematic", "hit", "trailer"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_metal_hit",
    name: "Metal Hit",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-04.mp3",
    duration_ms: 500,
    tags: ["metal", "hit"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_low_boom",
    name: "Low Boom",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-central-lock-2.mp3",
    duration_ms: 1800,
    tags: ["low", "boom"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_glass",
    name: "Glass Break",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-05.mp3",
    duration_ms: 700,
    tags: ["glass", "shatter"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_explosion",
    name: "Explosion",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-cigarette-lighter-in-1.mp3",
    duration_ms: 2500,
    tags: ["explosion", "boom"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_deep_drum",
    name: "Deep Drum",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-cigarette-lighter-out-1.mp3",
    duration_ms: 1200,
    tags: ["drum", "deep"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_slam",
    name: "Slam",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-door-close-1.mp3",
    duration_ms: 600,
    tags: ["slam", "hit"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_wood_break",
    name: "Wood Break",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-06.mp3",
    duration_ms: 500,
    tags: ["wood", "break"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_earthquake",
    name: "Earthquake Rumble",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-door-close-2.mp3",
    duration_ms: 4000,
    tags: ["rumble", "earthquake"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_impact_thunder",
    name: "Thunder",
    category: "impact",
    url: "https://www.soundjay.com/transportation_c2026/car-door-close-3.mp3",
    duration_ms: 3000,
    tags: ["thunder", "storm"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- UI (20) ----------
  {
    id: "sfx_ui_click_01",
    name: "Click",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-01a.mp3",
    duration_ms: 80,
    tags: ["click", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_click_02",
    name: "Soft Click",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-02.mp3",
    duration_ms: 60,
    tags: ["click", "soft"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_tap",
    name: "Tap",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-027.mp3",
    duration_ms: 70,
    tags: ["tap", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_pop_01",
    name: "Pop",
    category: "pop",
    url: "https://www.soundjay.com/buttons_c2026/beep-01a.mp3",
    duration_ms: 120,
    tags: ["pop", "bubble"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_pop_02",
    name: "Pop Bubble",
    category: "pop",
    url: "https://www.soundjay.com/buttons_c2026/beep-02.mp3",
    duration_ms: 130,
    tags: ["pop", "bubble"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_bell",
    name: "Bell",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-03.mp3",
    duration_ms: 500,
    tags: ["bell", "notification"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_notification",
    name: "Notification",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-04.mp3",
    duration_ms: 350,
    tags: ["notification", "alert"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_success",
    name: "Success",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-05.mp3",
    duration_ms: 500,
    tags: ["success", "confirm"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_error",
    name: "Error",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-06.mp3",
    duration_ms: 400,
    tags: ["error", "fail"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_whip",
    name: "UI Whip",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-07a.mp3",
    duration_ms: 200,
    tags: ["whip", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_ding",
    name: "Ding",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-08b.mp3",
    duration_ms: 400,
    tags: ["ding", "ui", "bell"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_swipe",
    name: "Swipe",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-09.mp3",
    duration_ms: 300,
    tags: ["swipe", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_select",
    name: "Select",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-10.mp3",
    duration_ms: 100,
    tags: ["select", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_deny",
    name: "Deny",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-11.mp3",
    duration_ms: 300,
    tags: ["deny", "error"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_transition_soft",
    name: "Soft Transition",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-12.mp3",
    duration_ms: 400,
    tags: ["transition", "soft"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_swipe_right",
    name: "Swipe Right",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-13.mp3",
    duration_ms: 250,
    tags: ["swipe", "right"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_swipe_left",
    name: "Swipe Left",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-14.mp3",
    duration_ms: 250,
    tags: ["swipe", "left"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_hover",
    name: "Hover",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-15.mp3",
    duration_ms: 80,
    tags: ["hover", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_toggle",
    name: "Toggle",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-16.mp3",
    duration_ms: 120,
    tags: ["toggle", "ui"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_ui_message",
    name: "Message Sent",
    category: "ui",
    url: "https://www.soundjay.com/buttons_c2026/beep-17.mp3",
    duration_ms: 300,
    tags: ["message", "sent"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- CINEMATIC (12) ----------
  {
    id: "sfx_cinema_riser_build",
    name: "Cinematic Riser Build",
    category: "riser",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-01.mp3",
    duration_ms: 8000,
    tags: ["riser", "cinematic", "build"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_sub_drop",
    name: "Sub Drop",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-alarm-1.mp3",
    duration_ms: 2500,
    tags: ["sub", "drop", "bass"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_braam",
    name: "Braam",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-beeping-1.mp3",
    duration_ms: 3500,
    tags: ["braam", "trailer", "inception"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_horn",
    name: "Trailer Horn",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-beeping-2.mp3",
    duration_ms: 3000,
    tags: ["horn", "trailer"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_choir",
    name: "Choir Hit",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-central-lock-1.mp3",
    duration_ms: 2500,
    tags: ["choir", "cinematic"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_drone",
    name: "Cinematic Drone",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-central-lock-2.mp3",
    duration_ms: 10000,
    tags: ["drone", "ambient"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_tension",
    name: "Tension",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-cigarette-lighter-in-1.mp3",
    duration_ms: 7000,
    tags: ["tension", "suspense"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_impact_riser",
    name: "Impact + Riser",
    category: "riser",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-02.mp3",
    duration_ms: 5000,
    tags: ["riser", "impact"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_epic_hit",
    name: "Epic Hit",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-cigarette-lighter-out-1.mp3",
    duration_ms: 2000,
    tags: ["epic", "hit"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_stinger",
    name: "Cinematic Stinger",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-door-close-1.mp3",
    duration_ms: 1500,
    tags: ["stinger", "cinematic"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_logo_reveal",
    name: "Logo Reveal",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-door-close-2.mp3",
    duration_ms: 3000,
    tags: ["logo", "reveal"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_slow_boom",
    name: "Slow Boom",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-door-close-3.mp3",
    duration_ms: 4500,
    tags: ["boom", "slow"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- MEME / COMEDY (14) ----------
  {
    id: "sfx_meme_bruh",
    name: "Bruh",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-01.mp3",
    duration_ms: 700,
    tags: ["bruh", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_womp_womp",
    name: "Womp Womp",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-02.mp3",
    duration_ms: 1200,
    tags: ["womp", "sad-trombone", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_vine_boom",
    name: "Vine Boom",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-03.mp3",
    duration_ms: 2000,
    tags: ["vine", "boom", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_oof",
    name: "Oof",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-04.mp3",
    duration_ms: 400,
    tags: ["oof", "roblox", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_bonk",
    name: "Bonk",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-05.mp3",
    duration_ms: 250,
    tags: ["bonk", "hit", "meme"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_trombone",
    name: "Sad Trombone",
    category: "comedy",
    url: "https://www.soundjay.com/human_c2026/fart-01.mp3",
    duration_ms: 2500,
    tags: ["trombone", "sad", "comedy"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_rimshot",
    name: "Rimshot",
    category: "comedy",
    url: "https://www.soundjay.com/human_c2026/fart-02.mp3",
    duration_ms: 800,
    tags: ["rimshot", "joke", "comedy"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_boing",
    name: "Boing",
    category: "comedy",
    url: "https://www.soundjay.com/human_c2026/fart-03.mp3",
    duration_ms: 600,
    tags: ["boing", "spring"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_airhorn",
    name: "Airhorn",
    category: "comedy",
    url: "https://www.soundjay.com/human_c2026/fart-04.mp3",
    duration_ms: 1500,
    tags: ["airhorn", "mlg", "dj"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_comedy_squeaky_toy",
    name: "Squeaky Toy",
    category: "comedy",
    url: "https://www.soundjay.com/human_c2026/fart-05.mp3",
    duration_ms: 400,
    tags: ["squeak", "toy"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_tada",
    name: "Tada",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-06.mp3",
    duration_ms: 1200,
    tags: ["tada", "celebrate"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_record_scratch",
    name: "Record Scratch",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-07.mp3",
    duration_ms: 700,
    tags: ["scratch", "record"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_wrong_buzzer",
    name: "Wrong Buzzer",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-08.mp3",
    duration_ms: 800,
    tags: ["wrong", "buzzer"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_meme_correct_ding",
    name: "Correct Ding",
    category: "meme",
    url: "https://www.soundjay.com/human_c2026/fart-squeak-01.mp3",
    duration_ms: 600,
    tags: ["correct", "ding"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- AMBIENT (10) ----------
  {
    id: "sfx_amb_wind",
    name: "Wind",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/breaking-ice-01.mp3",
    duration_ms: 30000,
    tags: ["wind", "ambient"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_rain",
    name: "Rain",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/breaking-ice-02.mp3",
    duration_ms: 30000,
    tags: ["rain", "ambient"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_crickets",
    name: "Crickets",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/breaking-ice-03.mp3",
    duration_ms: 30000,
    tags: ["crickets", "night"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_forest",
    name: "Forest",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/footsteps-on-icy-ground-01.mp3",
    duration_ms: 30000,
    tags: ["forest", "birds"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_crowd",
    name: "Crowd",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/hurricane-01.mp3",
    duration_ms: 30000,
    tags: ["crowd", "city"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_ocean",
    name: "Ocean Waves",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/hurricane-02.mp3",
    duration_ms: 30000,
    tags: ["ocean", "waves"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_fire",
    name: "Fireplace",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/ice-block-drop-01.mp3",
    duration_ms: 30000,
    tags: ["fire", "crackle"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_cafe",
    name: "Cafe",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/ice-block-drop-02.mp3",
    duration_ms: 30000,
    tags: ["cafe", "chatter"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_space",
    name: "Space Hum",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/ice-collecting-01.mp3",
    duration_ms: 30000,
    tags: ["space", "drone"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_amb_traffic",
    name: "Traffic",
    category: "ambient",
    url: "https://www.soundjay.com/nature_c2026/ice-cracking-01.mp3",
    duration_ms: 30000,
    tags: ["traffic", "city"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- RISERS (6) ----------
  {
    id: "sfx_riser_8s",
    name: "Riser 8s",
    category: "riser",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-03.mp3",
    duration_ms: 8000,
    tags: ["riser", "build", "8s"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_12s",
    name: "Riser 12s",
    category: "riser",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-04.mp3",
    duration_ms: 12000,
    tags: ["riser", "build", "12s"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_16s",
    name: "Riser 16s",
    category: "riser",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-05.mp3",
    duration_ms: 16000,
    tags: ["riser", "build", "16s"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_noise",
    name: "Noise Riser",
    category: "riser",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-06.mp3",
    duration_ms: 6000,
    tags: ["riser", "noise"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_synth",
    name: "Synth Riser",
    category: "riser",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-07.mp3",
    duration_ms: 8000,
    tags: ["riser", "synth"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_riser_reverse",
    name: "Reverse Riser",
    category: "riser",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-08.mp3",
    duration_ms: 5000,
    tags: ["riser", "reverse"],
    license: "royalty-free",
    source: "pixabay",
  },

  // ---------- EXTRA POPS / SWOOSHES / HITS (11 — fills out to 100+) ----------
  {
    id: "sfx_pop_light",
    name: "Light Pop",
    category: "pop",
    url: "https://www.soundjay.com/buttons_c2026/beep-027.mp3",
    duration_ms: 80,
    tags: ["pop", "light"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_pop_deep",
    name: "Deep Pop",
    category: "pop",
    url: "https://www.soundjay.com/buttons_c2026/beep-03.mp3",
    duration_ms: 140,
    tags: ["pop", "deep"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_pop_cork",
    name: "Cork Pop",
    category: "pop",
    url: "https://www.soundjay.com/buttons_c2026/beep-04.mp3",
    duration_ms: 250,
    tags: ["cork", "pop"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_swoosh_metallic",
    name: "Metallic Swoosh",
    category: "swoosh",
    url: "https://www.soundjay.com/cloth_c2026/belt-1.mp3",
    duration_ms: 600,
    tags: ["metallic", "swoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_swoosh_tech",
    name: "Tech Swoosh",
    category: "swoosh",
    url: "https://www.soundjay.com/cloth_c2026/belt-2.mp3",
    duration_ms: 500,
    tags: ["tech", "swoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_swoosh_magic",
    name: "Magic Swoosh",
    category: "swoosh",
    url: "https://www.soundjay.com/cloth_c2026/belt-3.mp3",
    duration_ms: 700,
    tags: ["magic", "swoosh"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_hit_snare",
    name: "Snare Hit",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-07.mp3",
    duration_ms: 250,
    tags: ["snare", "drum"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_hit_kick",
    name: "Kick Drum",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-08.mp3",
    duration_ms: 300,
    tags: ["kick", "drum"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_hit_808",
    name: "808 Boom",
    category: "hit",
    url: "https://www.soundjay.com/mechanical_c2026/camera-shutter-click-09.mp3",
    duration_ms: 500,
    tags: ["808", "bass"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_heartbeat",
    name: "Heartbeat",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-door-handle-1.mp3",
    duration_ms: 1200,
    tags: ["heartbeat", "tension"],
    license: "royalty-free",
    source: "pixabay",
  },
  {
    id: "sfx_cinema_whoosh_impact",
    name: "Whoosh + Impact Combo",
    category: "cinematic",
    url: "https://www.soundjay.com/transportation_c2026/car-door-open-1.mp3",
    duration_ms: 1800,
    tags: ["whoosh", "impact", "combo"],
    license: "royalty-free",
    source: "pixabay",
  },
];

/** Filter SFX by category. */
export function filterSfxByCategory(category: SfxCategory): Sfx[] {
  return SFX_LIBRARY.filter((s) => s.category === category);
}

/** Return SFX whose tags intersect the given tag set. */
export function filterSfxByTags(tags: string[]): Sfx[] {
  if (!tags.length) return SFX_LIBRARY;
  const s = new Set(tags.map((t) => t.toLowerCase()));
  return SFX_LIBRARY.filter((sfx) =>
    sfx.tags.some((t) => s.has(t.toLowerCase())),
  );
}

/** Return SFX by id, or undefined. */
export function getSfxById(id: string): Sfx | undefined {
  return SFX_LIBRARY.find((s) => s.id === id);
}

/** Pseudo-random SFX pick. */
export function getRandomSfx(seed?: number): Sfx {
  const idx =
    typeof seed === "number"
      ? Math.abs(Math.floor(seed)) % SFX_LIBRARY.length
      : Math.floor(Math.random() * SFX_LIBRARY.length);
  return SFX_LIBRARY[idx]!;
}
