/**
 * TRANSITIONS_LIBRARY — 100+ video transitions for the editor.
 *
 * Each entry is a data-only preset. The renderer reads `category` + `id` to pick
 * an implementation; `cssOrCompositorHint` is an optional one-line hint for the
 * compositor (CSS filter string, After Effects preset name, or a symbolic
 * keyword the ffmpeg filtergraph builder understands).
 */

export type TransitionCategory =
  | "cut"
  | "fade"
  | "slide"
  | "zoom"
  | "rotate"
  | "whip"
  | "glitch"
  | "masking"
  | "3d"
  | "creative";

export interface Transition {
  id: string;
  name: string;
  category: TransitionCategory;
  duration_ms: number;
  description: string;
  cssOrCompositorHint: string;
}

export const TRANSITIONS_LIBRARY: Transition[] = [
  // ---------- CUT (5) ----------
  {
    id: "tr_cut_hard",
    name: "Hard Cut",
    category: "cut",
    duration_ms: 0,
    description: "Instant switch with no blend. The editor's default.",
    cssOrCompositorHint: "none",
  },
  {
    id: "tr_cut_flash",
    name: "Flash Cut",
    category: "cut",
    duration_ms: 80,
    description: "White-flash punctuating the cut. Great for ads.",
    cssOrCompositorHint: "filter: brightness(3)",
  },
  {
    id: "tr_cut_match",
    name: "Match Cut",
    category: "cut",
    duration_ms: 0,
    description: "Hard cut aligned on matching composition between shots.",
    cssOrCompositorHint: "none",
  },
  {
    id: "tr_cut_j",
    name: "J-Cut",
    category: "cut",
    duration_ms: 0,
    description: "Audio from next clip starts before its video does.",
    cssOrCompositorHint: "audio-lead",
  },
  {
    id: "tr_cut_l",
    name: "L-Cut",
    category: "cut",
    duration_ms: 0,
    description: "Audio from previous clip continues into next clip's video.",
    cssOrCompositorHint: "audio-trail",
  },

  // ---------- FADE (9) ----------
  {
    id: "tr_fade_cross",
    name: "Crossfade",
    category: "fade",
    duration_ms: 500,
    description: "Classic dissolve between two clips.",
    cssOrCompositorHint: "opacity-blend",
  },
  {
    id: "tr_fade_long_cross",
    name: "Long Crossfade",
    category: "fade",
    duration_ms: 1500,
    description: "Slow romantic dissolve.",
    cssOrCompositorHint: "opacity-blend",
  },
  {
    id: "tr_fade_dip_black",
    name: "Dip to Black",
    category: "fade",
    duration_ms: 600,
    description: "Fade to black, then up into next clip.",
    cssOrCompositorHint: "fade-via: #000000",
  },
  {
    id: "tr_fade_dip_white",
    name: "Dip to White",
    category: "fade",
    duration_ms: 500,
    description: "Fade to white, then up. Feels clean and bright.",
    cssOrCompositorHint: "fade-via: #FFFFFF",
  },
  {
    id: "tr_fade_dip_color",
    name: "Dip to Color",
    category: "fade",
    duration_ms: 500,
    description: "Fade through a custom brand color.",
    cssOrCompositorHint: "fade-via: var(--brand)",
  },
  {
    id: "tr_fade_through_color_red",
    name: "Fade Through Red",
    category: "fade",
    duration_ms: 400,
    description: "High-impact fade via red flash.",
    cssOrCompositorHint: "fade-via: #FF2D2D",
  },
  {
    id: "tr_fade_through_color_blue",
    name: "Fade Through Blue",
    category: "fade",
    duration_ms: 400,
    description: "Cool-tone fade via blue flash.",
    cssOrCompositorHint: "fade-via: #2D7FFF",
  },
  {
    id: "tr_fade_film",
    name: "Film Fade",
    category: "fade",
    duration_ms: 700,
    description: "Fade with a subtle grain/flicker overlay.",
    cssOrCompositorHint: "fade + grain(0.1)",
  },
  {
    id: "tr_fade_additive",
    name: "Additive Dissolve",
    category: "fade",
    duration_ms: 600,
    description: "Blends clips by addition — highlights blow out during cross.",
    cssOrCompositorHint: "blend: plus-lighter",
  },

  // ---------- SLIDE (16 — 8 slide + 8 wipe + push variants) ----------
  {
    id: "tr_slide_left",
    name: "Slide Left",
    category: "slide",
    duration_ms: 450,
    description: "Next clip slides in from the right, pushing old out left.",
    cssOrCompositorHint: "transform: translateX(-100%)",
  },
  {
    id: "tr_slide_right",
    name: "Slide Right",
    category: "slide",
    duration_ms: 450,
    description: "Next clip slides in from the left.",
    cssOrCompositorHint: "transform: translateX(100%)",
  },
  {
    id: "tr_slide_up",
    name: "Slide Up",
    category: "slide",
    duration_ms: 450,
    description: "Next clip slides in from bottom.",
    cssOrCompositorHint: "transform: translateY(-100%)",
  },
  {
    id: "tr_slide_down",
    name: "Slide Down",
    category: "slide",
    duration_ms: 450,
    description: "Next clip slides in from top.",
    cssOrCompositorHint: "transform: translateY(100%)",
  },
  {
    id: "tr_slide_up_left",
    name: "Slide Up-Left",
    category: "slide",
    duration_ms: 450,
    description: "Diagonal slide from bottom-right.",
    cssOrCompositorHint: "transform: translate(-100%, -100%)",
  },
  {
    id: "tr_slide_up_right",
    name: "Slide Up-Right",
    category: "slide",
    duration_ms: 450,
    description: "Diagonal slide from bottom-left.",
    cssOrCompositorHint: "transform: translate(100%, -100%)",
  },
  {
    id: "tr_slide_down_left",
    name: "Slide Down-Left",
    category: "slide",
    duration_ms: 450,
    description: "Diagonal slide from top-right.",
    cssOrCompositorHint: "transform: translate(-100%, 100%)",
  },
  {
    id: "tr_slide_down_right",
    name: "Slide Down-Right",
    category: "slide",
    duration_ms: 450,
    description: "Diagonal slide from top-left.",
    cssOrCompositorHint: "transform: translate(100%, 100%)",
  },
  {
    id: "tr_push_left",
    name: "Push Left",
    category: "slide",
    duration_ms: 400,
    description: "Two clips move as a pair — outgoing pushed left.",
    cssOrCompositorHint: "push: left",
  },
  {
    id: "tr_push_right",
    name: "Push Right",
    category: "slide",
    duration_ms: 400,
    description: "Two clips move as a pair — outgoing pushed right.",
    cssOrCompositorHint: "push: right",
  },
  {
    id: "tr_push_up",
    name: "Push Up",
    category: "slide",
    duration_ms: 400,
    description: "Outgoing pushed up.",
    cssOrCompositorHint: "push: up",
  },
  {
    id: "tr_push_down",
    name: "Push Down",
    category: "slide",
    duration_ms: 400,
    description: "Outgoing pushed down.",
    cssOrCompositorHint: "push: down",
  },
  {
    id: "tr_wipe_left",
    name: "Wipe Left",
    category: "slide",
    duration_ms: 400,
    description: "Hard edge reveals next clip from right to left.",
    cssOrCompositorHint: "wipe: left",
  },
  {
    id: "tr_wipe_right",
    name: "Wipe Right",
    category: "slide",
    duration_ms: 400,
    description: "Hard edge reveals next clip from left to right.",
    cssOrCompositorHint: "wipe: right",
  },
  {
    id: "tr_wipe_up",
    name: "Wipe Up",
    category: "slide",
    duration_ms: 400,
    description: "Reveal edge moves bottom-to-top.",
    cssOrCompositorHint: "wipe: up",
  },
  {
    id: "tr_wipe_down",
    name: "Wipe Down",
    category: "slide",
    duration_ms: 400,
    description: "Reveal edge moves top-to-bottom.",
    cssOrCompositorHint: "wipe: down",
  },

  // ---------- ZOOM (8) ----------
  {
    id: "tr_zoom_in",
    name: "Zoom In",
    category: "zoom",
    duration_ms: 400,
    description: "Outgoing clip scales up until it cuts.",
    cssOrCompositorHint: "scale(1.4)",
  },
  {
    id: "tr_zoom_out",
    name: "Zoom Out",
    category: "zoom",
    duration_ms: 400,
    description: "Outgoing clip scales down to reveal next.",
    cssOrCompositorHint: "scale(0.6)",
  },
  {
    id: "tr_zoom_blur",
    name: "Zoom Blur",
    category: "zoom",
    duration_ms: 450,
    description: "Radial blur while zooming — high-impact.",
    cssOrCompositorHint: "blur+scale",
  },
  {
    id: "tr_zoom_punch",
    name: "Punch-In Zoom",
    category: "zoom",
    duration_ms: 200,
    description: "Fast, snappy zoom-in on cut. Ad-style.",
    cssOrCompositorHint: "scale(1.15)",
  },
  {
    id: "tr_zoom_punch_out",
    name: "Punch-Out Zoom",
    category: "zoom",
    duration_ms: 200,
    description: "Fast zoom-out on cut.",
    cssOrCompositorHint: "scale(0.85)",
  },
  {
    id: "tr_zoom_bounce",
    name: "Zoom Bounce",
    category: "zoom",
    duration_ms: 500,
    description: "Zoom in then slight snap-back.",
    cssOrCompositorHint: "scale + spring",
  },
  {
    id: "tr_zoom_motion_blur",
    name: "Motion-Blur Zoom",
    category: "zoom",
    duration_ms: 300,
    description: "Punchy zoom with directional motion blur.",
    cssOrCompositorHint: "scale + motion-blur",
  },
  {
    id: "tr_zoom_iris",
    name: "Iris Zoom",
    category: "zoom",
    duration_ms: 550,
    description: "Circular iris opens/closes while zooming.",
    cssOrCompositorHint: "iris + scale",
  },

  // ---------- ROTATE / FLIP (8) ----------
  {
    id: "tr_rotate_cw",
    name: "Rotate Clockwise",
    category: "rotate",
    duration_ms: 500,
    description: "Outgoing clip spins 360° clockwise.",
    cssOrCompositorHint: "rotate(360deg)",
  },
  {
    id: "tr_rotate_ccw",
    name: "Rotate Counter-Clockwise",
    category: "rotate",
    duration_ms: 500,
    description: "Outgoing clip spins counter-clockwise.",
    cssOrCompositorHint: "rotate(-360deg)",
  },
  {
    id: "tr_spin_fast",
    name: "Spin Fast",
    category: "rotate",
    duration_ms: 300,
    description: "Quick double-rotation with motion blur.",
    cssOrCompositorHint: "rotate(720deg) + blur",
  },
  {
    id: "tr_spin_slow",
    name: "Spin Slow",
    category: "rotate",
    duration_ms: 1200,
    description: "Long hypnotic spin.",
    cssOrCompositorHint: "rotate(360deg)",
  },
  {
    id: "tr_flip_horizontal",
    name: "Flip Horizontal",
    category: "rotate",
    duration_ms: 450,
    description: "3D Y-axis flip revealing next clip.",
    cssOrCompositorHint: "rotateY(180deg)",
  },
  {
    id: "tr_flip_vertical",
    name: "Flip Vertical",
    category: "rotate",
    duration_ms: 450,
    description: "3D X-axis flip revealing next clip.",
    cssOrCompositorHint: "rotateX(180deg)",
  },
  {
    id: "tr_tumble",
    name: "Tumble",
    category: "rotate",
    duration_ms: 600,
    description: "Rotate + scale down + fade — feels chaotic.",
    cssOrCompositorHint: "rotate + scale + fade",
  },
  {
    id: "tr_pinwheel",
    name: "Pinwheel",
    category: "rotate",
    duration_ms: 700,
    description: "Clip breaks into rotating quadrants.",
    cssOrCompositorHint: "quadrant-rotate",
  },

  // ---------- WHIP PAN / SPEED RAMP (8) ----------
  {
    id: "tr_whip_left",
    name: "Whip Pan Left",
    category: "whip",
    duration_ms: 220,
    description: "Camera whips left with heavy motion blur.",
    cssOrCompositorHint: "translateX(-100%) + motion-blur",
  },
  {
    id: "tr_whip_right",
    name: "Whip Pan Right",
    category: "whip",
    duration_ms: 220,
    description: "Camera whips right.",
    cssOrCompositorHint: "translateX(100%) + motion-blur",
  },
  {
    id: "tr_whip_up",
    name: "Whip Pan Up",
    category: "whip",
    duration_ms: 220,
    description: "Camera whips up.",
    cssOrCompositorHint: "translateY(-100%) + motion-blur",
  },
  {
    id: "tr_whip_down",
    name: "Whip Pan Down",
    category: "whip",
    duration_ms: 220,
    description: "Camera whips down.",
    cssOrCompositorHint: "translateY(100%) + motion-blur",
  },
  {
    id: "tr_whip_diagonal",
    name: "Whip Pan Diagonal",
    category: "whip",
    duration_ms: 240,
    description: "Diagonal whip with blur streaks.",
    cssOrCompositorHint: "translate(-100%, -100%) + blur",
  },
  {
    id: "tr_speed_ramp_up",
    name: "Speed Ramp Up",
    category: "whip",
    duration_ms: 400,
    description: "Speeds the end of clip A into clip B's start.",
    cssOrCompositorHint: "timeRemap: 1→3",
  },
  {
    id: "tr_speed_ramp_down",
    name: "Speed Ramp Down",
    category: "whip",
    duration_ms: 400,
    description: "Slows end of clip A into clip B's start (for drama).",
    cssOrCompositorHint: "timeRemap: 1→0.3",
  },
  {
    id: "tr_freeze_frame",
    name: "Freeze Frame",
    category: "whip",
    duration_ms: 200,
    description: "Holds last frame of clip A for a beat before cutting.",
    cssOrCompositorHint: "freeze(200ms)",
  },

  // ---------- GLITCH / DIGITAL (10) ----------
  {
    id: "tr_glitch_basic",
    name: "Glitch",
    category: "glitch",
    duration_ms: 250,
    description: "Pixel displacement + color-channel shift.",
    cssOrCompositorHint: "glitch(0.5)",
  },
  {
    id: "tr_glitch_heavy",
    name: "Heavy Glitch",
    category: "glitch",
    duration_ms: 400,
    description: "Big blocky displacement, scanlines, RGB split.",
    cssOrCompositorHint: "glitch(1.0) + scanlines",
  },
  {
    id: "tr_rgb_split",
    name: "RGB Split",
    category: "glitch",
    duration_ms: 300,
    description: "Red, green, blue channels separate on cut.",
    cssOrCompositorHint: "rgbOffset(8px)",
  },
  {
    id: "tr_datamosh",
    name: "Datamosh",
    category: "glitch",
    duration_ms: 500,
    description: "Compression-artifact smearing between keyframes.",
    cssOrCompositorHint: "datamosh",
  },
  {
    id: "tr_pixel_sort",
    name: "Pixel Sort",
    category: "glitch",
    duration_ms: 450,
    description: "Rows of pixels sorted by brightness during cut.",
    cssOrCompositorHint: "pixel-sort",
  },
  {
    id: "tr_scanline_sweep",
    name: "Scanline Sweep",
    category: "glitch",
    duration_ms: 350,
    description: "CRT-style horizontal sweep reveals next clip.",
    cssOrCompositorHint: "scanline-sweep",
  },
  {
    id: "tr_static_noise",
    name: "Static Noise",
    category: "glitch",
    duration_ms: 250,
    description: "VHS static fills between clips.",
    cssOrCompositorHint: "noise(100%)",
  },
  {
    id: "tr_vhs_tracking",
    name: "VHS Tracking",
    category: "glitch",
    duration_ms: 400,
    description: "Warped tracking lines + horizontal jitter.",
    cssOrCompositorHint: "vhs-tracking",
  },
  {
    id: "tr_bitcrush",
    name: "Bitcrush",
    category: "glitch",
    duration_ms: 300,
    description: "Color depth crushes to 8 levels then recovers.",
    cssOrCompositorHint: "posterize(8)",
  },
  {
    id: "tr_chromatic_split",
    name: "Chromatic Aberration",
    category: "glitch",
    duration_ms: 350,
    description: "Heavy lens fringing during transition.",
    cssOrCompositorHint: "chromatic(12px)",
  },

  // ---------- MASKING (10) ----------
  {
    id: "tr_mask_circle",
    name: "Circle Reveal",
    category: "masking",
    duration_ms: 500,
    description: "Growing circular mask reveals next clip.",
    cssOrCompositorHint: "clip-path: circle",
  },
  {
    id: "tr_mask_iris_in",
    name: "Iris In",
    category: "masking",
    duration_ms: 600,
    description: "Circle shrinks to hide outgoing clip.",
    cssOrCompositorHint: "clip-path: circle 100→0",
  },
  {
    id: "tr_mask_iris_out",
    name: "Iris Out",
    category: "masking",
    duration_ms: 600,
    description: "Circle grows to reveal next clip.",
    cssOrCompositorHint: "clip-path: circle 0→100",
  },
  {
    id: "tr_mask_heart",
    name: "Heart Reveal",
    category: "masking",
    duration_ms: 650,
    description: "Heart-shaped mask grows — cute/romantic.",
    cssOrCompositorHint: "clip-path: heart",
  },
  {
    id: "tr_mask_star",
    name: "Star Reveal",
    category: "masking",
    duration_ms: 600,
    description: "Star-shaped mask grows.",
    cssOrCompositorHint: "clip-path: star",
  },
  {
    id: "tr_mask_diamond",
    name: "Diamond Reveal",
    category: "masking",
    duration_ms: 600,
    description: "Diamond mask grows.",
    cssOrCompositorHint: "clip-path: polygon(diamond)",
  },
  {
    id: "tr_mask_squares",
    name: "Squares Grid",
    category: "masking",
    duration_ms: 800,
    description: "Grid of square tiles flip in sequence.",
    cssOrCompositorHint: "grid-flip",
  },
  {
    id: "tr_mask_stripes_h",
    name: "Horizontal Blinds",
    category: "masking",
    duration_ms: 700,
    description: "Horizontal blinds close then open on next clip.",
    cssOrCompositorHint: "blinds: horizontal",
  },
  {
    id: "tr_mask_stripes_v",
    name: "Vertical Blinds",
    category: "masking",
    duration_ms: 700,
    description: "Vertical blinds close then open.",
    cssOrCompositorHint: "blinds: vertical",
  },
  {
    id: "tr_mask_custom_shape",
    name: "Custom Shape Reveal",
    category: "masking",
    duration_ms: 700,
    description: "User-defined SVG path grows to reveal next clip.",
    cssOrCompositorHint: "clip-path: path()",
  },

  // ---------- 3D (10) ----------
  {
    id: "tr_3d_cube_rotate",
    name: "Cube Rotate",
    category: "3d",
    duration_ms: 700,
    description: "Clips live on faces of a cube that rotates 90°.",
    cssOrCompositorHint: "cube(90deg, y)",
  },
  {
    id: "tr_3d_cube_rotate_up",
    name: "Cube Rotate Up",
    category: "3d",
    duration_ms: 700,
    description: "Cube rotates up 90°.",
    cssOrCompositorHint: "cube(90deg, x)",
  },
  {
    id: "tr_3d_page_turn",
    name: "Page Turn",
    category: "3d",
    duration_ms: 900,
    description: "Outgoing clip peels like a book page.",
    cssOrCompositorHint: "pageCurl",
  },
  {
    id: "tr_3d_book_open",
    name: "Book Open",
    category: "3d",
    duration_ms: 1000,
    description: "Clips split open like pages of a book.",
    cssOrCompositorHint: "book-open",
  },
  {
    id: "tr_3d_card_flip",
    name: "Card Flip",
    category: "3d",
    duration_ms: 600,
    description: "Flip like a card — back side is next clip.",
    cssOrCompositorHint: "cardFlip(y)",
  },
  {
    id: "tr_3d_door_open",
    name: "Door Open",
    category: "3d",
    duration_ms: 800,
    description: "Outgoing clip splits in two and swings open.",
    cssOrCompositorHint: "door-open",
  },
  {
    id: "tr_3d_fold",
    name: "Fold",
    category: "3d",
    duration_ms: 800,
    description: "Outgoing clip folds in half like paper.",
    cssOrCompositorHint: "fold",
  },
  {
    id: "tr_3d_carousel",
    name: "Carousel",
    category: "3d",
    duration_ms: 800,
    description: "Clips on a rotating vertical carousel.",
    cssOrCompositorHint: "carousel(y)",
  },
  {
    id: "tr_3d_panel_fly",
    name: "Panel Fly",
    category: "3d",
    duration_ms: 600,
    description: "Old clip flies away in 3D space.",
    cssOrCompositorHint: "translateZ(-1000)",
  },
  {
    id: "tr_3d_unfold",
    name: "Unfold",
    category: "3d",
    duration_ms: 900,
    description: "Next clip unfolds from a rolled-up corner.",
    cssOrCompositorHint: "unfold",
  },

  // ---------- CREATIVE (16) ----------
  {
    id: "tr_ink_spread",
    name: "Ink Spread",
    category: "creative",
    duration_ms: 900,
    description: "Ink blot grows and reveals next clip.",
    cssOrCompositorHint: "ink-spread",
  },
  {
    id: "tr_water_ripple",
    name: "Water Ripple",
    category: "creative",
    duration_ms: 800,
    description: "Concentric ripple distorts outgoing clip.",
    cssOrCompositorHint: "ripple",
  },
  {
    id: "tr_shatter",
    name: "Shatter",
    category: "creative",
    duration_ms: 700,
    description: "Outgoing clip breaks into glass shards.",
    cssOrCompositorHint: "shatter",
  },
  {
    id: "tr_smoke",
    name: "Smoke",
    category: "creative",
    duration_ms: 900,
    description: "Smoke swallows outgoing and clears on next.",
    cssOrCompositorHint: "smoke-overlay",
  },
  {
    id: "tr_light_leak",
    name: "Light Leak",
    category: "creative",
    duration_ms: 600,
    description: "Warm film light leak bridges the cut.",
    cssOrCompositorHint: "light-leak",
  },
  {
    id: "tr_film_burn",
    name: "Film Burn",
    category: "creative",
    duration_ms: 700,
    description: "Old-film burn, curl, and sear between clips.",
    cssOrCompositorHint: "film-burn",
  },
  {
    id: "tr_film_flash",
    name: "Film Flash",
    category: "creative",
    duration_ms: 150,
    description: "Blown-out single-frame photo-flash.",
    cssOrCompositorHint: "flash(1frame)",
  },
  {
    id: "tr_confetti_wipe",
    name: "Confetti Wipe",
    category: "creative",
    duration_ms: 700,
    description: "Confetti burst clears outgoing clip.",
    cssOrCompositorHint: "confetti-overlay",
  },
  {
    id: "tr_particle_dissolve",
    name: "Particle Dissolve",
    category: "creative",
    duration_ms: 800,
    description: "Pixels float away like dust.",
    cssOrCompositorHint: "particle-dissolve",
  },
  {
    id: "tr_lightning_strike",
    name: "Lightning Strike",
    category: "creative",
    duration_ms: 350,
    description: "Bright white lightning-bolt flash + rumble.",
    cssOrCompositorHint: "lightning",
  },
  {
    id: "tr_ink_bleed",
    name: "Ink Bleed",
    category: "creative",
    duration_ms: 900,
    description: "Ink bleeds from edges to cover clip.",
    cssOrCompositorHint: "ink-bleed",
  },
  {
    id: "tr_brush_stroke",
    name: "Brush Stroke",
    category: "creative",
    duration_ms: 700,
    description: "Paintbrush swipe reveals next clip.",
    cssOrCompositorHint: "brush-stroke",
  },
  {
    id: "tr_clock_wipe",
    name: "Clock Wipe",
    category: "creative",
    duration_ms: 600,
    description: "Radial wipe rotates like a clock hand.",
    cssOrCompositorHint: "clock-wipe",
  },
  {
    id: "tr_star_wipe",
    name: "Star Wipe",
    category: "creative",
    duration_ms: 600,
    description: "Star-shaped wipe — 70s-TV vibe.",
    cssOrCompositorHint: "star-wipe",
  },
  {
    id: "tr_bokeh_blur",
    name: "Bokeh Blur",
    category: "creative",
    duration_ms: 600,
    description: "Blurs to bokeh circles then refocuses on next clip.",
    cssOrCompositorHint: "bokeh",
  },
  {
    id: "tr_color_pop",
    name: "Color Pop",
    category: "creative",
    duration_ms: 300,
    description: "Flash a brand-color overlay on cut.",
    cssOrCompositorHint: "overlay(brand)",
  },
];

/** Filter transitions by category. */
export function filterTransitionsByCategory(
  category: TransitionCategory,
): Transition[] {
  return TRANSITIONS_LIBRARY.filter((t) => t.category === category);
}

/** Return a transition by id, or undefined. */
export function getTransitionById(id: string): Transition | undefined {
  return TRANSITIONS_LIBRARY.find((t) => t.id === id);
}

/** Pseudo-random pick; seed for deterministic output. */
export function getRandomTransition(seed?: number): Transition {
  const idx =
    typeof seed === "number"
      ? Math.abs(Math.floor(seed)) % TRANSITIONS_LIBRARY.length
      : Math.floor(Math.random() * TRANSITIONS_LIBRARY.length);
  return TRANSITIONS_LIBRARY[idx]!;
}
