"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/lib/auth-context";
import { createClient } from "@/lib/supabase/client";
import { Client } from "@/lib/types";
import { formatCurrency } from "@/lib/utils";
import {
  FileText, Download, Sparkles, Loader, Send,
  TrendingUp, Users, BarChart3, Copy
} from "lucide-react";
import toast from "react-hot-toast";

export default function ClientReportsPage() {
  useAuth();
  const supabase = createClient();
  const [clients, setClients] = useState<Client[]>([]);
  const [selectedClient, setSelectedClient] = useState("");
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase.from("clients").select("*").eq("is_active", true).order("business_name").then(({ data }) => {
      setClients(data || []);
      setLoading(false);
    });
  }, []);

  async function generateReport() {
    if (!selectedClient) { toast.error("Select a client"); return; }
    setGenerating(true);
    setReport("");

    const client = clients.find(c => c.id === selectedClient);
    if (!client) { setGenerating(false); return; }

    // Fetch client data
    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();

    const [
      { count: leadsGenerated },
      { count: outreachSent },
      { count: repliesReceived },
      { data: contentPosts },
      { data: aiActions },
    ] = await Promise.all([
      supabase.from("leads").select("*", { count: "exact", head: true }).eq("client_id", selectedClient).gte("created_at", monthStart),
      supabase.from("outreach_log").select("*", { count: "exact", head: true }).gte("sent_at", monthStart),
      supabase.from("outreach_log").select("*", { count: "exact", head: true }).eq("status", "replied").gte("sent_at", monthStart),
      supabase.from("content_calendar").select("*").eq("client_id", selectedClient).gte("scheduled_at", monthStart),
      supabase.from("trinity_log").select("*").eq("client_id", selectedClient).gte("created_at", monthStart),
    ]);

    // Generate AI report
    try {
      const res = await fetch("/api/agents/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: `Write a professional monthly marketing report for ${client.business_name} (${client.industry || "business"}).

Data this month:
- Package: ${client.package_tier || "Growth"} ($${client.mrr}/mo)
- Leads generated: ${leadsGenerated || 0}
- Outreach messages sent: ${outreachSent || 0}
- Replies received: ${repliesReceived || 0}
- Content pieces: ${(contentPosts || []).length}
- AI agent actions: ${(aiActions || []).length}
- Health score: ${client.health_score}%

Write the report with sections: Executive Summary, Key Metrics, What We Did This Month, Results & Wins, Next Month's Plan, and Recommendations. Keep it professional but conversational. No markdown formatting — use plain text with clear section headers.`,
          agent_name: "Analytics Agent",
        }),
      });
      const data = await res.json();
      setReport(data.result || "Failed to generate report");
    } catch { setReport("Error generating report"); }

    setGenerating(false);
  }

  function downloadReport() {
    if (!report) return;
    const client = clients.find(c => c.id === selectedClient);
    const text = `SHORTSTACK DIGITAL
Monthly Marketing Report
${client?.business_name || "Client"}
${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}
${"=".repeat(50)}

${report}

${"=".repeat(50)}
Generated by ShortStack OS
shortstackdigital.com`;

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${client?.business_name.replace(/\s/g, "_")}_Report_${new Date().toISOString().slice(0, 7)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!");
  }

  if (loading) return <div className="flex items-center justify-center py-20"><Loader size={20} className="animate-spin text-gold" /></div>;

  return (
    <div className="fade-in space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="page-header mb-0 flex items-center gap-2">
            <FileText size={18} className="text-gold" /> Client Reports
          </h1>
          <p className="text-xs text-muted mt-0.5">Generate monthly marketing reports for clients</p>
        </div>
      </div>

      {/* Client selector + generate */}
      <div className="card">
        <div className="flex gap-3 items-end">
          <div className="flex-1">
            <label className="block text-[10px] text-muted mb-1 font-semibold">Select Client</label>
            <select value={selectedClient} onChange={e => setSelectedClient(e.target.value)} className="input w-full">
              <option value="">Choose a client...</option>
              {clients.map(c => (
                <option key={c.id} value={c.id}>{c.business_name} — {c.package_tier || "Standard"} ({formatCurrency(c.mrr)}/mo)</option>
              ))}
            </select>
          </div>
          <button onClick={generateReport} disabled={generating || !selectedClient}
            className="btn-primary text-xs flex items-center gap-1.5 disabled:opacity-50 shrink-0">
            {generating ? <Loader size={12} className="animate-spin" /> : <Sparkles size={12} />}
            {generating ? "Generating..." : "Generate Report"}
          </button>
        </div>
      </div>

      {/* Quick stats for selected client */}
      {selectedClient && (
        <div className="grid grid-cols-4 gap-3">
          {(() => {
            const client = clients.find(c => c.id === selectedClient);
            if (!client) return null;
            return <>
              <div className="card text-center">
                <TrendingUp size={14} className="mx-auto mb-1 text-gold" />
                <p className="text-lg font-bold">{client.health_score}%</p>
                <p className="text-[9px] text-muted">Health Score</p>
              </div>
              <div className="card text-center">
                <BarChart3 size={14} className="mx-auto mb-1 text-gold" />
                <p className="text-lg font-bold">{formatCurrency(client.mrr)}</p>
                <p className="text-[9px] text-muted">MRR</p>
              </div>
              <div className="card text-center">
                <Users size={14} className="mx-auto mb-1 text-gold" />
                <p className="text-lg font-bold">{client.package_tier || "Standard"}</p>
                <p className="text-[9px] text-muted">Package</p>
              </div>
              <div className="card text-center">
                <FileText size={14} className="mx-auto mb-1 text-gold" />
                <p className="text-lg font-bold">{(client.services || []).length}</p>
                <p className="text-[9px] text-muted">Services</p>
              </div>
            </>;
          })()}
        </div>
      )}

      {/* Report output */}
      {report && (
        <div className="card">
          <div className="flex items-center justify-between mb-3">
            <h2 className="section-header mb-0">Generated Report</h2>
            <div className="flex gap-2">
              <button onClick={() => { navigator.clipboard.writeText(report); toast.success("Copied!"); }}
                className="btn-ghost text-xs flex items-center gap-1"><Copy size={10} /> Copy</button>
              <button onClick={downloadReport}
                className="btn-secondary text-xs flex items-center gap-1"><Download size={10} /> Download</button>
              <button onClick={() => toast.success("Send via email — coming soon!")}
                className="btn-primary text-xs flex items-center gap-1"><Send size={10} /> Email to Client</button>
            </div>
          </div>
          <pre className="text-xs leading-relaxed whitespace-pre-wrap text-muted p-4 rounded-lg bg-surface-light">
            {report}
          </pre>
        </div>
      )}

      {!report && !generating && (
        <div className="card text-center py-16">
          <FileText size={32} className="mx-auto mb-3 text-muted/20" />
          <p className="text-sm text-muted mb-1">Select a client and generate their monthly report</p>
          <p className="text-[10px] text-muted/50">AI analyzes their data and creates a professional report you can send</p>
        </div>
      )}
    </div>
  );
}
