import { NextResponse } from "next/server";
import { readFile, stat } from "fs/promises";
import path from "path";

/**
 * Returns the download manifest for the ShortStack desktop app.
 *
 * Shape (when available):
 * {
 *   available: true,
 *   version: "1.4.0",
 *   updated: "2026-04-13T18:37:32.956Z",
 *   base: "/downloads" | "https://r2.shortstack.dev/desktop",
 *   files: {
 *     windows: { file: "ShortStack-OS-Setup.exe", size: 177239499, sha512: "..." },
 *     mac:     { file: "ShortStack-OS.dmg",       size: 0, sha512: null } | null,
 *     linux:   { file: "ShortStack-OS.AppImage",  size: 0, sha512: null } | null
 *   }
 * }
 *
 * When no manifest is available (Electron never built or binaries not staged)
 * we return { available: false } so the UI can show a graceful fallback.
 *
 * The manifest.json is generated by `npm run postbuild:electron` which copies
 * `dist-electron/ShortStack-OS-<version>-Setup.exe` to `public/downloads/` and
 * writes `public/downloads/manifest.json` with size + mtime metadata.
 *
 * If `DESKTOP_DOWNLOAD_BASE_URL` is set (e.g. a Cloudflare R2 public URL),
 * the manifest's `base` field points there instead of `/downloads`, so files
 * >25MB can live on R2 rather than Vercel's static bundle.
 */
export async function GET() {
  const manifestPath = path.join(process.cwd(), "public", "downloads", "manifest.json");
  const base = process.env.DESKTOP_DOWNLOAD_BASE_URL?.replace(/\/$/, "") || "/downloads";

  try {
    await stat(manifestPath);
    const raw = await readFile(manifestPath, "utf8");
    const parsed = JSON.parse(raw);
    return NextResponse.json({ available: true, base, ...parsed }, { status: 200 });
  } catch {
    return NextResponse.json(
      {
        available: false,
        base,
        reason: "Desktop installer manifest not found. Run `npm run postbuild:electron` after building, or configure DESKTOP_DOWNLOAD_BASE_URL.",
      },
      { status: 200 },
    );
  }
}
