"use client";

import { useEffect, useState, useRef } from "react";
import { motion } from "framer-motion";
import { createClient } from "@/lib/supabase/client";
import toast from "react-hot-toast";
import {
  FileText, Sparkles, Users, TrendingUp, TrendingDown,
  Loader, Clock, BarChart3, RefreshCw,
  ChevronDown, ChevronUp, Copy, Check, Calendar,
  Download, Mail, ClipboardCopy, Share2,
} from "lucide-react";
import { EmptyState } from "@/components/ui/empty-state-illustration";
import { MotionPage } from "@/components/motion/motion-page";

interface Client {
  id: string;
  business_name: string;
  contact_name: string;
  email: string;
  mrr: number;
  health_score: number;
  is_active: boolean;
}

interface Report {
  id: string;
  description: string;
  client_id: string;
  created_at: string;
  result: {
    type: string;
    report: string;
    metrics?: {
      leads: number;
      leads_trend: string;
      outreach: number;
      replies: number;
      deals_won: number;
      deals_revenue: number;
    };
  };
}

interface GeneratedReport {
  report: string;
  client: string;
  type: string;
  metrics: {
    leads: number;
    leads_trend: string;
    outreach: number;
    replies: number;
    deals_won: number;
    deals_revenue: number;
    health_score: number;
    mrr: number;
  };
}

export default function ReportsPage() {
  const supabase = createClient();
  const [clients, setClients] = useState<Client[]>([]);
  const [reports, setReports] = useState<Report[]>([]);
  const [selectedClient, setSelectedClient] = useState<string>("");
  const [reportType, setReportType] = useState<"weekly" | "monthly">("weekly");
  const [generating, setGenerating] = useState(false);
  const [currentReport, setCurrentReport] = useState<GeneratedReport | null>(null);
  const [expandedReport, setExpandedReport] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [loading, setLoading] = useState(true);
  const [exportOpen, setExportOpen] = useState(false);
  const [emailFormOpen, setEmailFormOpen] = useState(false);
  const [emailAddress, setEmailAddress] = useState("");
  const exportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetchData();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function fetchData() {
    setLoading(true);
    try {
      const [{ data: clientData }, reportsRes] = await Promise.all([
        supabase.from("clients").select("id, business_name, contact_name, email, mrr, health_score, is_active").eq("is_active", true).order("business_name"),
        fetch("/api/reports/generate").then(r => r.json()).catch(() => ({ reports: [] })),
      ]);
      setClients(clientData || []);
      setReports(reportsRes.reports || []);
    } finally {
      // Prevent the page from hanging on a spinner if either request throws.
      setLoading(false);
    }
  }

  async function generateReport() {
    if (!selectedClient) return;
    setGenerating(true);
    setCurrentReport(null);
    try {
      const res = await fetch("/api/reports/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ client_id: selectedClient, report_type: reportType }),
      });
      const data = await res.json();
      if (data.success) {
        setCurrentReport(data);
        fetchData(); // Refresh report list
      }
    } catch {
      // Error handled silently
    }
    setGenerating(false);
  }

  // Close export dropdown on outside click
  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (exportRef.current && !exportRef.current.contains(e.target as Node)) {
        setExportOpen(false);
      }
    }
    if (exportOpen) {
      document.addEventListener("mousedown", handleClickOutside);
      return () => document.removeEventListener("mousedown", handleClickOutside);
    }
  }, [exportOpen]);

  function buildReportMarkdown(report: GeneratedReport): string {
    const lines: string[] = [];
    const typeLabel = report.type === "monthly" ? "Monthly" : "Weekly";
    lines.push(`# ${typeLabel} Report � ${report.client}`);
    lines.push("");
    if (report.metrics) {
      const m = report.metrics;
      lines.push("## Key Metrics");
      lines.push("");
      lines.push(`| Metric | Value |`);
      lines.push(`| --- | --- |`);
      lines.push(`| Leads | ${m.leads} (${m.leads_trend !== "N/A" ? `${m.leads_trend}%` : "N/A"}) |`);
      lines.push(`| Outreach | ${m.outreach} |`);
      lines.push(`| Replies | ${m.replies} |`);
      lines.push(`| Deals Won | ${m.deals_won} ($${m.deals_revenue.toLocaleString()}) |`);
      lines.push(`| Health Score | ${m.health_score}% |`);
      lines.push(`| MRR | $${m.mrr.toLocaleString()} |`);
      lines.push("");
    }
    lines.push("## Report");
    lines.push("");
    lines.push(report.report);
    lines.push("");
    lines.push(`---`);
    lines.push(`Generated by Trinity on ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`);
    return lines.join("\n");
  }

  function buildReportHTML(report: GeneratedReport): string {
    const typeLabel = report.type === "monthly" ? "Monthly" : "Weekly";
    const m = report.metrics;
    const metricsHTML = m ? `
      <table style="width:100%;border-collapse:collapse;margin:24px 0;">
        <thead>
          <tr style="background:#FBF9F4;border-bottom:2px solid #2563EB;">
            <th style="text-align:left;padding:10px 14px;font-size:12px;color:#6B7280;font-weight:600;">Metric</th>
            <th style="text-align:right;padding:10px 14px;font-size:12px;color:#6B7280;font-weight:600;">Value</th>
          </tr>
        </thead>
        <tbody>
          <tr style="border-bottom:1px solid #E8E5E0;">
            <td style="padding:10px 14px;font-size:13px;color:#374151;">Leads</td>
            <td style="padding:10px 14px;font-size:13px;color:#374151;text-align:right;font-weight:600;">${m.leads}${m.leads_trend !== "N/A" ? ` <span style="color:${parseInt(m.leads_trend) >= 0 ? "#2563EB" : "#EF4444"};font-size:11px;">(${parseInt(m.leads_trend) >= 0 ? "+" : ""}${m.leads_trend}%)</span>` : ""}</td>
          </tr>
          <tr style="border-bottom:1px solid #E8E5E0;background:#FEFDFB;">
            <td style="padding:10px 14px;font-size:13px;color:#374151;">Outreach</td>
            <td style="padding:10px 14px;font-size:13px;color:#374151;text-align:right;font-weight:600;">${m.outreach}</td>
          </tr>
          <tr style="border-bottom:1px solid #E8E5E0;">
            <td style="padding:10px 14px;font-size:13px;color:#374151;">Replies</td>
            <td style="padding:10px 14px;font-size:13px;color:#374151;text-align:right;font-weight:600;">${m.replies}</td>
          </tr>
          <tr style="border-bottom:1px solid #E8E5E0;background:#FEFDFB;">
            <td style="padding:10px 14px;font-size:13px;color:#374151;">Deals Won</td>
            <td style="padding:10px 14px;font-size:13px;color:#374151;text-align:right;font-weight:600;">${m.deals_won} ($${m.deals_revenue.toLocaleString()})</td>
          </tr>
          <tr style="border-bottom:1px solid #E8E5E0;">
            <td style="padding:10px 14px;font-size:13px;color:#374151;">Health Score</td>
            <td style="padding:10px 14px;font-size:13px;text-align:right;font-weight:600;color:${m.health_score >= 70 ? "#2563EB" : m.health_score >= 40 ? "#F59E0B" : "#EF4444"};">${m.health_score}%</td>
          </tr>
          <tr style="background:#FEFDFB;">
            <td style="padding:10px 14px;font-size:13px;color:#374151;">MRR</td>
            <td style="padding:10px 14px;font-size:13px;color:#374151;text-align:right;font-weight:600;">$${m.mrr.toLocaleString()}</td>
          </tr>
        </tbody>
      </table>` : "";

    const reportParagraphs = report.report
      .split("\n")
      .map(line => line.trim())
      .filter(Boolean)
      .map(line => `<p style="margin:0 0 12px;font-size:13px;line-height:1.7;color:#374151;">${line.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p>`)
      .join("\n        ");

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${typeLabel} Report � ${report.client}</title>
  <style>
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .no-print { display: none !important; }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', Roboto, sans-serif;
      background: #FAFAF7;
      margin: 0;
      padding: 40px 20px;
      color: #374151;
    }
    .container {
      max-width: 720px;
      margin: 0 auto;
      background: #FFFFFF;
      border-radius: 16px;
      border: 1px solid #E8E5E0;
      overflow: hidden;
      box-shadow: 0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.02);
    }
    .header {
      background: linear-gradient(135deg, #1A1A2E 0%, #2D2D44 100%);
      padding: 32px 40px;
    }
    .brand {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 16px;
    }
    .brand-dot {
      width: 10px;
      height: 10px;
      border-radius: 50%;
      background: #2563EB;
    }
    .brand-name {
      font-size: 13px;
      font-weight: 600;
      color: #2563EB;
      letter-spacing: 0.5px;
    }
    .title {
      font-size: 22px;
      font-weight: 700;
      color: #FFFFFF;
      margin: 0;
    }
    .subtitle {
      font-size: 13px;
      color: rgba(255,255,255,0.6);
      margin: 6px 0 0;
    }
    .body { padding: 32px 40px; }
    .section-title {
      font-size: 11px;
      font-weight: 600;
      color: #2563EB;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin: 0 0 16px;
    }
    .footer {
      border-top: 1px solid #E8E5E0;
      padding: 20px 40px;
      text-align: center;
    }
    .footer-text {
      font-size: 11px;
      color: #9CA3AF;
    }
    .print-btn {
      display: inline-block;
      margin: 0 auto 32px;
      padding: 10px 24px;
      background: #2563EB;
      color: #fff;
      border: none;
      border-radius: 8px;
      font-size: 13px;
      font-weight: 600;
      cursor: pointer;
      text-align: center;
    }
    .print-btn:hover { opacity: 0.9; }
  </style>
</head>
<body>
  <div style="text-align:center;" class="no-print">
    <button class="print-btn" onclick="window.print()">Print / Save as PDF</button>
  </div>
  <div class="container">
    <div class="header">
      <div class="brand">
        <div class="brand-dot"></div>
        <span class="brand-name">SHORTSTACK OS</span>
      </div>
      <h1 class="title">${typeLabel} Report</h1>
      <p class="subtitle">${report.client} &mdash; ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
    </div>
    <div class="body">
      ${m ? `<p class="section-title">Key Metrics</p>${metricsHTML}` : ""}
      <p class="section-title">Report Summary</p>
      <div>
        ${reportParagraphs}
      </div>
    </div>
    <div class="footer">
      <p class="footer-text">Generated by Trinity &bull; ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
    </div>
  </div>
</body>
</html>`;
  }

  function downloadReportHTML() {
    if (!currentReport) return;
    const html = buildReportHTML(currentReport);
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const safeClient = currentReport.client.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase();
    a.href = url;
    a.download = `report-${safeClient}-${currentReport.type}-${new Date().toISOString().split("T")[0]}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setExportOpen(false);
    toast.success("HTML report downloaded");
  }

  function copyReportMarkdown() {
    if (!currentReport) return;
    const md = buildReportMarkdown(currentReport);
    navigator.clipboard.writeText(md);
    setExportOpen(false);
    toast.success("Report copied to clipboard as Markdown");
  }

  function handleEmailReport() {
    setExportOpen(false);
    setEmailFormOpen(true);
  }

  function submitEmailReport(e: React.FormEvent) {
    e.preventDefault();
    toast("Email sending requires SMTP setup", { icon: "\u2709\uFE0F" });
    setEmailFormOpen(false);
    setEmailAddress("");
  }

  function copyReport() {
    if (currentReport?.report) {
      navigator.clipboard.writeText(currentReport.report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  function getClientName(clientId: string) {
    return clients.find(c => c.id === clientId)?.business_name || "Unknown";
  }

  const totalReports = reports.length;
  const weeklyReports = reports.filter(r => r.result?.type === "weekly_report").length;
  const monthlyReports = reports.filter(r => r.result?.type === "monthly_report").length;
  const uniqueClients = new Set(reports.map(r => r.client_id)).size;

  return (
    <MotionPage className="p-6 max-w-7xl mx-auto space-y-6">{/* Hero Header */}{/* -- AI Client Reports command strip -- */}
    <div className="flex items-center justify-between gap-4 px-1 py-3 sm:py-4">
      <div className="min-w-0">
        <p className="font-editorial text-[11px] italic text-text-muted mb-0.5">Intelligence Reports</p>
        <h1 className="font-display text-xl sm:text-2xl font-bold tracking-tight text-text-primary leading-none">AI Client Reports</h1>
      </div>
      <div className="flex items-center gap-2 shrink-0">
        <button onClick={fetchData}
                  className="text-xs flex items-center gap-1.5 px-4 py-2 rounded-xl bg-black/10 border border-border-subtle text-text-primary font-medium hover:bg-black/15 transition-all">
                  <RefreshCw size={12} /> Refresh
                </button>
      </div>
    </div>{/* Stats */}
            <div className="grid grid-cols-2 lg:grid-cols-[4fr_2fr_2fr_2fr] gap-3 mb-4">
              <motion.div
                className="col-span-2 lg:col-span-1 glass rounded-2xl p-5 flex items-center gap-4"
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.38, delay: 0.04, ease: [0.22, 1, 0.36, 1] }}
              >
                <div>
                  <p className="text-[10px] font-medium uppercase tracking-[0.14em] text-text-muted mb-1.5">Total Reports</p>
                  <p className="font-display text-3xl font-bold tracking-[-0.03em] text-text-primary tabular-nums">{totalReports}</p>
                  <p className="text-[11px] text-text-muted mt-1.5">generated</p>
                </div>
              </motion.div>
              <motion.div
                className="glass rounded-2xl p-5 flex flex-col justify-center"
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.38, delay: 0.10, ease: [0.22, 1, 0.36, 1] }}
              >
                <p className="text-[10px] font-medium uppercase tracking-[0.14em] text-text-muted mb-1.5">Weekly</p>
                <p className="font-display text-2xl font-bold tracking-[-0.02em] text-brand-accent tabular-nums">{weeklyReports}</p>
                <p className="text-[11px] text-text-muted mt-1.5">reports</p>
              </motion.div>
              <motion.div
                className="glass rounded-2xl p-5 flex flex-col justify-center"
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.38, delay: 0.14, ease: [0.22, 1, 0.36, 1] }}
              >
                <p className="text-[10px] font-medium uppercase tracking-[0.14em] text-text-muted mb-1.5">Monthly</p>
                <p className="font-display text-2xl font-bold tracking-[-0.02em] text-brand-accent tabular-nums">{monthlyReports}</p>
                <p className="text-[11px] text-text-muted mt-1.5">reports</p>
              </motion.div>
              <motion.div
                className="glass rounded-2xl p-5 flex flex-col justify-center"
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.38, delay: 0.18, ease: [0.22, 1, 0.36, 1] }}
              >
                <p className="text-[10px] font-medium uppercase tracking-[0.14em] text-text-muted mb-1.5">Clients Covered</p>
                <p className="font-display text-2xl font-bold tracking-[-0.02em] text-emerald-600 tabular-nums">{uniqueClients}</p>
                <p className="text-[11px] text-text-muted mt-1.5">in reports</p>
              </motion.div>
            </div>
            <div className="grid grid-cols-3 gap-6">
              {/* Generate Report Panel */}
              <div className="col-span-1 space-y-4">
                <motion.div
                  className="glass rounded-xl p-5 spotlight-card"
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.22, delay: 0.24 }}
                  whileHover={{ y: -2 }}
                  onMouseMove={(e) => { const rect = e.currentTarget.getBoundingClientRect(); e.currentTarget.style.setProperty("--mouse-x", `${e.clientX - rect.left}px`); e.currentTarget.style.setProperty("--mouse-y", `${e.clientY - rect.top}px`); }}
                >
                  <div className="flex items-center gap-2 mb-4">
                    <Sparkles size={14} className="text-brand-accent" />
                    <h2 className="text-sm font-semibold text-text-primary">Generate Report</h2>
                  </div>

                  {/* Client selector */}
                  <div className="space-y-3">
                    <div>
                      <label className="text-[10px] text-text-muted uppercase tracking-wider font-medium">Client</label>
                      <select
                        value={selectedClient}
                        onChange={e => setSelectedClient(e.target.value)}
                        className="input mt-1 text-xs"
                      >
                        <option value="">Select a client...</option>
                        {clients.map(c => (
                          <option key={c.id} value={c.id}>{c.business_name}</option>
                        ))}
                      </select>
                    </div>

                    {/* Report type */}
                    <div>
                      <label className="text-[10px] text-text-muted uppercase tracking-wider font-medium">Report Type</label>
                      <div className="flex gap-2 mt-1">
                        {(["weekly", "monthly"] as const).map(type => (
                          <button
                            key={type}
                            onClick={() => setReportType(type)}
                            className={`flex-1 py-2 px-3 rounded-xl text-xs font-medium border transition-all ${
                              reportType === type
                                ? "bg-[rgba(59,130,246,0.08)] border-[rgba(59,130,246,0.25)] text-brand-accent"
                                : "bg-surface-light border-border-subtle/30 text-text-muted hover:text-text-primary"
                            }`}
                          >
                            {type === "weekly" ? "Weekly" : "Monthly"}
                          </button>
                        ))}
                      </div>
                    </div>

                    <motion.div whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                      <button
                        onClick={generateReport}
                        disabled={!selectedClient || generating}
                        className="btn-primary w-full text-xs flex items-center justify-center gap-2"
                      >
                        {generating ? (
                          <><Loader size={12} className="animate-spin" /> Generating...</>
                        ) : (
                          <><Sparkles size={12} /> Generate Report</>
                        )}
                      </button>
                    </motion.div>
                  </div>

                  {/* Selected client preview */}
                  {selectedClient && (() => {
                    const client = clients.find(c => c.id === selectedClient);
                    if (!client) return null;
                    return (
                      <div className="mt-4 p-3 rounded-xl bg-surface-light border border-border-subtle/30">
                        <p className="text-xs font-medium text-text-primary">{client.business_name}</p>
                        <div className="flex items-center gap-3 mt-1.5 text-[10px] text-text-muted">
                          <span>MRR: ${client.mrr.toLocaleString()}</span>
                          <span>Health: {client.health_score}%</span>
                        </div>
                      </div>
                    );
                  })()}
                </motion.div>

                {/* Quick Generate for All */}
                <motion.div
                  className="glass rounded-xl p-5 spotlight-card"
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.22, delay: 0.30 }}
                  whileHover={{ y: -2 }}
                  onMouseMove={(e) => { const rect = e.currentTarget.getBoundingClientRect(); e.currentTarget.style.setProperty("--mouse-x", `${e.clientX - rect.left}px`); e.currentTarget.style.setProperty("--mouse-y", `${e.clientY - rect.top}px`); }}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <Users size={14} className="text-brand-accent" />
                    <h2 className="text-sm font-semibold text-text-primary">Batch Reports</h2>
                  </div>
                  <p className="text-[10px] text-text-muted mb-3">
                    Weekly reports are auto-generated every Friday at 3 PM via cron job. You can also generate individual reports on-demand above.
                  </p>
                  <div className="flex items-center gap-2 text-[10px] text-success">
                    <Clock size={10} />
                    <span>Next auto-run: Friday 3:00 PM</span>
                  </div>
                </motion.div>
              </div>

              {/* Report Output & History */}
              <div className="col-span-2 space-y-4">
                {/* Current Generated Report */}
                {currentReport && (
                  <motion.div
                    className="glass-indigo rounded-xl p-5 spotlight-card"
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.22 }}
                    whileHover={{ y: -2 }}
                    onMouseMove={(e) => { const rect = e.currentTarget.getBoundingClientRect(); e.currentTarget.style.setProperty("--mouse-x", `${e.clientX - rect.left}px`); e.currentTarget.style.setProperty("--mouse-y", `${e.clientY - rect.top}px`); }}
                  >
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-2">
                        <Sparkles size={14} className="text-brand-accent" />
                        <h2 className="text-sm font-semibold text-text-primary">
                          {currentReport.type === "monthly" ? "Monthly" : "Weekly"} Report � {currentReport.client}
                        </h2>
                      </div>
                      <div className="flex items-center gap-2">
                        <button onClick={copyReport} className="btn-secondary text-[10px] flex items-center gap-1">
                          {copied ? <Check size={10} /> : <Copy size={10} />}
                          {copied ? "Copied" : "Copy"}
                        </button>

                        {/* Export dropdown */}
                        <div className="relative" ref={exportRef}>
                          <button
                            onClick={() => setExportOpen(!exportOpen)}
                            className="btn-secondary text-[10px] flex items-center gap-1"
                          >
                            <Share2 size={10} />
                            Export Report
                            <ChevronDown size={10} className={`transition-transform ${exportOpen ? "rotate-180" : ""}`} />
                          </button>

                          {exportOpen && (
                            <div className="absolute right-0 top-full mt-1 w-52 bg-surface border border-border-subtle/50 rounded-xl shadow-elevated z-50 py-1">
                              <button
                                onClick={downloadReportHTML}
                                className="w-full flex items-center gap-2.5 px-3.5 py-2.5 text-left text-xs text-text-primary hover:bg-surface-light transition-colors"
                              >
                                <Download size={13} className="text-brand-accent" />
                                <div>
                                  <p className="font-medium">Download as HTML</p>
                                  <p className="text-[10px] text-text-muted mt-0.5">Print-ready with styling</p>
                                </div>
                              </button>
                              <button
                                onClick={copyReportMarkdown}
                                className="w-full flex items-center gap-2.5 px-3.5 py-2.5 text-left text-xs text-text-primary hover:bg-surface-light transition-colors"
                              >
                                <ClipboardCopy size={13} className="text-brand-accent" />
                                <div>
                                  <p className="font-medium">Copy to Clipboard</p>
                                  <p className="text-[10px] text-text-muted mt-0.5">Formatted Markdown</p>
                                </div>
                              </button>
                              <div className="border-t border-border-subtle/30 my-1" />
                              <button
                                onClick={handleEmailReport}
                                className="w-full flex items-center gap-2.5 px-3.5 py-2.5 text-left text-xs text-text-primary hover:bg-surface-light transition-colors"
                              >
                                <Mail size={13} className="text-brand-accent" />
                                <div>
                                  <p className="font-medium">Email Report</p>
                                  <p className="text-[10px] text-text-muted mt-0.5">Send to an email address</p>
                                </div>
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* Metrics bar */}
                    {currentReport.metrics && (
                      <div className="flex items-center gap-4 mb-4 p-3 bg-surface-light rounded-xl text-[10px]">
                        <div>
                          <span className="text-text-muted">Leads</span>
                          <div className="flex items-center gap-1 mt-0.5">
                            <span className="font-bold text-text-primary">{currentReport.metrics.leads}</span>
                            {currentReport.metrics.leads_trend !== "N/A" && (
                              <span className={`flex items-center ${parseInt(currentReport.metrics.leads_trend) >= 0 ? "text-success" : "text-danger"}`}>
                                {parseInt(currentReport.metrics.leads_trend) >= 0 ? <TrendingUp size={8} /> : <TrendingDown size={8} />}
                                {currentReport.metrics.leads_trend}%
                              </span>
                            )}
                          </div>
                        </div>
                        <div className="w-px h-6 bg-border-subtle" />
                        <div>
                          <span className="text-text-muted">Outreach</span>
                          <p className="font-bold text-text-primary mt-0.5">{currentReport.metrics.outreach}</p>
                        </div>
                        <div className="w-px h-6 bg-border-subtle" />
                        <div>
                          <span className="text-text-muted">Replies</span>
                          <p className="font-bold text-text-primary mt-0.5">{currentReport.metrics.replies}</p>
                        </div>
                        <div className="w-px h-6 bg-border-subtle" />
                        <div>
                          <span className="text-text-muted">Deals</span>
                          <p className="font-bold text-text-primary mt-0.5">{currentReport.metrics.deals_won} (${currentReport.metrics.deals_revenue.toLocaleString()})</p>
                        </div>
                        <div className="w-px h-6 bg-border-subtle" />
                        <div>
                          <span className="text-text-muted">Health</span>
                          <p className={`font-bold mt-0.5 ${currentReport.metrics.health_score >= 70 ? "text-success" : currentReport.metrics.health_score >= 40 ? "text-warning" : "text-danger"}`}>
                            {currentReport.metrics.health_score}%
                          </p>
                        </div>
                      </div>
                    )}

                    {/* Report text */}
                    <div className="prose prose-sm max-w-none">
                      <pre className="whitespace-pre-wrap text-xs text-text-primary leading-relaxed font-sans bg-surface-light rounded-xl p-4 border border-border-subtle/30 max-h-[500px] overflow-y-auto">
                        {currentReport.report}
                      </pre>
                    </div>
                  </motion.div>
                )}

                {/* Report History */}
                <motion.div
                  className="glass rounded-xl p-5"
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.22, delay: 0.12 }}
                >
                  <div className="flex items-center gap-2 mb-4">
                    <Clock size={14} className="text-text-muted" />
                    <h2 className="text-sm font-semibold text-text-primary">Report History</h2>
                    <span className="text-[9px] text-text-muted bg-surface-light px-2 py-0.5 rounded-full">{reports.length}</span>
                  </div>

                  {loading ? (
                    <div className="flex items-center justify-center py-12">
                      <Loader size={16} className="animate-spin text-text-muted" />
                    </div>
                  ) : reports.length === 0 ? (
                    <EmptyState
                      type="no-analytics"
                      title="No reports generated yet"
                      description="Select a client and generate your first AI-powered report."
                    />
                  ) : (
                    <div className="space-y-2">
                      {reports.map((report, index) => (
                        <motion.div
                          key={report.id}
                          className="border border-border-subtle/30 rounded-xl overflow-hidden"
                          initial={{ opacity: 0, x: -8 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ duration: 0.18, delay: index * 0.04 }}
                          whileHover={{ backgroundColor: "rgba(0,0,0,0.03)" }}
                        >
                          <button
                            onClick={() => setExpandedReport(expandedReport === report.id ? null : report.id)}
                            className="w-full flex items-center justify-between px-4 py-3 hover:bg-surface-light transition-colors"
                            aria-expanded={expandedReport === report.id}
                            aria-controls={`report-${report.id}-content`}
                          >
                            <div className="flex items-center gap-3">
                              <div className={`w-1.5 h-1.5 rounded-full ${report.result?.type === "monthly_report" ? "bg-info" : "bg-brand-accent"}`} />
                              <div className="text-left">
                                <p className="text-xs font-medium text-text-primary">{getClientName(report.client_id)}</p>
                                <p className="text-[10px] text-text-muted">
                                  {report.result?.type === "monthly_report" ? "Monthly" : "Weekly"} Report � {new Date(report.created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                                </p>
                              </div>
                            </div>
                            <div className="flex items-center gap-2">
                              {report.result?.metrics && (
                                <span className="text-[9px] text-text-muted bg-surface-light px-2 py-0.5 rounded-full">
                                  {report.result.metrics.leads} leads
                                </span>
                              )}
                              {expandedReport === report.id ? <ChevronUp size={12} className="text-text-muted" /> : <ChevronDown size={12} className="text-text-muted" />}
                            </div>
                          </button>

                          {expandedReport === report.id && report.result?.report && (
                            <div id={`report-${report.id}-content`} className="px-4 pb-4 border-t border-border-subtle/20">
                              <pre className="whitespace-pre-wrap text-[11px] text-text-primary leading-relaxed font-sans mt-3 bg-surface-light rounded-xl p-3 max-h-[300px] overflow-y-auto">
                                {report.result.report}
                              </pre>
                              <div className="flex items-center gap-2 mt-2">
                                <button
                                  onClick={() => {
                                    navigator.clipboard.writeText(report.result.report);
                                  }}
                                  className="text-[10px] text-text-muted hover:text-text-primary flex items-center gap-1 transition-colors"
                                >
                                  <Copy size={10} /> Copy
                                </button>
                              </div>
                            </div>
                          )}
                        </motion.div>
                      ))}
                    </div>
                  )}
                </motion.div>
              </div>
            </div>{/* Email report modal */}{emailFormOpen && (
              <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center">
                <div className="bg-surface border border-border-subtle/50  p-6 w-full max-w-sm shadow-elevated">
                  <div className="flex items-center gap-2 mb-4">
                    <Mail size={16} className="text-brand-accent" />
                    <h3 className="text-sm font-semibold text-text-primary">Email Report</h3>
                  </div>
                  <form onSubmit={submitEmailReport} className="space-y-3">
                    <div>
                      <label className="text-[10px] text-text-muted uppercase tracking-wider font-medium">Recipient Email</label>
                      <input
                        type="email"
                        required
                        value={emailAddress}
                        onChange={e => setEmailAddress(e.target.value)}
                        placeholder="client@example.com"
                        className="input mt-1 text-xs w-full"
                        autoFocus
                      />
                    </div>
                    <div className="flex items-center gap-2 pt-1">
                      <button type="submit" className="btn-primary text-xs flex-1">
                        Send Report
                      </button>
                      <button
                        type="button"
                        onClick={() => { setEmailFormOpen(false); setEmailAddress(""); }}
                        className="btn-secondary text-xs flex-1"
                      >
                        Cancel
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            )}</MotionPage>
  );
}
