import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-mesh py-16 px-4">
      <div className="max-w-2xl mx-auto">
        <Link href="/dashboard" className="text-xs text-gold hover:text-gold-light mb-8 inline-block">Back to Dashboard</Link>
        <h1 className="text-2xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-xs text-muted mb-8">Last updated: April 6, 2026</p>

        <div className="space-y-6 text-sm text-muted leading-relaxed">
          <section>
            <h2 className="text-sm font-semibold text-white mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using ShortStack OS (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">2. Description of Service</h2>
            <p>ShortStack OS is a digital marketing agency operating system that provides tools for lead generation, content creation, social media management, client management, and AI-powered automation. The Service is provided on a subscription basis.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">3. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use. You must be at least 18 years old to use the Service.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">4. Subscription & Payments</h2>
            <p>Subscriptions are billed monthly. All fees are non-refundable unless otherwise stated. We reserve the right to change pricing with 30 days notice. Free trials automatically convert to paid subscriptions.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">5. Acceptable Use</h2>
            <p>You agree not to: (a) use the Service for illegal purposes, (b) send spam or unsolicited messages in violation of platform policies, (c) attempt to reverse engineer the Service, (d) share your account with unauthorized users, (e) use the Service to harass or harm others.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">6. AI-Generated Content</h2>
            <p>Content generated by our AI tools is provided as-is. You are responsible for reviewing and approving all AI-generated content before publishing. We do not guarantee the accuracy, originality, or effectiveness of AI outputs.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">7. Social Media Integrations</h2>
            <p>By connecting your social media accounts, you authorize ShortStack OS to access and manage those accounts on your behalf within the permissions you grant. You can revoke access at any time.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">8. Limitation of Liability</h2>
            <p>ShortStack OS is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">9. Termination</h2>
            <p>Either party may terminate the subscription at any time. Upon termination, your access to the Service will end and your data may be deleted after 30 days.</p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-white mb-2">10. Contact</h2>
            <p>For questions about these terms, contact us at growth@shortstack.work.</p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-border/20 text-center">
          <p className="text-[10px] text-muted">ShortStack Agency | shortstack.work</p>
        </div>
      </div>
    </div>
  );
}
